### ISSUE TITLE
contact us button does not respond at PET NEWS section

### ISSUE THREAD

**Issue by Sushilverma002** [akshitagupta15june/PetMe#1011]
**Describe the bug**
contact us button does not respond at PET NEWS section
**To Reproduce**

**Expected behavior**
it must respond and show the contact form.
**Screenshots**

https://github.com/akshitagupta15june/PetMe/assets/114687502/32d205ca-6877-4c53-9224-3bc9f142f432

Desktop (please complete the following information):
 - OS: [window]
 - Browser [chrome]
 - Version [115.0.5790.110]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sushilverma002** [comment]
@akshitagupta15june have a look.

**Comment by emily883** [comment]
Assign this to me
