### ISSUE TITLE
navbar overlaps with content of sos page

### ISSUE THREAD

**Issue by Komal73** [akshitagupta15june/PetMe#1014]
**Describe the bug**
navbar overlaps the content on the sos page 

**To Reproduce**
1. Go to SOS page
2. Scroll down
3. See that the heading of the form is not visible

**Expected behavior**
to remove the  overlap and make the content visible

**Screenshots**
![Screenshot 2023-08-03 133831](https://github.com/akshitagupta15june/PetMe/assets/115211296/584c89fa-2b32-4804-a02f-0094dc9d101e)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: edge
 - Version : 106.0.1370.34

**Comment by Komal73** [comment]
@akshitagupta15june kindly check this issue and assign under GSSOC 23

**Comment by aditi-dsi** [comment]
Hi, I am taking up this issue to work upon. Thanks!

**Comment by aditi-dsi** [comment]
Hi, can I take up this issue to work upon?

**Comment by Komal73** [comment]
@aditi-dsi It is not assigned yet, you can create your own issues as well.
