### ISSUE TITLE
Nav Bar enhancement

### ISSUE THREAD

**Issue by Manishak798** [akshitagupta15june/PetMe#1018]
**Is your feature request related to a problem? Please describe.**
The nav elements are not aligned and the language selection button is not going with the theme, I want to enhance the entire nav bar along with hover effects.

**Describe the solution you'd like**
I will align the item correctly so they do not look odd, provide new hover effects to the button, and will redesign the language selection button

**Describe alternatives you've considered**
I want to make it more appealing to the visitors and make it more attractive so it becomes more engaging and relative. It is the first thing the visitor is going to see so we should consider its redesigning.

**Additional context**
I want to work on this feature, please assign this to me under GSSOC23.

**Comment by Aryan-Kohli** [comment]
please assign me this issue under SWOC'24
