### ISSUE TITLE
Contact us and toggle theme button need to be improved

### ISSUE THREAD

**Issue by Ahnaf-codes** [akshitagupta15june/PetMe#103]
Currently the Contact us and toggle theme button looks like they are disabled. It would be better to make them brighter and more vibrant.
![Screenshot 2022-10-02 at 18-14-58 PetMe](https://user-images.githubusercontent.com/102795582/193453554-d87f7719-1c8a-4006-87d2-393211fc7a0a.png)

**Comment by Ahnaf-codes** [comment]
@akshitagupta15june Im willing to work on this

**Comment by akshitagupta15june** [comment]
yes work on it
