### ISSUE TITLE
Improve the Back to top button in the blog page

### ISSUE THREAD

**Issue by debdutta04** [akshitagupta15june/PetMe#1030]
**Is your feature request related to a problem? Please describe.**
the back to top button is not working properly 

**Describe the solution you'd like**
I would like to change the Scroll to Top icon and also add hover effect to it.

**Additional context**
please assign me this under Gssoc'23

**Comment by akshitagupta15june** [comment]
its not required currently

**Comment by Vishal-1004** [comment]
@akshitagupta15june mam dont you think that the scroll to top button should be in the right side making it more convenient for the users,
generally scroll to top buttons are present at the right side of the website i have never seen any website which has it in the left side
