### ISSUE TITLE
Improve the main readme

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#105]
beautify the current readme

**Comment by Santhusha-bit** [comment]
Can I work on this

**Comment by krupalitrivedi** [comment]
Hi Akshita! I worked on this issue previously :) and made a mistake while making a pull request, Can you check again and then tell the other person to make changes if needed, otherwise both works will go in vein :) thank you!

**Comment by akshitagupta15june** [comment]
Closing this issue

**Comment by chiragkhatri19** [comment]
Hello Akshita, Can I add some custom made banner or something in the readme file ? and if yes can you create a issue for the same, I'll happily contribute
