### ISSUE TITLE
[BUG]: Text Not Clearly Visible on Cards in Light Mode

### ISSUE THREAD

**Issue by SaketKaswa20** [akshitagupta15june/PetMe#1051]
**Describe the bug**
The Text is not clearly visible on cards in light mode.

**To Reproduce**
1. Go to 'https://akshitagupta15june.github.io/PetMe/'
2. Click on 'Light Mode'
3. Scroll down to 'Meet Our Friends' Section

**Expected behavior**
The text should be clearly visible. We can change the colour of cards or change the text colour.

**Screenshots**
![Screenshot from 2023-08-14 21-56-33](https://github.com/akshitagupta15june/PetMe/assets/105808363/bb02b3d3-26d8-45d8-968b-a3a714bd0b6f)

**Comment by Vijeth56** [comment]
I would like to work on this issue, please assign this to me?

**Comment by akshitagupta15june** [comment]
Go for it

**Comment by akshitagupta15june** [comment]
its visible
