### ISSUE TITLE
Top left page banner and Home button do the same job 

### ISSUE THREAD

**Issue by chroniste** [akshitagupta15june/PetMe#1055]
**Describe the bug**
Top left page banner and Home button return you to the homepage . 
So they are used for the exact same purpose . 

**To Reproduce**
1. Go to 'https://akshitagupta15june.github.io/PetMe/'
2. Click on 'SOS Report'
3. You have two options to return to the homepage . 
The first one is the top left page banner and the second one is the Home button. 
This could confuse the user about the operation of the two buttons . 

**Expected behavior**
I would expect the top left banner not to be used as a button to return you to the homepage .

**Screenshots**
Both return you to the homepage . 
![Στιγμιότυπο οθόνης (185)](https://github.com/akshitagupta15june/PetMe/assets/92442636/f75c976c-0b9b-4254-a763-1130b9a3f592)
![Στιγμιότυπο οθόνης (187)](https://github.com/akshitagupta15june/PetMe/assets/92442636/86861fe5-350f-42bb-8d52-cc78771f0cff)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Chrome]

**Comment by akshitagupta15june** [comment]
yes! buts its ok for site
