### ISSUE TITLE
Improvements to the footer section

### ISSUE THREAD

**Issue by d3vsuthar** [akshitagupta15june/PetMe#106]
![petme-footer-before](https://user-images.githubusercontent.com/46597688/193457319-e5edb1bf-cbd2-4431-8bf0-aaa2f70c8e5b.jpg)

Found the following UX and design issues
- Responsiveness on md screens (should be 2 columns instead of 3)
- Logo is squished 
- Email section is too cluttered
- Color scheme looks out of place with the rest of the section (why use blue here?)

**Comment by akshitagupta15june** [comment]
Go for it

**Comment by Samriddh2703** [comment]
assign it please to me
