### ISSUE TITLE
Enhance UI for "Meet our Friends Here" Section

### ISSUE THREAD

**Issue by Panth1823** [akshitagupta15june/PetMe#1067]
**Enhance the "Meet our Friends Here" section's UI by replacing the previous rectangular design with more suitable styling, aligning it with UI standards and improving the overall user experience.**

 **Before :**
![before](https://github.com/akshitagupta15june/PetMe/assets/89696311/3751bfeb-6693-4189-b9b1-a2c4bdf7b639)

**After :**
![after](https://github.com/akshitagupta15june/PetMe/assets/89696311/b03c3714-db23-4edb-b05d-195061c61f50)

**Comment by PrajwalGraj** [comment]
I would like to work on it. Can u assign this to me

**Comment by Sruti-sahini** [comment]
Hi @akshitagupta15june  , I am from JOWC, please assign me this issue.
