### ISSUE TITLE
Dockerize this project

### ISSUE THREAD

**Issue by Ayaan49** [akshitagupta15june/PetMe#1071]
**Is your feature request related to a problem? Please describe.**
I'd like to suggest Dockerizing our application to improve deployment and maintainability.

**Describe the solution you'd like**
Dockerization offers numerous benefits, including enhanced portability, consistent environments across different stages of development, and simplified dependency management. It can also help with scaling our application more efficiently.

**Describe alternatives you've considered**
- Docker containers would make it easier to deploy our application on various cloud platforms.
- Developers can work in identical environments, reducing the "it works on my machine" issue.
- We can automate testing and deployment workflows more effectively with Docker.

**Comment by Viveksati5143** [comment]
Hey @akshitagupta15june I would like to work on this issue

**Comment by Ayaan49** [comment]
> Hey @akshitagupta15june I would like to work on this issue

Thanks for your interest , but I raised this issue so if this gets accepted then I am working on this.
