### ISSUE TITLE
Copyright year should be dynamic

### ISSUE THREAD

**Issue by Vidip-Ghosh** [akshitagupta15june/PetMe#1077]
**Describe the bug**
Copyright year should change with year. It still shows Copyright 2022.. 

**To Reproduce**

**Expected behavior**

**Screenshots**

<img width="1680" alt="Screenshot 2023-10-02 at 13 39 49" src="https://github.com/akshitagupta15june/PetMe/assets/91741581/3f9b31f6-13a5-4931-a4ee-9092353edd82">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by akshitagupta15june** [comment]
Go for it

**Comment by HimanshuMahto** [comment]
Hey @akshitagupta15june can i work on this issue please.

**Comment by Vidip-Ghosh** [comment]
Hey @HimanshuMahto, this issue has already been completed via #1079
