### ISSUE TITLE
news favicon not present

### ISSUE THREAD

**Issue by S-ishita** [akshitagupta15june/PetMe#1078]
**Describe the bug**
news favicon not present
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
PLease assign this issue to me under hacktober fest

**Comment by shivam200446** [comment]
please assign me i want to work on it

**Comment by Azhar-0401** [comment]
@akshitagupta15june I am contributor under GSSO24 and i can add news favicon
