### ISSUE TITLE
"Blogs" page footer LOGO error

### ISSUE THREAD

**Issue by PrajwalGraj** [akshitagupta15june/PetMe#1094]
**Describe the bug**
The LOGO which is in footer of “BLOGS” , when clicked it is not working.Its not scrolling the webpage all the way top

**To Reproduce**
1. Go to Website
2. Click on 'Blogs'
3. Scroll down to find the LOGO in footer
4. Click it
5. Doesn’t work

**Expected behavior**
On clicking on the LOGO, it should scroll the webpage all the way to the top.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser:Chrome

**Comment by akshitagupta15june** [comment]
go for it

**Comment by Shivangi015** [comment]
Hey @akshitagupta15june please assign this issue to me.
