### ISSUE TITLE
Submit Button of Volunteer Page 

### ISSUE THREAD

**Issue by ayan-joshi** [akshitagupta15june/PetMe#1099]
**Is your feature request related to a problem? Please describe.**

The submit button in the volunteer html page is of indigo color which is not matching to the theme of the website I would like to update the button.

**Describe the solution you'd like**

![Screenshot 2023-10-04 030114](https://github.com/akshitagupta15june/PetMe/assets/96243602/294055df-2118-4f2e-ba1e-f16fac1b9ff8)

So the color of the button should be matching to the bg color of navbar, I will update the button similar to the navbar background color.

**Additional context**
Please assign me this issue under hacktoberfest label @akshitagupta15june

**Comment by bisariyon** [comment]
I would like to work on this issue @ayan-joshi . Please assign me this issue

**Comment by pabitra0011** [comment]
please assign me this issue under hacktoberfest label @akshitagupta15june

**Comment by Shivangi015** [comment]
Hey @Susmita-Dey please assign this issue to me.

**Comment by SrinehaMukku** [comment]
please assign this issue to me
