### ISSUE TITLE
About us content not visible in NIGHT/LIGHT mode

### ISSUE THREAD

**Issue by PrajwalGraj** [akshitagupta15june/PetMe#1109]
**Describe the bug**
Text in About us section is not visible in LIGHT/NIGHT mode

**To Reproduce**
1. Go to Website
2. Click on ‘About us’
3. Click on Light/NIGHT Mode

**Expected behavior**
Content should be visible [font colour:BLACK]

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Screenshots**

Day mode:
<img width="1421" alt="Screenshot 2023-10-04 at 7 51 44 PM" src="https://github.com/akshitagupta15june/PetMe/assets/113518358/ca336a4b-c85a-4a82-9484-0e8cc3c70baf">

Night mode:
<img width="1421" alt="Screenshot 2023-10-04 at 7 51 54 PM" src="https://github.com/akshitagupta15june/PetMe/assets/113518358/f20048dd-02f1-47c3-8c6a-292b4fb0dc3b">

**Comment by victor-duarte** [comment]
Relates to https://github.com/akshitagupta15june/PetMe/issues/998

**Comment by AaadityaG** [comment]
Can I work on it?
