### ISSUE TITLE
"Meet our Friends here" is appearing too big in phone and also there's a text overflow

### ISSUE THREAD

**Issue by 404Nikhil** [akshitagupta15june/PetMe#1116]
![image](https://github.com/akshitagupta15june/PetMe/assets/83774380/677b089e-7256-4a37-9fa3-cd2396d59223)

The "s" in "Friends" is overflowing from the text-box, and the entire text is occupying 75% of the screen, which is not very visually appealing.

please assign me this issue.

**Comment by Lokendrakushwah12** [comment]
Can you please assign me this issue :)
