### ISSUE TITLE
Design blog.html page

### ISSUE THREAD

**Issue by sshiwangi** [akshitagupta15june/PetMe#112]
**Is your feature request related to a problem? Please describe.**
The blog.html page is empty. It will be good to have a blog page where users can share their experience with the organization. 

**Describe the solution you'd like**
I would like to design blog.html page following the color theme of the website.

**Additional context**

**Comment by sshiwangi** [comment]
@akshitagupta15june please assign me this issue under hacktoberfest.

**Comment by akshitagupta15june** [comment]
Currently we don't have any blogs and page is already created better is we should have atleast 2-3 blogs so that we can create this page
You can see this issue #60
