### ISSUE TITLE
Github logo on Contributors Section

### ISSUE THREAD

**Issue by gpt-anurag** [akshitagupta15june/PetMe#113]
![image](https://user-images.githubusercontent.com/95965664/193466866-9eb42717-143b-46d9-9e18-06fcb0c9b42f.png)
There's no GitHub logo.

**Comment by akshitagupta15june** [comment]
Please add it

**Comment by harsitagarwalla187** [comment]
Can you assign it to me?

**Comment by Samriddh2703** [comment]
please assign me...
