### ISSUE TITLE
Add the mandatory mark + validation in adopt screen

### ISSUE THREAD

**Issue by asfaqehussain** [akshitagupta15june/PetMe#1152]
**Is your feature request related to a problem? Please describe.**
The user is not able to check which fields are mandatory to be entered and phone number validation is also not given user is able to enter any number in any length

**Describe the solution you'd like**
The user will be able to see the mandatory fields with red mark and then I'll add the phone number validation 

**Screenshot**
Below is the marked area where I'm mentioning the changes to be done.
![Annotation 2023-10-07 122214](https://github.com/akshitagupta15june/PetMe/assets/51645676/e8c95bdd-7c28-4f4a-b43e-358d35619cb2)

Please review and assign this issue to me and add hacktoberfest tag

**Comment by atulsahani8** [comment]
assign me the issue I'll fix it

**Comment by akshitagupta15june** [comment]
its not needed currently in this form
