### ISSUE TITLE
Form error when enter wrong email format 

### ISSUE THREAD

**Issue by asfaqehussain** [akshitagupta15june/PetMe#1154]
**Describe the bug**

**To Reproduce**
1. Go to the Donate screen & enter all other required details
2. Now enter the email as 'test@test' do not add the '.com'
3. Click the donate button 

**Expected behavior**
An Error will be there for the form validation I have added the screenshot for that below.

- After that when we try to go to that screen again then all the entered values in the form are cleared and we have to enter the values again

**Screenshots**

![Annotation 2023-10-07 123156](https://github.com/akshitagupta15june/PetMe/assets/51645676/df73cd96-69c4-4d5f-ab12-c2d0f2d98cf2)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
Please assign this issue to me and add the hacktoberfest tag to this.

**Comment by akshitagupta15june** [comment]
its already present in forms
