### ISSUE TITLE
Some text not visible in dark mode

### ISSUE THREAD

**Issue by asfaqehussain** [akshitagupta15june/PetMe#1155]
**Describe the bug**
When switch to dark mode than some of the text are not visible.

**To Reproduce**
1. Go to Home
2. Click on the Theme switch and switch to light mode
3. See error

**Screenshots**

![Annotation 2023-10-07 125051](https://github.com/akshitagupta15june/PetMe/assets/51645676/64b8efd4-bb57-4687-9560-08e36cd9b23a)

Please assign this issue to me add the hacktoberfest tag.

**Comment by amrahs02** [comment]
can i work on this issue

**Comment by akshitagupta15june** [comment]
someone is already looking into it
