### ISSUE TITLE
Change the logo of cat dog rabbit to white as they are not visible in current UI 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#117]

**Comment by yesimhozman** [comment]
Hello @akshitagupta15june . Can you specify the need? You mean the cat dog and rabbit are not visible so maybe we can use transparent background ?

**Comment by akshitagupta15june** [comment]
![Screenshot_20221002-225423](https://user-images.githubusercontent.com/57909583/193468222-dc9bebb9-56b4-47c8-a26c-4f1637801049.png)
See the logo is not visible

**Comment by akshitagupta15june** [comment]
Before dog and Delhi
It's black

**Comment by akshitagupta15june** [comment]
It should be white

**Comment by yesimhozman** [comment]
ok, you mean the location and animal icons should be white. Could you assign it to me ?

**Comment by akshitagupta15june** [comment]
Ofcourse
