### ISSUE TITLE
Footer Section Is Missing In Donate Page.

### ISSUE THREAD

**Issue by pabitra0011** [akshitagupta15june/PetMe#1178]
Footer Section Is Missing In Donate Page. It must be there like any other page.

**Describe the solution you'd like**
Adding Footer section in Donate page improve it's UI.

Screenshort -
![image](https://github.com/akshitagupta15june/PetMe/assets/94389910/98cf88ec-eea5-4efd-a9fe-74704f409638)

**Comment by pabitra0011** [comment]
@akshitagupta15june Please assing me this issue with hacktoberfest tag.
I want to work on this issue.

Thank You

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me
