### ISSUE TITLE
Improve the design of the contact form

### ISSUE THREAD

**Issue by viditagrawal56** [akshitagupta15june/PetMe#1188]
**Is your feature request related to a problem? Please describe.**
The current contact from looks very dated and does not fit the page. The contact form does not stand out and does not provide enough contrast from the background.

![Screenshot 2023-10-06 205849](https://github.com/akshitagupta15june/PetMe/assets/52532308/ed586686-ab95-4053-b630-0cfe10ab8628)

**Describe the solution you'd like**

Improvement of the design of the contact form to make it look more appealing and modern

**Comment by Shashankpantiitbhilai** [comment]
I am interested,assign this to me and give the issue hactoberfest label

**Comment by viditagrawal56** [comment]
@akshitagupta15june  I have already opened a pr before please assign me this issue.
I will resolve all the conflicts ASAP

**Comment by viditagrawal56** [comment]
Hey @akshitagupta15june this is the third time I am asking you to assign me this issue. Earlier you closed my pr because I wasn't assigned the issue. But this time I am asking you to assign me this issue and you are not responding. Please assign me this issue.
