### ISSUE TITLE
Improvements in the adopt.html navbar

### ISSUE THREAD

**Issue by sshiwangi** [akshitagupta15june/PetMe#119]
**Is your feature request related to a problem? Please describe.**
The navbar section of adopt.html page is not complementing the reportstary.html navbar.
Adopt.html
![petme](https://user-images.githubusercontent.com/77545230/193467727-01807398-888e-4315-9b5e-6ab8aa7af8c3.png)
reportstary.html
![petme2](https://user-images.githubusercontent.com/77545230/193467751-f4341b83-d8c5-4d6b-9dd9-877285c835ea.png)

**Describe the solution you'd like**
I would like to change the color of home and add other items in the navbar such as contact and donate.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by sshiwangi** [comment]
@akshitagupta15june please assign me this issue under hacktoberfest.

**Comment by akshitagupta15june** [comment]
go for it @sshiwangi

**Comment by Samriddh2703** [comment]
can you assign it to me?
