### ISSUE TITLE
Adopt file bug

### ISSUE THREAD

**Issue by ayan-joshi** [akshitagupta15june/PetMe#1196]
**Describe the bug**
So in the adopt.html file in the navbar we have a option in support us which have a markdown volunteer 
the hover on the volunteer just makes the impression bad , I would like to work on it and improve it to match it with the navbar and whole webpage.

**Screenshots**

![Screenshot (225)](https://github.com/akshitagupta15june/PetMe/assets/96243602/40fb5910-6c81-4c98-9876-f2fbd8231351)

**Additional context**
Please assign me this issue @akshitagupta15june  @Susmita-Dey

**Comment by akshitagupta15june** [comment]
go for it
