### ISSUE TITLE
Help Button Not Fully Visible on Mobile view.

### ISSUE THREAD

**Issue by 404Nikhil** [akshitagupta15june/PetMe#1202]
Actual Results:
The Help button is not fully visible. It is only partially visible, making it difficult for users to access it.
![image](https://github.com/akshitagupta15june/PetMe/assets/83774380/39061164-2667-4a63-93eb-d7915328a381)

Expected Results:
The Help button should be fully visible and accessible to users without any visual obstruction.
![image](https://github.com/akshitagupta15june/PetMe/assets/83774380/915fdf18-e905-455e-add8-b051bd74fa6b)

Please assign this issue to me.

PR is linked below

**Comment by BoshraJaber** [comment]
Hello @404Nikhil 
Would like to help if help is still needed

**Comment by 404Nikhil** [comment]
> Hello @404Nikhil 
> Would like to help if help is still needed

Thank you @BoshraJaber but I have already fixed the issue. PR for is attached under the issue. If a change is suggested to me which require some help I'll let you know.
