### ISSUE TITLE
adopt me button UI improvement

### ISSUE THREAD

**Issue by GURMEHAR-PEC** [akshitagupta15june/PetMe#1227]
**Is your feature request related to a problem? Please describe.**
This is in context with the UI. I personally think that the "Adopt me" button on the 'meet your friends' page needs some better styling
**Describe the solution you'd like**
I can improve the styling of the button and also plan to give it a 3-D effect while hovering.

**Describe alternatives you've considered**
We can simply do some changes with the font colour too , but in order to make the UI look more appealing ,  I believe my solution can address the problem effectively

PS: @akshitagupta15june please assign me this issue.I would be happy to contribute .
Thanks!

**Comment by devdeep2003** [comment]
Hey ! I would like to contribute to it . Assign me
