### ISSUE TITLE
Error in the "Donate" page

### ISSUE THREAD

**Issue by PrajwalGraj** [akshitagupta15june/PetMe#1233]
**Describe the bug**
“Donate” page has been changed.The present Donate page is still not yet completed and its not looking nice.

**To Reproduce**
1. Go to Website
2. Click on ‘Donate’
3. You will see a page which is not yet ready.

**Expected behavior**
It should be like this.So I will change the file 
![Screenshot 2023-10-15 at 2 41 46 PM](https://github.com/akshitagupta15june/PetMe/assets/113518358/c92daca1-2621-4d51-bc5c-d1b745157091)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser:Chrome

**Screenshots**
Present:

![Screenshot 2023-10-15 at 2 41 33 PM](https://github.com/akshitagupta15june/PetMe/assets/113518358/d395af61-f484-4168-8528-2f5509b4cc73)

**Comment by akshitagupta15june** [comment]
Go for it!
