### ISSUE TITLE
No Footer in "SOS Report" page

### ISSUE THREAD

**Issue by PrajwalGraj** [akshitagupta15june/PetMe#1235]
**Describe the bug**
Footer is missing in “SOS Report” page

**To Reproduce**
1. Go to Website
2. Click on ‘SOS Report’
3. Scroll down
4. No Footer

**Expected behavior**
To have a FOOTER below

**Desktop :**
 - OS: Mac OS
 - Browser:Chrome

**Screenshots**

<img width="1421" alt="Screenshot 2023-10-15 at 3 16 02 PM" src="https://github.com/akshitagupta15june/PetMe/assets/113518358/65e34746-ff51-4c64-a779-b0871d6f64c1">

**Comment by khushminder270** [comment]
@PrajwalGraj  please assign this issue to me
