### ISSUE TITLE
Inconsistencies in font colours throughout website in light mode

### ISSUE THREAD

**Issue by varundhand** [akshitagupta15june/PetMe#1242]
**Describe the bug**
In the website's light mode, there are inconsistencies in font colors in various sections of the site. This leads to font colors that are not appropriate, making it challenging for users to read content and impacting the overall user experience.

**To Reproduce**
1. Visit the website in light mode.
2. Navigate to different sections of the site, such as main heading, Adopt me button in the cards, etc
3. Observe font color inconsistencies that blend with the website's background, making it difficult to read content.

**Expected behavior**
In light mode, font colors across all sections of the website should provide good contrast with the background, ensuring readability and a positive user experience.

**Screenshots**
These inconsistencies in the font colors need to be fixed.
![Screenshot 2023-10-16 at 12 24 46 AM](https://github.com/akshitagupta15june/PetMe/assets/110025628/59580dd1-21e8-4598-bc88-06481b2041cc)

![Screenshot 2023-10-16 at 12 24 56 AM](https://github.com/akshitagupta15june/PetMe/assets/110025628/70981523-ebf8-41ca-a92a-49fcd17a174f)

![Screenshot 2023-10-16 at 12 25 04 AM](https://github.com/akshitagupta15june/PetMe/assets/110025628/60d4cbf0-f7fb-427c-913a-fbeee9b92f8f)

**Desktop (please complete the following information):**
 - OS: macOS 14.0
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: 17
 - Browser: Chrome

**Additional context**
I would like to work on this issue. Could you please assign it to me?
Additionally, could you please label this issue as "hacktoberfest" and "hacktoberfest-accepted"? Thank you!

**Comment by Pratikdate** [comment]
Assigned me i will do it
