### ISSUE TITLE
Github Icon Not Visible 

### ISSUE THREAD

**Issue by varundhand** [akshitagupta15june/PetMe#1249]
**Describe the bug**
The GitHub icon in the footer is currently **not as visible** as it should be. It needs to be made **lighter** to improve its visibility and alignment with the rest of the content.

**To Reproduce**
1. Go to the website's footer.
2. Go to the website's footer.

**Expected behavior**
The GitHub icon in the footer should be made lighter, ensuring that it's clearly visible and stands out from the background.

**Screenshots**

_The icon blends in with the background, which isnt ideal_
![Screenshot 2023-10-16 at 3 11 21 PM](https://github.com/akshitagupta15june/PetMe/assets/110025628/cca22bca-4a8c-4819-8193-1e457c6aa70b)

**Desktop (please complete the following information):**
 - OS: macOS 14
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: 17.1
 - Browser: Chrome

**Additional context**
I would like to work on this issue. Could you please assign it to me?

**Comment by akshitthakur128** [comment]
Hi! @varundhand 
I am Akshit, currently a beginner, i would like to work on this issue. Can you please assign it to me?

**Comment by DarshSohaliya** [comment]
I would like to work on that issue under JWOC

**Comment by varundhand** [comment]
@akshitthakur128 @DarshSohaliya The issue has already been fixed and merged. Im closing this now.
