### ISSUE TITLE
Navbar font size inconsistent

### ISSUE THREAD

**Issue by Vidip-Ghosh** [akshitagupta15june/PetMe#1264]
**Describe the bug**
I found that in light mode, navbar font size is not consistent. 

**To Reproduce**

**Expected behavior**
Font size should be uniform for all pages navbar. 

**Screenshots**

<img width="1680" alt="Screenshot 2023-10-17 at 17 04 20" src="https://github.com/akshitagupta15june/PetMe/assets/91741581/f3057907-207b-4a1f-a428-88f9ce74fb75">

<img width="1680" alt="Screenshot 2023-10-17 at 17 03 51" src="https://github.com/akshitagupta15june/PetMe/assets/91741581/122df818-570d-49ef-85e2-365b913a4b43">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Avtech04** [comment]
assign me this issue

**Comment by Vidip-Ghosh** [comment]
> assign me this issue

Issues are assigned on First come first serve basis. 
The person who opened the issue will be given preference.

**Comment by akshitagupta15june** [comment]
Go for it!
