### ISSUE TITLE
index html file bug 

### ISSUE THREAD

**Issue by ayan-joshi** [akshitagupta15june/PetMe#1267]
**Describe the bug**
to improve the contact us button it's not matching the styling of the file 

**Screenshots**
![Screenshot 2023-10-17 220349](https://github.com/akshitagupta15june/PetMe/assets/96243602/bdc13eb1-099b-42ae-8e93-217e749b8f2b)

**Additional context**
I'll solve it assign me the issue @akshitagupta15june @Susmita-Dey

**Comment by akshitagupta15june** [comment]
its ok no need to change
