### ISSUE TITLE
bug in reportstray.html

### ISSUE THREAD

**Issue by ayan-joshi** [akshitagupta15june/PetMe#1268]
**Describe the bug**
The submit button of the form in the file does not match the styling of the file , it should be improved 

**Screenshots**

![Screenshot 2023-10-17 221359](https://github.com/akshitagupta15june/PetMe/assets/96243602/3c641f9d-4856-4f81-851f-f63f3328af30)

**Additional context**
I'l improve the button , assign me the issue @akshitagupta15june @Susmita-Dey

**Comment by Pratikdate** [comment]
Assigned me I will work on it

**Comment by akshitagupta15june** [comment]
It's ok 
No need to change
