### ISSUE TITLE
Inconsistency in colors of social media in footer

### ISSUE THREAD

**Issue by Lokendrakushwah12** [akshitagupta15june/PetMe#1269]
**Describe the bug**

**To Reproduce**
1. Go to [website](https://akshitagupta15june.github.io/PetMe/)
2. Scroll down to footer
![image](https://github.com/akshitagupta15june/PetMe/assets/118094744/788ad169-e4a5-4ab7-972b-e3404c417703)

**Expected behavior**
colors needs to match with the overall ui of website

**Would you like to work on this?**
Yes i will work on it assign it to me

**Comment by Gauravtb2253** [comment]
i would like to work on this
