### ISSUE TITLE
Consistent Social Media Icons

### ISSUE THREAD

**Issue by iamanurag101** [akshitagupta15june/PetMe#1270]
**Is your feature request related to a problem? Please describe.**
Inconsistent color style of social media icons
<img width="212" alt="Inconsistent" src="https://github.com/akshitagupta15june/PetMe/assets/139618603/3e48499c-52b2-47a8-8267-915c93344137">

**Describe the solution you'd like**
Consistent color of social media icons

**Describe alternatives you've considered**

**Additional context**

**Comment by Avtech04** [comment]
Assign me this issue

**Comment by Shreyc711** [comment]
assign #1270
