### ISSUE TITLE
Add 'onClick' functionality to social handles in footer

### ISSUE THREAD

**Issue by bhattabhi013** [akshitagupta15june/PetMe#128]
**Describe the bug**
After clicking on social handles (facebook, Instagram), nothing happens.

**To Reproduce**
1. Go to the footer section.
2. Click on Facebook or Instagram icon.
3. See an error

**Expected behavior**
Redirect to the respective handles or remove the icons from footer if social handle not available

**Screenshots**
<img width="188" alt="image" src="https://user-images.githubusercontent.com/47862474/193475867-1473230d-307f-4168-b118-273434470ee6.png">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome]

**Comment by akshitagupta15june** [comment]
Currently social handles not available but we are planning to create ones so right now this issue is not required
