### ISSUE TITLE
[BUG] Contact us button not working in "Pet News" page

### ISSUE THREAD

**Issue by PrajwalGraj** [akshitagupta15june/PetMe#1283]
**Describe the bug**
“Contact us” nav not working in PET NEWs page

**To Reproduce**
1. Go to Website
2. Click on ‘Pet News’
3. Click on ‘Contact us’

**Expected behavior**
On clicking “Contact us” it should redirect us to the Contact us form.

**Desktop :**
 - OS: Mac OS
 - Browser:Chrome

**Screenshots**

https://github.com/akshitagupta15june/PetMe/assets/113518358/349cd289-dcf9-4b01-90dc-563cced1dd2f

**Comment by sohail300** [comment]
Can this be assigned to me?

**Comment by rishabhh23** [comment]
I have figured out the problem and would like to contribute to this issue, Please assign it to me :)
