### ISSUE TITLE
Improve "Our Contributor section"

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#129]
![image](https://user-images.githubusercontent.com/57909583/193492724-04e93b8b-2965-465e-8146-e43a9aae22be.png)

there is no github icon image as well as no proper spacing

**Comment by danschenker** [comment]
I'd be happy to take this on if you're willing, @akshitagupta15june!

**Comment by akshitagupta15june** [comment]
Go for it
