### ISSUE TITLE
Collect pet owners details who want to sell their pets

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#13]

**Comment by narayan954** [comment]
@akshitagupta15june I can work on this issue , please assign it to me :)

We have to create a simple form similar to the adopt form right?

**Comment by akshitagupta15june** [comment]
No it's already created we have make a backend connectivity @muditchoudhary can you please help him whenever free

**Comment by muditchoudhary** [comment]
Hello, @narayan954 Thanks for showing interest in contributing to petMe.
So, do you know know how to make a database? For this, we need a database to store the owner's details who is donating his/her pet.

**Comment by narayan954** [comment]
database as in MySQL or MongoDB? I can give that a try. Do I have to create my own dB or it'll be provided ?

**Comment by muditchoudhary** [comment]
You need to use mongo because someone else is also working on the backend part and he is using mongo. 

Yes you need to create a database I will give you basic schema like what details we will store etc.

**Comment by narayan954** [comment]
oh okkk, is there any communication channel?

**Comment by muditchoudhary** [comment]
@narayan954 We can communicate here also. And there is a discord too you can find it on the readme
