### ISSUE TITLE
Improve the footer section 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#132]
![image](https://user-images.githubusercontent.com/57909583/193497286-f656ac71-5514-43bb-8e33-5df5157d43ec.png)

footer and contributor section should have a proper spacing
and all the things should be aligned

**Comment by deven-533** [comment]
Please Assign me this issue ma'am

**Comment by akshitagupta15june** [comment]
ok!

**Comment by d3vsuthar** [comment]
looks like this was broken by the other PRs @akshitagupta15june :/

**Comment by akshitagupta15june** [comment]
yeah
