### ISSUE TITLE
[Bug]:CSS Properties of Google Translate Bar are not being reflected properly

### ISSUE THREAD

**Issue by JiyaGupta-cs** [akshitagupta15june/PetMe#1350]
**Bug:-**
In the navbar below the translate searchbar "Powered By" is written whose sense is incomplete without "Powered by Google".
Upon inspecting I found that CSS has been written to hide it, "Google Translate" img is hidden by that but it is not being reflected on "Powered By", it is being overridden by some other properties.
I have fixed that issue.

**Screenshots**
![image](https://github.com/akshitagupta15june/PetMe/assets/140608790/2c6c4c26-6365-4578-a0c7-81e6a7cd9448)

**Expected behavior**
The "Powered By" Text should also be removed.

![image](https://github.com/akshitagupta15june/PetMe/assets/140608790/c4295db7-83b2-40a1-bdc1-e5d4da305f13)

**Comment by saurabhkurve** [comment]
Can I work on this issue?
