### ISSUE TITLE
dark theme for 'Blogs' and 'Donate' pages

### ISSUE THREAD

**Issue by Srish-ty** [akshitagupta15june/PetMe#1356]
**Describe the bug**
- The dark theme is implemented in 'home' and 'meet pets' pages
- But the 'Blogs' and 'Donate' pages don't have dark theme implemented
- Even after clicking dark theme, only the navbar gets changed but not the page or any container on the rest of the page.
- These pages remain intact, there's no change in color or background of page
**To Reproduce**
1. Go to [the website](https://akshitagupta15june.github.io/PetMe/index.html)
2. Click on Blogs in navbar. [Blogs](https://akshitagupta15june.github.io/PetMe/blog.html)
3. Scroll down to Blogs cards

**Expected behavior**
- The colors and texts of the entire page should change with the theme

**Screenshots**

![Screenshot 2023-10-27 171929](https://github.com/akshitagupta15june/PetMe/assets/68679980/645e1efc-9fba-4e58-9682-2e3119f9e178)

![Screenshot 2023-10-27 172259](https://github.com/akshitagupta15june/PetMe/assets/68679980/7400f1d5-7400-4668-b8f3-13ecf4203b0d)

**Desktop (please complete the following information):**
 - Browser [All the browsers]

**Smartphone (please complete the following information):**
 - Device: [All devices]
 - OS: [ios, Android]

**Additional context**

**Comment by Albert-2** [comment]
hey @Srish-ty 
first of all great idea and very nice app
i would love to contribute 
THANK YOU FOR CONSIDERING..:)

**Comment by Srish-ty** [comment]
@akshitagupta15june , I'd raised pr after working on this issue. But it was closed without telling any reason.

**Comment by akku-07** [comment]
i'd like to work on this issue!
even the 'Fill up the form below and donate your pets.' text isn't visible. I'll fix it like the blog page.

could you add label ssoc please?

**Comment by akshitagupta15june** [comment]
It's not needed
