### ISSUE TITLE
decrease the size of embed video in the readme

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#136]
![image](https://user-images.githubusercontent.com/57909583/193500129-eb8c0146-b51f-44f0-ba62-06bc1b456b11.png)

**Comment by rodolfonei** [comment]
Hi! I would like to work on this issue, could you assign me?

**Comment by akshitagupta15june** [comment]
ok

**Comment by Avi-2003** [comment]
Hi! I would like to work on this issue, could you assign me?
