### ISSUE TITLE
[Bug]: Text color of the contact form heading is incorrect in light-theme 

### ISSUE THREAD

**Issue by hariraghav10** [akshitagupta15june/PetMe#1364]
**Describe the bug**
The text color of the heading of the Contact Form in the Index page is not visible and not matching the overall design in the light mode

**To Reproduce**
1. Go to 'Index' page
2. Click on 'Contact Us' button
3. See color of Heading and Description of 'Contact Form' which is not clearly visible 

**Expected behavior**
It can be White in color as other texts in the Contact Form remain unchanged as white for both light and dark modes

**Screenshots**
![PetMe-ContactForm-Before-LightTheme](https://github.com/akshitagupta15june/PetMe/assets/58381512/e7a1353b-e055-41b7-97f0-c859387491da)

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: 118.0.5993.117 (Official Build) (64-bit)

**Comment by DevanshKyada27** [comment]
Hey @akshitagupta15june can you please assign me with this issue.
Want to work on it.
