### ISSUE TITLE
the text on home page is not clearly visible in mobile view

### ISSUE THREAD

**Issue by Vanshiii203** [akshitagupta15june/PetMe#139]
**Describe the bug**
the text on home page is not clearly visible in mobile view

**Screenshots**
![Screenshot (444)](https://user-images.githubusercontent.com/94471189/193515230-28e8e491-991e-48df-a2b3-96113d11b870.png)

**Comment by akshitagupta15june** [comment]
actually i am creating an issue for it to change the background, currently finding one
