### ISSUE TITLE
Configure main page

### ISSUE THREAD

**Issue by Dynnammo** [akshitagupta15june/PetMe#14]
Currently, when we click on the "Home" button of the website hosted here (https://akshitagupta15june.github.io/PetMe/index.html), we simply get a 401 error. We could either remove the "Home" button or redirect simply to "PetMe" since it's the main purpose of the website.

**Comment by akshitagupta15june** [comment]
cool @Dynnammo would you like to work on this issue?

**Comment by jmdagenais** [comment]
@akshitagupta15june Can I work on this issue? I would like to participate to Hacktoberfest.

**Comment by Dynnammo** [comment]
I could handle it 👍 Assign it to me, I'll take a look tomorrow

**Comment by Dynnammo** [comment]
> @akshitagupta15june Can I work on this issue? I would like to participate to Hacktoberfest.

Go ahead buddy

**Comment by jmdagenais** [comment]
It looks like it have already been fixed.
