### ISSUE TITLE
The contact us button can be changed to an element of navbar and linked to the contact us section of the website 

### ISSUE THREAD

**Issue by Vanshiii203** [akshitagupta15june/PetMe#140]
**Describe the bug**
The contact us button can be changed to an element of navbar and linked to the contact us section of the website 

**Screenshots**

https://user-images.githubusercontent.com/94471189/193516239-b843ee67-276e-4851-889a-bfd060fb7367.mp4

**Comment by akshitagupta15june** [comment]
@Vanshiii203 can u please work on previous issue i will open new issues accordingly so as to give chance to other contributors as well.

**Comment by Vanshiii203** [comment]
> @Vanshiii203 can u please work on previous issue i will open new issues accordingly so as to give chance to other contributors as well.

okay

**Comment by Vanshiii203** [comment]
> @Vanshiii203 can u please work on previous issue i will open new issues accordingly so as to give chance to other contributors as well.

@akshitagupta15june can I create new issues now? I have raised the PRs for my previous issues
