### ISSUE TITLE
Support Us should have a pointer cursor

### ISSUE THREAD

**Issue by Afterdie** [akshitagupta15june/PetMe#1408]
**Describe the bug**
When hovering the support us button on navbar the cursor changes to a line.

**Expected behavior**
Cursor should change to a pointer.

**Screenshots**
![image](https://github.com/akshitagupta15june/PetMe/assets/82810411/cf8de639-4777-437d-b1a8-4eb40c104ad6)

**Comment by Afterdie** [comment]
I'd like to work on this issue.

**Comment by Soham-glitch** [comment]
Hi, I have solved the issue. I am creating a pull request for this. Please review it and if it's correct then kindly merge it. 
Thank you :)

**Comment by Afterdie** [comment]
> Hi, I have solved the issue. I am creating a pull request for this. Please review it and if it's correct then kindly merge it. Thank you :)

Try to abide by the contributor guidelines for the event :)

**Comment by Soham-glitch** [comment]
> > Hi, I have solved the issue. I am creating a pull request for this. Please review it and if it's correct then kindly merge it. Thank you :)
> 
> Try to abide by the contributor guidelines for the event :)

For sure. No one was assigned, so I decided to work on this.

**Comment by akshitagupta15june** [comment]
go for it!

**Comment by Afterdie** [comment]
@akshitagupta15june pls add the codepeak tag to the issue
