### ISSUE TITLE
Implementing accurate validation in the "Name" field of the contact form.

### ISSUE THREAD

**Issue by Ayusht777** [akshitagupta15june/PetMe#1419]
Ensure accurate data entry by implementing robust validation in the "Name" field of the contact form. This enhances user input accuracy and improves the overall reliability of the submitted information.

![image](https://github.com/akshitagupta15june/PetMe/assets/106388215/ff9db2a8-c576-41bd-a9d7-6b882cf4f94a)

**Comment by RitamDas30** [comment]
Hey, I have fixed it, Can I make a pull request?

**Comment by Ayusht777** [comment]
@RitamDas30 Hey, sorry for that, but I am not the main owner of this project.
