### ISSUE TITLE
Dark Mode Button and Layout

### ISSUE THREAD

**Issue by panamyrt** [akshitagupta15june/PetMe#1427]
Hello,
I believe that the dark mode button is a little confusing.
I would like to add a switch to change form light mode to dark mode(and reverse).
Also I believe when you are in dark mode the background of the pages Blogs,Donate,Support us and SOS report  should also change.
Thanks in advance!!

**Comment by Avadhut20** [comment]
Hi @panamyrt. Can you please assign this issue to me under SWOC?

**Comment by rishicds** [comment]
Please assign this issue to me

**Comment by Vipul-Harsh** [comment]
hey i would love to work on this issue so if you can please assign this issue to me

**Comment by akku-07** [comment]
i'd like to fix this again, someone ig tampered with my darktheme mode. i also want to extend this to the support page. 

kindly allot me this, i shall fix this ma'am

**Comment by akku-07** [comment]
this is under SSOC '24
