### ISSUE TITLE
Improving the pet details box element

### ISSUE THREAD

**Issue by si88har1h** [akshitagupta15june/PetMe#143]
**Is your feature request related to a problem? Please describe.**
container for the pet image breaks the background when hovered over. 

**Describe the solution you'd like**
I'd like to add a hidden overflow property to the pet picture container and change the container's border-radius as its too rounded in my opinion.

**Describe alternatives you've considered**
I could also add the overflow of the existing pictures without changing the container's roundness :)

**Comment by akshitagupta15june** [comment]
Go for it

**Comment by Potato-29** [comment]
the pe picture borders look way too rounded and need to be fixed, may I work on this?

**Comment by akshitagupta15june** [comment]
@Potato-29 don't comment on already assigned issues

**Comment by akshitagupta15june** [comment]
are u still working on this issue or I should assign a new person to this issue?

**Comment by si88har1h** [comment]
I am sorry i forgot to mention that i resolved this in my PR. Its already delt with

**Comment by akshitagupta15june** [comment]
ok, thanks
