### ISSUE TITLE
Fix Visual Bug in Blog section

### ISSUE THREAD

**Issue by rishicds** [akshitagupta15june/PetMe#1430]
**Bug Description**
At various resolutions, the read button does not appear properly as shown below.
![image](https://github.com/akshitagupta15june/PetMe/assets/124495375/821423b5-b583-4fe6-8299-338465f0a2da)

**Expected behavior**
Only at certain resolutions it appears correctly like this.
![image](https://github.com/akshitagupta15june/PetMe/assets/124495375/d20830ce-ccb5-4591-9f15-8f8a311c2f72)

Please assign me this issue under SWOC'24 and I'll try my best to fix this issue

**Comment by akshitagupta15june** [comment]
Go for it!
