### ISSUE TITLE
Background change in footer section in SOS report page.

### ISSUE THREAD

**Issue by Avadhut20** [akshitagupta15june/PetMe#1432]
**Describe the bug**
On the SOS REPORT  page, the subscribe form in the footer section has a white background.  
**To Reproduce**
1. Go to the reportstary.html file
2. Click on open with live server
3. Scroll down to the footer section
4. You will see the subscribe form with background

**Expected behavior**
The background of the 
subscribe should be the same as the footer background color.

**Screenshots**
![Screenshot (32)](https://github.com/akshitagupta15june/PetMe/assets/111897568/0bfcd582-c4fd-4de2-9f84-f98f5adb5079)

Can you please assign this issue to me under SWOC?

**Comment by akshitagupta15june** [comment]
go for it

**Comment by PRITISH212121** [comment]
if its open,can i work on it?

**Comment by Avadhut20** [comment]
The issue is fixed. 
![Screenshot (34)](https://github.com/akshitagupta15june/PetMe/assets/111897568/778355c9-3663-45dc-a283-cc17a0c7d908)
