### ISSUE TITLE
Sending the email directly to source email by passing the Sent interface of Formspree  using different provider elastic email

### ISSUE THREAD

**Issue by Navya-1212** [akshitagupta15june/PetMe#1441]
1. When I visit the "Contact Us" or "Adopt Me" page and fill out the form details, upon clicking submit, I am redirected to a "Formspree" provider page that confirms the message has been sent.

2. The redirection to the "Formspree" page seems unnecessary and can be eliminated.

3. An alternative solution is to use the "Elasticemail" provider, which allows direct delivery of messages to our email inbox.

4. By implementing this change, all the form details filled out by users will be sent directly to the provided email address without the intermediate step of redirection to the "Formspree" page.

5. This adjustment streamlines the user experience and ensures that the author receives the submitted details promptly in their email.

**Comment by akshitagupta15june** [comment]
hey its not needed currently
