### ISSUE TITLE
Animations in the website.

### ISSUE THREAD

**Issue by yashi-15** [akshitagupta15june/PetMe#1445]
I would like to introduce subtle animations (smooth floating effects) for the contents of all the pages within the website.
Kindly assign this issue to me under SWOC. Thankyou!

**Comment by Sakshamjain98** [comment]
I would like to introduce subtle animations (smooth floating effects) for the contents of all the pages within the website.
Kindly assign this issue to me under IWOC. Thankyou!

**Comment by vermaanurag1532** [comment]
i can add good animation please assign it to me

**Comment by jojotjo** [comment]
i would like to work on this issue . kindly assign it to me under iwoc2024

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.
