### ISSUE TITLE
Landing Page QOL Improvements

### ISSUE THREAD

**Issue by trs-web** [akshitagupta15june/PetMe#1446]
I have a few quality of life improvements I'd like to work on.

-"Support Us" Dropdown Box Text Unreadable. I want to darken the text color within the dropdown menu.
-Remove hover underline from 'About Us' Header. It looks like a hyperlink when it's hovered, I think it looks better without the hover underline effect.
-Correct grammar in 'About Us' Header. FROM ["Meet our Friends Here"] -> TO ["Meet Our Friends Here"]

I actually added these changes to my branch already, but I didn't realize I had to make an issue first. Sorry, this is my first git contribution. Thank you for reading!

**Comment by akshitagupta15june** [comment]
go for it

**Comment by trs-web** [comment]
Thank you, I will be able to work on this soon. 👍
