### ISSUE TITLE
After selecting 'Pet News,' it disappears from the nav bar, and similarly, 'About Us' disappears after selecting 'Donate.

### ISSUE THREAD

**Issue by thesri** [akshitagupta15june/PetMe#1448]
**Describe the bug**
Pet news isnt appearing in the nav bar and similarly about us is disappearing after selecting donate
**To Reproduce**
1. Go to 'https://akshitagupta15june.github.io/PetMe/index.html
2. Click on 'pet news', 'donate'
3. See the Nav bar'

**Expected behavior**
After selecting 'Pet News,' I expected it to remain visible in the nav bar, providing continued navigation access
After selecting 'donate,' I expected 'about us' to remain visible in the nav bar,because it is the required information,  providing continued navigation access

**Screenshots**
![Screenshot 2024-01-11 103905](https://github.com/akshitagupta15june/PetMe/assets/98333833/49cc2768-53de-4646-92dc-6c6bb7b03fd1)
![Screenshot 2024-01-11 103923](https://github.com/akshitagupta15june/PetMe/assets/98333833/ff16cea3-3ef9-4feb-8b36-52d816cbfa79)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]

**Smartphone (please complete the following information):**
 - Version [Version 120.0.6099.130 ]

**Additional context**

**Comment by thesri** [comment]
i kindly request u to assign me this issue under JWOC 2024

**Comment by akshitagupta15june** [comment]
yes its not needed on those pages
