### ISSUE TITLE
"After clicking 'SOS Report,' the footer help is being dragged all over the page."

### ISSUE THREAD

**Issue by thesri** [akshitagupta15june/PetMe#1449]
**Describe the bug**
After clicking 'SOS Report,' the footer help should remain static but is instead draggable and moves across the page.
**To Reproduce**
1. Go to 'https://akshitagupta15june.github.io/PetMe/index.html'
2. Click on 'SOS REPORT'
3. Scroll down to see 'Help' in the right side always
https://akshitagupta15june.github.io/PetMe/reportstary.html

**Expected behavior**
I expct the Help in the fotter to be static 
**Screenshots**
![Screenshot 2024-01-11 103945](https://github.com/akshitagupta15june/PetMe/assets/98333833/4a0ba0d2-76ab-4b3e-bddd-0c59bfc09ff9)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
 - Version [120.0.6099.130]

**Additional context**
Please kindly provide me this issue, under JWOC 2024

**Comment by akshitagupta15june** [comment]
Go for it!

**Comment by thesri** [comment]
Yes under jwoc 2024

**Comment by Shiv10122003** [comment]
Please assign me this under iwoc

**Comment by shivam101203** [comment]
please assign me this issue under iwoc @akshitagupta15june

**Comment by thesri** [comment]
> Go for it!

should i start working on it?

**Comment by thesri** [comment]
@akshitagupta15june please give the jwoc tag and tell me if i have to start working for it

**Comment by thesri** [comment]
> @akshitagupta15june please give the jwoc tag and tell me if i have to start working for it

@akshitagupta15june please reply
