### ISSUE TITLE
Feature: Improve the styling buttons in the blog.html file 

### ISSUE THREAD

**Issue by Simer13** [akshitagupta15june/PetMe#1453]
**Is your feature request related to a problem? Please describe.**
The https://akshitagupta15june.github.io/PetMe/blog.html  file can have better styling buttons to make them look more enhanced. 

![Screenshot (263)](https://github.com/akshitagupta15june/PetMe/assets/113010708/ed0f3186-108f-4507-befa-e635a7573c5a)

**Additional context**
I would like to be assigned under IWOC'24.

**Comment by DarshSohaliya** [comment]
I would like to work on that issue under JWOC
