### ISSUE TITLE
[Feature] Improve the styling of the 'adopt me' button 

### ISSUE THREAD

**Issue by Simer13** [akshitagupta15june/PetMe#1473]
**Is your feature request related to a problem? Please describe.**
Improve the styling of the 'Adopt Me' button on the about us page.

![Screenshot (280)](https://github.com/akshitagupta15june/PetMe/assets/113010708/6459f0c4-a021-41b7-ae21-69cdc92211fa)

**Describe alternatives you've considered**

**Additional context**

**Comment by RitanshRajput** [comment]
Yo! Simer13
Can you assign me this issue I would love to understand and contribute to it.
