### ISSUE TITLE
The nav bar logo shrinks when using the browser in 1080 width mode

### ISSUE THREAD

**Issue by version0chiro** [akshitagupta15june/PetMe#1481]
**Describe the bug**
When opening the website a couple of time and the select language drop down appearing the image logo shrinks to fit in the image and the font is not dynamic in nature making it a bad UI experience. 

**To Reproduce**
1. Open the browser at a smaller width, i used 1080px 
2. Refresh the page with the select language drop down appearing 
3. The nav bar would look weird in nature and the logo shrinks

**Expected behavior**
Ideally the nav bar should adjust to different monitor sizes automatically and provide text size changes accordingly. 

**Screenshots**
![image](https://github.com/akshitagupta15june/PetMe/assets/56084650/3be927b6-f4c9-4dcf-b2e3-cf75ed8f1f5a)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: brave (chromium) 

**Additional context**
NA

**Comment by upsaurav12** [comment]
hello maintainers can i work on this issu3 ??

**Comment by lovelymahor** [comment]
I would like to work on this project. Please assign it to me!

**Comment by Annu1809** [comment]
@akshitagupta15june can I please work on this issue ?

**Comment by neeraj03788** [comment]
I can debug this bug assign it to me @neeraj03788
