### ISSUE TITLE
Improve the readme

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#15]
add some pictures or basically this issue means is to beautify it

**Comment by krupalitrivedi** [comment]
Hello! I would like to work on this during the hacktoberfest! I have worked on multiple ReadMe files before!

**Comment by akshitagupta15june** [comment]
Assigning u @krupalitrivedi

**Comment by SonakshiChauhan** [comment]
Hey I would like to work on this issue during the hacktober fest.I'm a newbie in opensource but I love beautifying things and adding a creative touch.

**Comment by krupalitrivedi** [comment]
Also the hacktoberfest website shows that the repository is not participating in hacktoberfest. Please see that you add relevant information to the repository for it to be considered

**Comment by akshitagupta15june** [comment]
Where it's was written @krupalitrivedi 
There no issue by hacktoberfest committee that this website is not participating and it has all necessary details

**Comment by krupalitrivedi** [comment]
> Where it's was written @krupalitrivedi 
> There no issue created by hacktoberfest committee in this project that this website is not participating and it has all necessary details 

![Screenshot_20221002-084434__01.jpg](https://user-images.githubusercontent.com/99717469/193436330-98b70ddf-30c7-474b-9fde-51d155bd9cca.jpg)

**Comment by akshitagupta15june** [comment]
I have no idea how is it because in some of the contributors it is showing accepted

**Comment by krupalitrivedi** [comment]
> I have no idea how is it because in some of the contributors it is showing accepted

Maybe when you put the hacktoberfest-accepted label, it will go away - after you merge the PR

**Comment by krupalitrivedi** [comment]
Hi Akshita! I finished working on this, sorry for multiple comments :) I made a mistake while sending a PR and apologizing for the same :) I hope you can take a lot at the changes I have made
