### ISSUE TITLE
Host via Vercel

### ISSUE THREAD

**Issue by akshaaatt** [akshitagupta15june/PetMe#150]
**Is your feature request related to a problem? Please describe.**
We can use vercel to host our NextJs app for free.

**Describe the solution you'd like**
OSS projects are free to be deployed by Vercel. @akshitagupta15june this is specific to you. Please head to https://vercel.com/dashboard , add this project and configure the react branch to be deployed.

**Describe alternatives you've considered**
Best ever solution is to use Vercel for OSS projects.

**Comment by akshitagupta15june** [comment]
ok i have chosen framework preset as next.js but how to configure react branch it is taking main as default
no option to change
![image](https://user-images.githubusercontent.com/57909583/193554370-16340c13-c17d-4a46-aab2-72187e443a0a.png)

**Comment by akshitagupta15june** [comment]
do u need the write access @akshaaatt ?

**Comment by akshitagupta15june** [comment]
because you cana lso help other contributors in this domain

**Comment by akshaaatt** [comment]
Sure @akshitagupta15june , do provide my username the access. (Email: tiwariakshat03@gmail.com)

**Comment by akshitagupta15june** [comment]
Sent you a invite and as you will also review the pr's related to react so please add yourself as a project maintainer in main readme

**Comment by akshaaatt** [comment]
Hey @akshitagupta15june , I am unable to configure the app on Vercel with the invite you have sent. I am not sure whether we need admin access to do so or not.

**Comment by Anuran12** [comment]
@akshitagupta15june 

you must login in Vercel with your github account

then in vercel , in a new project you will see this page ⬇️
![image](https://user-images.githubusercontent.com/104062485/193772486-e0614e93-8a57-4dde-a690-0a47f6973735.png)


then click on the github button. then you will see this ⬇️
![image](https://user-images.githubusercontent.com/104062485/193773117-51eb023b-91a2-453c-b90d-f22ec21375fd.png)

**Comment by Anuran12** [comment]
> @akshitagupta15june
> 
> you must login in Vercel with your github account
> 
> then in vercel , in a new project you will see this page ⬇️ ![image](https://user-images.githubusercontent.com/104062485/193772486-e0614e93-8a57-4dde-a690-0a47f6973735.png)
> 
> then click on the "continue with github" button. then you will see this ⬇️ ![image](https://user-images.githubusercontent.com/104062485/193773117-51eb023b-91a2-453c-b90d-f22ec21375fd.png)
> 
> then click on the "add github account"
> 
> this page will pop up ⬇️ ![image](https://user-images.githubusercontent.com/104062485/193773611-abcac7a8-d5e1-4ced-a3b1-94539f9f44a6.png)
> 
> then select "all repositories" then click Install.

then you will see this⬇️
![image](https://user-images.githubusercontent.com/104062485/193774042-bd5433c5-f859-495d-9ff4-25a4db9b5aec.png)

**Comment by akshitagupta15june** [comment]
this process is done already but connect react branch is not possible

**Comment by Anuran12** [comment]
Hey hey.... @akshitagupta15june I got it

**Comment by Anuran12** [comment]
![image](https://user-images.githubusercontent.com/104062485/193841725-4efd9437-a523-4ecf-adb0-8456d7a2b193.png)
 
at first you have to write "react" under the "BRANCH NAME"


then you have to create a empty commit in your react branch and BOOM💥 !

I tried it⬇️
![image](https://user-images.githubusercontent.com/104062485/193842361-dd8f6cc4-464a-41c5-b32f-3cfb8a5d2726.png)

**Comment by akshitagupta15june** [comment]
![image](https://user-images.githubusercontent.com/57909583/193856213-f68e1a84-57b7-4c38-96cc-c64aa36b1e5b.png)

**Comment by Anuran12** [comment]
Oh wait let me solve this 😐 then i will tell you.

**Comment by Anuran12** [comment]
@akshaaatt  Did you ever try to host this react branch locally ? I am trying but it show me lots of errors

**Comment by Anuran12** [comment]
@akshitagupta15june did you try to host it locally?

**Comment by akshitagupta15june** [comment]
error

**Comment by akshaaatt** [comment]
I've fixed the build and now it is being hosted properly.

**Comment by akshitagupta15june** [comment]
where it is hosted @akshaaatt

**Comment by Anuran12** [comment]
> 

Ohh great. 😃

**Comment by akshaaatt** [comment]
Fir now, it is at https://pet-lkydb9qsj-akshitagupta15june.vercel.app/ @akshitagupta15june  but you can configure it on the vercel dashboard in future in case you have a domain name registered.

**Comment by akshaaatt** [comment]
Also, I am travelling abroad currently, so might be a bit off this week in case people have any questions. The project is currently set for any nextjs beginner and there should be no blockers in general.

**Comment by akshitagupta15june** [comment]
thanks @akshaaatt

**Comment by Anuran12** [comment]
Hey @akshitagupta15june this branch seems like empty now. So i would like to implement things from scratch. I just learnt next js and trying to do contribution in next js as much possible. So it will be great for me if you make me maintainer of the "react" branch.
