### ISSUE TITLE
Improving the UI of Contact Us Form

### ISSUE THREAD

**Issue by MohitNamdev22** [akshitagupta15june/PetMe#152]
**Is your feature request related to a problem? Please describe.**
The present UI of the Contact form looks very normal, the design can be improved.

**Describe the solution you'd like**
I'll make some modifications to the existing tailwind code and try to make a glass morphism effect on Form.

**Describe alternatives you've considered**
And some alignment changes are required.

**Additional context**
Screenshot - 
![image](https://user-images.githubusercontent.com/89779447/193557536-ac9614a9-4c58-4d84-9dae-3a82c8a13d50.png)

**Comment by akshitagupta15june** [comment]
Go for it

**Comment by sumit-022** [comment]
I can do it. Assign to me

**Comment by MohitNamdev22** [comment]
> I can do it. Assign to me

Bro it's already assigned to me and may create something new issue
