### ISSUE TITLE
Improving Navigation Bar

### ISSUE THREAD

**Issue by AkashSharma001** [akshitagupta15june/PetMe#153]
**Is your feature request related to a problem? Please describe.**
As I have seen the website, I have found that all pages have a different navigation bar

**Describe the solution you'd like**
I want to add home page navigation bar to all pages.

**Additional context**

Screenshot

Home Page
![image](https://user-images.githubusercontent.com/97700368/193566030-e185008f-a05a-481d-a07f-d63c4542e3b9.png)

Donate Page
![image](https://user-images.githubusercontent.com/97700368/193566321-90898732-f0d7-4c73-a68a-694dbf04d851.png)

SOS Page
![image](https://user-images.githubusercontent.com/97700368/193566584-3165b021-18e3-402c-9ea6-b445acaa4eea.png)

**Comment by AkashSharma001** [comment]
Please Assign me.

**Comment by akshitagupta15june** [comment]
go for it

**Comment by sumit-022** [comment]
I will use partials for this. So that every header remains the same and attractive. Please assign this to me

**Comment by AkashSharma001** [comment]
Can I make the navigation bar sticky? @akshitagupta15june 

![image](https://user-images.githubusercontent.com/97700368/194147133-f08ecfe8-c806-4446-b44d-2639c84ec5b8.png)

**Comment by akshitagupta15june** [comment]
thanks for issue, but its not required
