### ISSUE TITLE
Form field doesn't show error

### ISSUE THREAD

**Issue by MaragathaMeenakshi** [akshitagupta15june/PetMe#1537]
**Describe the bug**
In donate.html form page, errors are not displaying to user. if the user doesn't statisfy the regExp , it should show what is error to user.

**Expected behavior**
when user doesn't enter, error should be display in textfield and the box outline should be red.

Assign me this issue, I will resolve it.

**Comment by pahuja-sahil** [comment]
Hello @akshitagupta15june , I would like to work on this issue under GSSoC'24. Kindly assign this issue to me.I can fix the problem with forms .
Thank you.

**Comment by tejjhode** [comment]
I am able to make changes please assign me under GSSOC'24

**Comment by MaragathaMeenakshi** [comment]
Could you please assign me for this issue.

**Comment by nhyadav05** [comment]
Could you please assign me for this issue.

**Comment by mtg718** [comment]
Could you please assign me for this issue.
