### ISSUE TITLE
Social media icons are no functional

### ISSUE THREAD

**Issue by TBorundia** [akshitagupta15june/PetMe#1540]
Social media icons of instagram and facebook are not functional. Please assign this issue to me under GSSoC'24, I want to work on it.

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by Dhevamuthu** [comment]
hey, Can you please assign this work under GSSOC 2024 to me and I would definitely do my level best to solve it

**Comment by akshitagupta15june** [comment]
Its not required currently in website. As there is no social media of petme
