### ISSUE TITLE
Add a text box for other stray animals

### ISSUE THREAD

**Issue by Vanshika7902** [akshitagupta15june/PetMe#1541]
**Issue** : In the form present in **SOS report** section , when a user select **other option** in type of stray animal , then there should be **text box for inputting other animal** .

![Screenshot (691)](https://github.com/akshitagupta15june/PetMe/assets/92636041/7f03deb4-774d-414f-9db4-4d1789be995e)

**Solution** : To add a text box for other stray animals .

**Comment by GnanariddhikaRavikumar** [comment]
I can work on this issue and solve this using the Techstacks like React , Mongo DB . kindly assign me this issue and I would really wish to contribute as a GSSoC24 - Contributor

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by akshitagupta15june** [comment]
Go for it

**Comment by GnanariddhikaRavikumar** [comment]
Good Afternoon mam
You have replied to proceed but my name is not mentioned in the
assignees..Can i work on this issue mam?
Thankyou mam

**Comment by GnanariddhikaRavikumar** [comment]
Thank you for your response.I will work on it

**Comment by Vanshika7902** [comment]
Thankyou for assigning me this issue
