### ISSUE TITLE
[FEAT]: Improve the UI for Pet News page

### ISSUE THREAD

**Issue by Ayesha-Siddiqua88** [akshitagupta15june/PetMe#1543]
**Is your feature request related to a problem? Please describe.**
Hovering over news boxes expands them horizontally, causing text to adjust with increased width, detracting from user appeal in the UI.

**Describe the solution you'd like**
I propose implementing a scaling property on hover to maintain text arrangement while enlarging the news boxes, enhancing user experience in the UI

**Additional context**

https://github.com/akshitagupta15june/PetMe/assets/128472306/596398f0-fe66-4f83-868c-ea5a3572dc35

**Comment by Ayesha-Siddiqua88** [comment]
Hello @akshitagupta15june, please assign this issue to me under gssoc

**Comment by akshitagupta15june** [comment]
Its not required currently in website.
