### ISSUE TITLE
[FEAT] :Remove Search Bar from Navbar

### ISSUE THREAD

**Issue by Harshit7492** [akshitagupta15june/PetMe#1544]
# Search Bar In Navbar
  The current navbar design includes a search bar, which is taking up too much space and affecting the overall UI design negatively. To improve the UI, we propose removing the search bar from the navbar and re-positioning it elsewhere in the UI. This will allow other options in the navbar to have more space and enhance the overall user experience.

We suggest placing the search bar below the navbar or in a different section of the application, ensuring it remains easily accessible to users while freeing up space in the navbar.

# To Reproduce
1. Go to 'Navbar component file.'
2. Comment search bar code in the navbar
3. Open the file where you want to place the search bar.
4. Render the search bar component in the desired section.
5. Save the file.
6. Run the application to view the updated layout.5. 
7. See error

# Screenshots
![Screenshot 2024-05-14 223656](https://github.com/akshitagupta15june/PetMe/assets/114082380/786f0752-b1bd-4287-bc97-6dba8819415e)
Add search bar 
![Screenshot 2024-05-14 225412](https://github.com/akshitagupta15june/PetMe/assets/114082380/7c9a28ee-3dc7-46df-9842-6f5a1516587f)

## Code of Conduct and Contributing Guideline  

 I am committed to upholding the standards outlined in the project's Code of Conduct and following the Contributing Guidelines. I understand the importance of maintaining a respectful and inclusive community environment and will ensure that my contributions align with these principles. If there are any specific guidelines or procedures I need to follow, please provide guidance, and I will adhere to them accordingly.

**Comment by saumil-16** [comment]
I would like to work on this project. Please assign it to me.

**Comment by paramveer-bit** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by Gokilp** [comment]
can i working the issue

**Comment by Mahimatestgithub** [comment]
I would like to work on this issue. Please assign me this issue.

**Comment by akshitagupta15june** [comment]
Its not required currently in website.
