### ISSUE TITLE
On the Blog page "Read" button goes out of the margin

### ISSUE THREAD

**Issue by bhumika-1127** [akshitagupta15june/PetMe#1545]
@akshitagupta15june Kindly assign me this issue under GSSOC'24. I would like to help.
![image](https://github.com/akshitagupta15june/PetMe/assets/137604220/f7b69277-1c9a-4d31-906c-d2ddfb923307)

**Comment by GnanariddhikaRavikumar** [comment]
Kindly assign me this issue I can solve this as a Contributor

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by chakrabortydeep** [comment]
![image](https://github.com/akshitagupta15june/PetMe/assets/146315717/1204fbea-3254-40d5-ba5c-e42cbbb3fa26)

I can work on that Read button and can fix the alignment effectively if u assign me the task.

**Comment by Mahimatestgithub** [comment]
I would like to work on this issue. Please assign me this issue.

**Comment by akshitagupta15june** [comment]
Someone is working on this issue
