### ISSUE TITLE
Redesign the website for look enhancement

### ISSUE THREAD

**Issue by satyamdasx** [akshitagupta15june/PetMe#1546]
I want to redesign the website for looking more aesthetic and beautiful.
@akshitagupta15june Please assigned this issue to me under GSSOC'24.
![Screenshot (619)](https://github.com/akshitagupta15june/PetMe/assets/161871534/684465af-58b2-4f5d-81fb-16f9bf186935)

**Comment by akshitagupta15june** [comment]
Its not required currently in website.
