### ISSUE TITLE
Bug :  On blogs page after clicking read button 

### ISSUE THREAD

**Issue by gaddevinay** [akshitagupta15june/PetMe#1548]
**Describe the bug**
On blog page after clicking the read button of card  the next page is not responsive for both mobile and desktop . There is white space right side of the content.

**To Reproduce**
1. Go to https://akshitagupta15june.github.io/PetMe/blog.html
2. Click on Read button 
3. See error  
![Screenshot_20240515-193247](https://github.com/akshitagupta15june/PetMe/assets/128584849/19db3b17-39d5-4aff-985d-02438a34521d)
![Screenshot_20240515-193732](https://github.com/akshitagupta15june/PetMe/assets/128584849/d35069bc-7045-44b5-a942-333082eb3a0c)

**Comment by akshitagupta15june** [comment]
Go for it!
