### ISSUE TITLE
Styling: Become Volunteer button color should be changed to other color for better UI

### ISSUE THREAD

**Issue by Scrapper700** [akshitagupta15june/PetMe#1553]
![Screenshot (213)](https://github.com/akshitagupta15june/PetMe/assets/113296663/9739ff0a-9113-49d1-bc29-fa341b8fa8ff)
![Uploading Screenshot (214).png…]()

**Comment by Scrapper700** [comment]
@akshitagupta15june can you assign me this task

**Comment by akshitagupta15june** [comment]
Its not required currently in website.
