### ISSUE TITLE
Enhancing the Header and About Us Section

### ISSUE THREAD

**Issue by SAURABH-CHAMOLI** [akshitagupta15june/PetMe#1554]
**Describe the bug**
In header part the options are not arranged in single line which makes it look weird.
And Also,
In About Us Section ,the space/padding is more.

**To Reproduce**
1. Go to 'Home page and About Us'

**Expected behavior**
The options in header section should be re-arranged in single line.
And 
In About Us Section ,the padding should be minimized.

**Screenshots**
![Screenshot 2024-05-16 130541](https://github.com/akshitagupta15june/PetMe/assets/124969978/9686be3a-e54c-4e1c-95cd-3726df38171b)
![Screenshot 2024-05-16 130629](https://github.com/akshitagupta15june/PetMe/assets/124969978/b8785be6-b257-4e50-a99b-b9f968e28053)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 22

**Comment by SAURABH-CHAMOLI** [comment]
Can you assign the labels to it 
And also please assign this issue to me .

**Comment by akshitagupta15june** [comment]
Its not required currently in website.
