### ISSUE TITLE
Docs: update the issue template 

### ISSUE THREAD

**Issue by officeneerajsaini** [akshitagupta15june/PetMe#1555]
**Describe the bug**
We should update the issue template. We can add more new things like emoji, tags for issues, and titles for every issue, like Docs:, Feat:, Bug:. This way, we can understand the purpose of the issue raised by just seeing the title. 

**Expected behavior**
We can see all issues with a good title so we can easily understand the purpose for which the issue was created.

**Screenshots**

![Screenshot from 2024-05-16 14-31-10](https://github.com/akshitagupta15june/PetMe/assets/118799941/09bcec9c-9c2b-4905-a9db-667f0b4da0fc)

![Screenshot from 2024-05-16 14-34-37](https://github.com/akshitagupta15june/PetMe/assets/118799941/c0e60744-261a-4fbd-ab1c-0feb700ef2c6)

**Desktop (please complete the following information):**
 - OS: Ubuntu [Linux}
 - Browser chrome
 - Version : 20.04.6 LTS

**Comment by akshitagupta15june** [comment]
Go for it!

**Comment by officeneerajsaini** [comment]
Okay

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!
