### ISSUE TITLE
Feacture: You should add telegram ,youtube and whatsapp icon also in footer with other social media.

### ISSUE THREAD

**Issue by theashikagupta** [akshitagupta15june/PetMe#1557]
**Is your feature request related to a problem? Please describe.**
Social media icons are less you should add more .

**Describe the solution you'd like**
You should add telegram ,youtube channel and whatsapp icon also in footer with other social media.
So that they can follow your website everywhere and reach out to you from anywhere.
![Screenshot 2024-05-16 184816](https://github.com/akshitagupta15june/PetMe/assets/136061047/782c3af4-6704-4d45-ac10-3c2734cd8875)

**Comment by theashikagupta** [comment]
Hello Ma'am , If you think this issue is valid then please assign me this issue for GSSoC'24.
Thank you

**Comment by Rishitatripathi** [comment]
Please assign me this issue under gssoc'24

**Comment by akshitagupta15june** [comment]
Its not required currently in website.

**Comment by theashikagupta** [comment]
Okay ma'am
