### ISSUE TITLE
no icon in titlebar in many pages!!

### ISSUE THREAD

**Issue by SrijaVuppala295** [akshitagupta15june/PetMe#1561]
**Is your feature request related to a problem? Please describe.**
There is no icon in the titlebar for many web pages.
**Describe the solution you'd like**
I want to add an icon to all the pages in which the icon is missing.

**Additional context**
![Screenshot 2024-05-16 231023](https://github.com/akshitagupta15june/PetMe/assets/140592148/64c14e52-c323-4b5d-b522-a6ee3984c0b0)
![Screenshot 2024-05-16 232358](https://github.com/akshitagupta15june/PetMe/assets/140592148/3798e351-948d-467e-bf32-3602e0e08ff1)
![Screenshot 2024-05-16 232417](https://github.com/akshitagupta15june/PetMe/assets/140592148/c2d6bac7-7d84-465c-abd1-967c358bc6ca)

**Comment by akshitagupta15june** [comment]
Go for it!

**Comment by Ved8290** [comment]
Can this issue be assigned to me for gssoc '24
