### ISSUE TITLE
On the blog section, "Read" button goes out of the block

### ISSUE THREAD

**Issue by johnkim0306** [akshitagupta15june/PetMe#1562]
![image](https://github.com/akshitagupta15june/PetMe/assets/26418357/99e1fccc-12d1-42de-ac69-5a11f7c1a51f)
Is this a result of a recent design change? if not, I would like to help.

**Comment by akshitagupta15june** [comment]
Go for it!

**Comment by Divi-1026** [comment]
can you plzz assigned this issue to me i resolved in very few amount of time

**Comment by ShreyaKhare1** [comment]
Can you assign me this problem under gssoc'24

**Comment by johnkim0306** [comment]
> Can you assign me this problem under gssoc'24

The problem is solved thanks

**Comment by johnkim0306** [comment]
> can you plzz assigned this issue to me i resolved in very few amount of time

The problem is solved thanks
