### ISSUE TITLE
[BUG] Fix Hover effect on new pet page 

### ISSUE THREAD

**Issue by ayushnandi** [akshitagupta15june/PetMe#1563]
### Issue
The animation on hover for the pet info cards on the new pet page is poorly displayed and needs improvement.

### Problem Description
Currently, when hovering over the pet info cards on the new pet page, the animation is not visually appealing and may even disrupt the overall layout and user experience. This detracts from the professionalism and usability of the page.
### without hover:
![image](https://github.com/akshitagupta15june/PetMe/assets/110190468/a747bf05-7968-4355-ab4a-302226a336fa)
### on hover:
![image](https://github.com/akshitagupta15june/PetMe/assets/110190468/550e389d-8a35-47a8-ad55-c88ccce8dd92)

### Proposed Solution
To address this issue, I suggest fixing the layout using flexbox and setting min and max widths for different content within the pet info cards. By using flexbox, we can ensure consistent alignment and spacing, while setting min and max widths will prevent content from overflowing or becoming too cramped, thereby improving the overall display and user experience.

### Expected Outcome
Implementing the proposed solution will result in a more visually appealing and user-friendly display of animations on hover for the pet info cards. The cards will maintain a consistent layout and spacing, ensuring that the animation enhances rather than detracts from the user experience.

### Additional Details
- I will ensure that the proposed solution is compatible with different screen sizes and devices.
- This enhancement may require adjustments to the existing CSS code for the pet info cards.
- I am open to feedback and collaboration with other contributors to fine-tune the implementation and ensure its effectiveness.

Kindly assign this issue to me under GSSoC 24.

**Comment by TitikshyaChanda** [comment]
Kindly assign this issue to me under GSSoC 24.

**Comment by akshitagupta15june** [comment]
go for it!

**Comment by mtg718** [comment]
Kindly assign this issue to me under GSSoC 24.

**Comment by visioncoding021** [comment]
@akshitagupta15june   i would like to work on this issue ,please assign me this.

**Comment by Pranali3103** [comment]
Hello @akshitagupta15june Please assign  me this issue.

**Comment by harshcodesit** [comment]
hey @akshitagupta15june 

i can add immersive hover effect effect on the cards
please assign me the issue

**Comment by puneet426** [comment]
hey @akshitagupta15june i can add hover effect on nav bar which is not fix upto now i done it please assign it to me under
 GSSoC'24

https://github.com/akshitagupta15june/PetMe/assets/168094736/7f49d4a4-1d22-4664-84fc-707785908fae

**Comment by RedWing0021** [comment]
@akshitagupta15june Please assign this to me..!!
