### ISSUE TITLE
Request to Add FAQ Section in Navbar

### ISSUE THREAD

**Issue by SrijaVuppala295** [akshitagupta15june/PetMe#1564]
**Is your feature request related to a problem? Please describe.**
There's a need to address frequently asked questions (FAQ) but no dedicated section in the navbar, leading to difficulty in accessing important information efficiently.

**Describe the solution you'd like**
Integrate a FAQ section into the navigation bar to provide easy access to commonly asked questions and relevant information.

**Describe alternatives you've considered**
Utilizing a separate page or link for FAQs, or embedding FAQ content within existing pages.

**Additional context**
Improving user experience by facilitating quick access to frequently sought information.

![Screenshot 2024-05-16 233903](https://github.com/akshitagupta15june/PetMe/assets/140592148/baa1dd9e-269e-4194-a065-478cc607bd82)

**Comment by akshitagupta15june** [comment]
Its not required currently in website.
