### ISSUE TITLE
different navbar views in different pages 

### ISSUE THREAD

**Issue by AdhithiManjunath** [akshitagupta15june/PetMe#1568]
hello @akshitagupta15june , i noticed there was no alignment of navbar as such and was able to see different navbars for different pages , which would create difficulty for the user to navigate to pages as such .

i hv tried solving this , please do allocate this issue as i can contribute to it and work on it .  

**issues**
![image](https://github.com/akshitagupta15june/PetMe/assets/130202961/ed0f5442-8257-4810-9870-c5d19dfd347a)
main page view 

![image](https://github.com/akshitagupta15june/PetMe/assets/130202961/28bc1446-b43b-4328-90c3-982a81ebd122)
blog page view 

![image](https://github.com/akshitagupta15june/PetMe/assets/130202961/8b0ae7f1-5001-412e-872f-64f8299a03ca)
donate page view 

i personally feel that there should be uniformity  in nav bars in different pages too

**Comment by akshitagupta15june** [comment]
hey! yes it  is changes accordingly so no changes needed here.
