### ISSUE TITLE
When we click on adopt me , the information of the dog being adopted doesnt comes up.

### ISSUE THREAD

**Issue by sumeet05xcaliber** [akshitagupta15june/PetMe#1571]
![image](https://github.com/akshitagupta15june/PetMe/assets/90512820/e267cf46-201e-473c-854f-75b0b4cdfc59)
when we click on adopt me for a dog 
![image](https://github.com/akshitagupta15june/PetMe/assets/90512820/39fbe35a-679d-41df-b480-5e68db35de51)
the information of the dog being adopted doesnt comes in front, i will make sure that the information of the dog is presented while filling up the form with proper visualizations.
Can you assign this task to me under GSSOC24

**Comment by akshitagupta15june** [comment]
as its a dummy record so there is no info of pets
