### ISSUE TITLE
Logo enhancement

### ISSUE THREAD

**Issue by Akshitha-reddy-13** [akshitagupta15june/PetMe#1581]
Logo and tagline are not correctly placed and, hence, can enhance the logo to make it attractive for users and supporters.

![image](https://github.com/akshitagupta15june/PetMe/assets/122172211/d18504ac-273c-4c62-affc-b02d92fc84fa)
Can you assign it to me? @akshitagupta15june 

Full name: Akshitha Reddy
GitHub profile link: [Akshitha-reddy-13](https://github.com/Akshitha-reddy-13)
Email ID: akshithajagan13@gmail.com
Approach for this project: I will use my creative skills in designing and editing knowledge to make this cause carrying project more attractive and promotable. Please assign this work to me.
What is your participant role?: GSSoC-2024 contributor

Can you add the label for GSSoC, please?
Thanks.

**Comment by akshitagupta15june** [comment]
hey currently its ok, not planning to change it
