### ISSUE TITLE
Placement of Help Button in sos report 

### ISSUE THREAD

**Issue by kesharwaniyanshi** [akshitagupta15june/PetMe#1582]
![image](https://github.com/akshitagupta15june/PetMe/assets/123561974/cfd78407-b3fd-43de-ade1-5761546a3142)
This placement of Help button looks quite abrupt .It can be relocated to a better place.

**Comment by akshitagupta15june** [comment]
go for it!

**Comment by ujjwalkumar-64** [comment]
please assign this task to me under gssoc'24

**Comment by as112223** [comment]
I have recently completed my javascript , html and css course i can help you with this issue . could you assign me with this task?
I'm under GSSOC'24
