### ISSUE TITLE
Adding contact details in footer

### ISSUE THREAD

**Issue by Shreesanyog** [akshitagupta15june/PetMe#1583]
Currently the website doesn't have contact details at the footer.

![image](https://github.com/akshitagupta15june/PetMe/assets/166977453/d6342f6b-36d9-4ed0-b1bd-0c73f6fb6871)

**Solution**-

I will add a contact section in the footer that includes email, phone number and address. This enhancement will make it easier for users to find relevant contact information on the website home page itself.

**Comment by akshitagupta15june** [comment]
hey its not required currently!
