### ISSUE TITLE
responsiveness in blog section

### ISSUE THREAD

**Issue by Devansh1508** [akshitagupta15june/PetMe#1584]
**Issue**
The blog section does not have responsiveness 

**Problem Description**

Currently whenever the width is less than 1280px. Whole text of blog collapses to left side. 

**when width is less than 1280px**

<img width="987" alt="respo - 1" src="https://github.com/akshitagupta15june/PetMe/assets/160311808/5c493435-62b3-473c-a176-f8ad77d9c6d3">

**proposed solution**

To address this issue, I suggest fixing the layout using flexbox and setting min and max widths for blog card. By using flexbox, we can ensure consistent alignment and spacing, while setting min and max widths will prevent content from overflowing or becoming too cramped, thereby improving the overall display and user experience.

**Expected Outcome**

Implementing the proposed solution will result in a more readable and a user-friendly blog section.

**Additional Details**

- I will ensure that the proposed solution is compatible with different screen sizes and devices.

- This enhancement may require adjustments to the existing CSS code.

Kindly assign this issue to me under GSSoC 24.

**Comment by AyushSingh916** [comment]
I can do that, assign this task to me.

**Comment by akshitagupta15june** [comment]
Go for it!
