### ISSUE TITLE
Adding data.json for pet field

### ISSUE THREAD

**Issue by MaragathaMeenakshi** [akshitagupta15june/PetMe#1585]
**Is your feature request related to a problem? Please describe.**
we can add data.json file and make the code clear and short for pet field.

**Describe the solution you'd like**
By adding data.json file for pet field make easier to add and remove data for pet. 
Simplifying code and reducing the number of lines can make it easier to maintain and extend the codebase for pet field.

Assign me the issue. I like to work on it.

**Comment by akshitagupta15june** [comment]
hey as its a dummy data so it will not be required

**Comment by MaragathaMeenakshi** [comment]
In future, if we need to add data dynamically from server/ any source . duplicating code will be difficult. Kindly look at the below code snippet
![Screenshot 2024-05-19 225835](https://github.com/akshitagupta15june/PetMe/assets/113226919/c980ffba-eb12-449b-bbd5-271fce7b0525)
![Screenshot 2024-05-19 225746](https://github.com/akshitagupta15june/PetMe/assets/113226919/2b05fd85-9776-48fc-a90c-35d0ee46e6b6)
![Screenshot 2024-05-19 225856](https://github.com/akshitagupta15june/PetMe/assets/113226919/3b3deef2-ef88-4182-837c-2d7f874b60b7)
.
