### ISSUE TITLE
the ui of the header named "meet our friends here" is not consistent with the rest of the ui 

### ISSUE THREAD

**Issue by CodeSage4** [akshitagupta15june/PetMe#1586]
**Describe the bug**
improving the aesthetics of the webpage

**To Reproduce**
1. Go to home page
2. Scroll down to 'meet our friends here'

**Screenshots**
![petme1](https://github.com/akshitagupta15june/PetMe/assets/106674125/b54bec2c-3f64-4f89-a0bb-0a2b69222bd5)

**Desktop (please complete the following information):**
 - Windows 11
 - brave, bing

**Comment by akshitagupta15june** [comment]
hey its not currently required to make changes in this part, also please don't create pr without issues are not assigned

**Comment by CodeSage4** [comment]
okay got it !! thanks for informing me
