### ISSUE TITLE
Enhance UI of the "Become Volunteer" button

### ISSUE THREAD

**Issue by Devaki01** [akshitagupta15june/PetMe#1588]
### Description of the issue
The volunteer here button can be made more catchy which further catalyze in attracting more volunteers.

<img width="367" alt="image" src="https://github.com/akshitagupta15june/PetMe/assets/147143243/1ea7527a-d59c-43c6-86c8-2399652c5fa2">

### About me 
I am a tech-enthusiast and an aspiring developer, passionate about Front-end technologies such as React.

Please assign me this issue under GGSoC'24. Looking forward to contribute an learn in the process.

**Comment by akshitagupta15june** [comment]
hey its not currently required
