### ISSUE TITLE
Adding the website logo to readme.md

### ISSUE THREAD

**Issue by Vanshiii203** [akshitagupta15june/PetMe#159]
**Is your feature request related to a problem? Please describe.**
I would like to Add the website logo to readme

**Comment by RRK-CODER** [comment]
I would like to add fabicons to your website, kindly give approval to proceed

**Comment by akshitagupta15june** [comment]
Website logo is already there

**Comment by RRK-CODER** [comment]
but it is not visible

**Comment by RRK-CODER** [comment]
The logo of the website is not visible , I would like to add fabicons to your website, kindly give approval to proceed.
