### ISSUE TITLE
Implement Hover effect on cards in meet our friends section.

### ISSUE THREAD

**Issue by Vaidehi-Sarag** [akshitagupta15june/PetMe#1593]
Problem-Currently there is no hover effect on card

I would like to add a hover effect on card to prove use visual aesthetics ans enhance use engagement.

Something like this-
![image](https://github.com/akshitagupta15june/PetMe/assets/152738458/86ee1d96-905d-4ad6-a322-16a2bf308920)

I had add hover effects like:
Card Expansion: Cards pop out slightly on hover.
Name Underline: Name or title becomes highlighted with underline.
Shadow Effect: Subtle shadow added to hovered card.

Kindly Assign this issue to me under GSSoC24

**Comment by akshitagupta15june** [comment]
hey its not required currently!
