### ISSUE TITLE
Subscribe the news letter is not working

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [akshitagupta15june/PetMe#1599]
**Describe the bug**
Subscribe the news letter is not working

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by meenakshiiyer2531** [comment]
Hey @akshitagupta15june
Can this issue be assigned to me for gssoc '24
Regards,
V Meenakshi Iyer
