### ISSUE TITLE
Bug alert: SOS Button UI Gone

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#160]

**Comment by AkashSharma001** [comment]
Assign me. I will fix this issue. 
@akshitagupta15june

**Comment by akshitagupta15june** [comment]
U are already assigned an issue so let other contribute

**Comment by lakshyaagr1105** [comment]
Hi @akshitagupta15june, I am Lakshya and i would like to work on this issue. So, please assign me this issue.

**Comment by akshitagupta15june** [comment]
ok @lakshyaagr1105

**Comment by kartikmandhan** [comment]
@akshitagupta15june

**Comment by akshitagupta15june** [comment]
as there is no response from @lakshyaagr1105 so i am merging the pr of @kartikmandhan
