### ISSUE TITLE
Adding Search bar based on animal type and filter option based on gender  

### ISSUE THREAD

**Issue by MitashaJ** [akshitagupta15june/PetMe#1602]
Is your feature request related to a problem? Please describe.
Yes, the feature request is related to the problem of difficulty in finding preferred pets on the PetMe website. Currently, users have to scroll through a long list of pets, which can be time-consuming and frustrating, especially if they have specific preferences. For example, a user looking for a female cat or a male dog has no direct way to filter these options quickly.

Describe the solution you'd like
I want to add a search bar and filter options at the top of the MeetPets section. This feature will allow users to:

**Search by Animal Type**: Users can enter the type of pet they are looking for (e.g., dog, cat, rabbit) in the search bar.
**Filter by Gender**: Users can select filters to view only male or female pets.

**Describe alternatives you've considered**
**Category Tab**s: Creating separate tabs for different types of animals (e.g., dogs, cats, others) to allow users to navigate directly to the category they are interested in. 

![image](https://github.com/akshitagupta15june/PetMe/assets/128090631/b2cb6321-661a-4862-bccb-912e62697567)

**Comment by MitashaJ** [comment]
I would to like to work on this issue. @akshitagupta15june can u assign it to me ?

**Comment by akshitagupta15june** [comment]
Hey it's not currently needed as it's a dummy data
