### ISSUE TITLE
Border radius should be less for better Looks

### ISSUE THREAD

**Issue by toodiv** [akshitagupta15june/PetMe#1604]
![Screenshot 2024-05-21 004855](https://github.com/akshitagupta15june/PetMe/assets/160960398/3f729d86-6e9d-4f47-bafd-49c0c86fcc2b)
**Describe the bug**
Border radius should be less for good looking UI 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Tanishka023** [comment]
Hey!! I am really excited to contribute to this project!! Please assign this to me @akshitagupta15june
