### ISSUE TITLE
Create an Impact section in the Home page 

### ISSUE THREAD

**Issue by prathimacode-hub** [akshitagupta15june/PetMe#162]
**Is your feature request related to a problem? Please describe.**
I would like to create an impact section to the home page

**Describe the solution you'd like**
Adding an impact section will benefit users in knowing of how this app made difference to pet's life just by taking a step and therefore inspires them to initiate the goodness.

Can you assign this issue? @akshitagupta15june

**Comment by akshitagupta15june** [comment]
hey @prathimacode-hub it is not needed for website
