### ISSUE TITLE
Light and Dark mode not working on blogs page

### ISSUE THREAD

**Issue by Dhruv-Gaba** [akshitagupta15june/PetMe#1636]
**Describe the bug**
The night and dark mode feature is not working on the blogs page. the background remains bright even on switching to dark mode. The issue is shown in the video below.

**To Reproduce**
1. Go to the Blogs web page
2. Click on the change mode option.
3. The mode doesn't change.

**Expected behavior**
On clicking the dark mode option, the site should change its appearance to a darker shade according to the website's color schema.

**Screenshots**

https://github.com/akshitagupta15june/PetMe/assets/141745373/a5795589-8349-4f89-9ce7-10f1a6c48b6b

**Desktop (please complete the following information):**
 - OS: windows
 - Browser - chrome
 - Version windows 10

I would like to solve the above mentioned issue, Please assign this issue to me under GSSOC'24.

**Comment by RohitGo8789** [comment]
Can you assign me this issue, I think I can solve this issue!

**Comment by akshitagupta15june** [comment]
go for it

**Comment by GeeekySouro003** [comment]
can u please assign me this

**Comment by akku-07** [comment]
i'd like to work on this!
