### ISSUE TITLE
Overflowing content in blogs page.

### ISSUE THREAD

**Issue by Dhruv-Gaba** [akshitagupta15june/PetMe#1637]
**Describe the bug**
The buttons are overflowing from the cards container and it looks clumsy. The cards need a consistent layout and adequate padding to ensure that the buttons fit properly within the container, creating a more organized and visually appealing design.

**To Reproduce**
1. Go to blogs section
2. The cards do not have proper padding and layout and the content is flowing out.

**Expected behavior**
Giving proper layout and padding to all the cards to make the webpage more attractive.

**Screenshots**
![image](https://github.com/akshitagupta15june/PetMe/assets/141745373/7faca45c-b154-4c0e-bcfe-8716c0cfce77)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version windows 10

I would like to work on the above mentioned issue. Please assign this issue to me under GSSOC'24.

**Comment by riya-rjha** [comment]
I'd like to work on this under Gssoc. Kindly assign me this issue.

**Comment by Pappula-Aishwarya** [comment]
@akshitagupta15june I would like to work on the above mentioned issue. Please assign this issue to me under GSSOC'24.

**Comment by akshitagupta15june** [comment]
its corrected now
