### ISSUE TITLE
Improper position of button in SOS report section.

### ISSUE THREAD

**Issue by Dhruv-Gaba** [akshitagupta15june/PetMe#1638]
**Describe the bug**
The HELP button in the SOS Section randomly beside the form. the button should be placed at the end of the form, this would look more presentable.

**To Reproduce**
1. Go to SOS Section
2. The help button is placed poorly.

**Expected behavior**
The button should be positioned at the end of the form.

**Screenshots**
![image](https://github.com/akshitagupta15june/PetMe/assets/141745373/873c1665-056e-4730-8b41-9c427bdf5340)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version Windows 10

I would like to work on the above stated issue. Please assign this issue to me under GSSOC'24.

**Comment by Pappula-Aishwarya** [comment]
I would like to work on the above issue. Please assign this issue to me under GSSOC'24.

**Comment by akshitagupta15june** [comment]
go for it
