### ISSUE TITLE
Improper visibility of text.

### ISSUE THREAD

**Issue by Dhruv-Gaba** [akshitagupta15june/PetMe#1639]
**Describe the bug**
The text in the Support us dropdown is too light and not properly visible.

**To Reproduce**
1. Go to Blogs section.
2. Click on support us dropdown 
3. the text is not visible.

**Expected behavior**
The text should be clearly visible and dark.

**Screenshots**
![image](https://github.com/akshitagupta15june/PetMe/assets/141745373/fb5f5051-f480-44ea-9fc1-1f0a7202ba78)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version Windows 10

I would like to work on the above issue. Please assign this issue to me under GSSOC'24.

**Comment by Pappula-Aishwarya** [comment]
I would like to work on the above issue. Please assign this issue to me under GSSOC'24.

**Comment by akshitagupta15june** [comment]
its properly visible currently
