### ISSUE TITLE
User able to submit the form without entering any info.

### ISSUE THREAD

**Issue by aanchal-fatwani** [akshitagupta15june/PetMe#164]
**Describe the bug**
On Contact Us Form, the user is able to Submit the form without entering any info. This then redirects to Formspee and there the user is shown an error.

**To Reproduce**
1. Go to ['...'](https://akshitagupta15june.github.io/PetMe/index.html#contact)
2. Click on 'Contact Us'
3. See the error

**Expected behavior**
The validations should happen before the user is allowed to Submit the form.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
NA

**Comment by aanchal-fatwani** [comment]
@akshitagupta15june  I would like to work on this issue and add a fix for the same. Please assign the issue to me so I can proceed with the same.
Thanks

**Comment by akshitagupta15june** [comment]
ok go for it
