### ISSUE TITLE
Feat: Live Location Sharing feature for the SOS form

### ISSUE THREAD

**Issue by mayanksinghshekhawat** [akshitagupta15june/PetMe#1640]
**Is your feature request related to a problem? Please describe.**
While submitting the **SOS** form the user(if he/she is present on the site of the injured/stray animal) should be able to submit the exact **latitude and longitude** of the location.

**Describe the solution you'd like**
Automatically fetch the user's current latitude and longitude using the browser's Geolocation API when they click the "Locate Me" button.
Update the address field in the form with this data, ensuring that the exact location is captured accurately and effortlessly.

**Describe alternatives you've considered**
Manual Entry: Allowing users to manually enter the address, which can lead to inaccuracies and delays.
Map Pin Drop: Users could drop a pin on an embedded map to select the location. This requires more user interaction and may be less precise if not handled carefully.

**Additional context**
![Screenshot 2024-05-24 223330](https://github.com/akshitagupta15june/PetMe/assets/127962246/acc156bf-6916-4c7b-b1fd-2e0a3615d664)
![Screenshot 2024-05-24 222905](https://github.com/akshitagupta15june/PetMe/assets/127962246/0c9cd158-5d9e-4bbd-bc09-f616a410bcb6)

**If you find this a good feature to be implemented please assign it to me @akshitagupta15june ma'am.**

**Comment by akshitagupta15june** [comment]
Go for it!
