### ISSUE TITLE
Improving styles

### ISSUE THREAD

**Issue by sumitkr2000** [akshitagupta15june/PetMe#166]
Hey @akshitagupta15june I want to add hover effect on buttons and improve styling of the page. Can you please assign me this issue?

After adding hovering effect buttons will animate.

Thank you!

**Comment by akshitagupta15june** [comment]
ok @sumitkr2000

**Comment by sumitkr2000** [comment]
@akshitagupta15june  Can I add animations to the website or you want to keep it simple?

**Comment by akshitagupta15june** [comment]
@Susmita-Dey do u want some animations for website?

**Comment by Potato-29** [comment]
Can you assign this to me? I can make the buttons better

**Comment by Susmita-Dey** [comment]
@sumitkr2000 Go ahead

**Comment by sumitkr2000** [comment]
If u allow me to add animations on cards of pets I can do that.

**Comment by sumitkr2000** [comment]
If u add that feature then only i will do it. Because it takes a lot of time . After wasting so much time if its not merged it hurts :)

**Comment by Susmita-Dey** [comment]
@akshitagupta15june What to do?

**Comment by akshitagupta15june** [comment]
Better is to leave it now @Susmita-Dey because we are already working on other issues if needed we will assign him in future

**Comment by Potato-29** [comment]
It doesn't take time at all, I can do the animations, I don't care if you merge it or not

**Comment by sumitkr2000** [comment]
@akshitagupta15june okk just ping me when you require it. Thank you!

**Comment by sumitkr2000** [comment]
Why did u closed this?

**Comment by akshitagupta15june** [comment]
will create a new issue when needed
