### ISSUE TITLE
Changing background of Dogs section with some attractive pattern

### ISSUE THREAD

**Issue by MohitNamdev22** [akshitagupta15june/PetMe#167]
**Is your feature request related to a problem? Please describe.**
Currently, there is only yellow color in the background, If we use something pattern-like pattern it will look more attractive.
**Describe the solution you'd like**
I'll change the background color with some good pattern

**Additional context**
Current Background - 
![image](https://user-images.githubusercontent.com/89779447/193896844-6daa9df5-9ac2-420d-abf4-c8659251c00e.png)

**Comment by akshitagupta15june** [comment]
ok go for it @MohitNamdev22

**Comment by Potato-29** [comment]
Can I work on this?

**Comment by akshitagupta15june** [comment]
Issue completed
