### ISSUE TITLE
Navbar not displaying properly in all pages

### ISSUE THREAD

**Issue by paulkrishanu4** [akshitagupta15june/PetMe#1698]
navbar is not displaying in all pages, in some pages it is acting as mobile view navbar

https://github.com/akshitagupta15june/PetMe/assets/169196836/d8d2afd2-6ebf-4ee6-a904-eba68ddcae87

**Comment by md-wasim-123** [comment]
i would like to fixed this issue

**Comment by akshitagupta15june** [comment]
someone is working on this
