### ISSUE TITLE
💡[FEATURE]: Increase the font weight of the footer section to medium

### ISSUE THREAD

**Issue by ArionDutta33** [akshitagupta15june/PetMe#1700]
##Proposing to change the font weight of the footer texts (Adopt a pet, Subscribe to our newsletter, Follow us on ) for more appeal

**BEFORE**
 
![Footer-fnweight](https://github.com/akshitagupta15june/PetMe/assets/146577817/db30f98e-65b0-424c-aef5-63e84770e2d0)

 **AFTER**
![fnweigh-inct](https://github.com/akshitagupta15june/PetMe/assets/146577817/ffcc5788-700e-4799-a281-d1b5ac0c40fe)

**Comment by md-wasim-123** [comment]
i would like to add this font weight
