### ISSUE TITLE
🪲BUG: Theme mode gets turned off on refeshing a page

### ISSUE THREAD

**Issue by MastanSayyad** [akshitagupta15june/PetMe#1702]
**Describe the bug**
Hey @akshitagupta15june 
The Theme mode function gets turned off on refreshing a page or if we try to navigate to other pages . (You may check that)

To fix this, we can store the theme state in the browser's local storage so that it persists across page reloads.

I believe by storing the theme state in the browser's local storage, we ensure that:
- The theme persists across page reloads and navigations
- Even when the user navigates away from the page, the theme persist
- This provides a seamless experience for users who prefer a specific theme setting. (for example, social media and our IDEs stay on the theme mode that we have selected)

I hope I was able to explain the issue and the expected solution.
If so, Could you please assign this issue to me under GSSoC 24?

**Comment by captainsahil001** [comment]
can i work on this issue. pls assign me

**Comment by captainsahil001** [comment]
am ssoc contributor
