### ISSUE TITLE
💡[FEATURE]: Animated cursor 

### ISSUE THREAD

**Issue by happyrao78** [akshitagupta15june/PetMe#1703]
Adding the animated cursor to the  website to make it more appealing and user interactive.

**Comment by kushagra-singhh** [comment]
I would like to work on this feature. Please assign it to me under SSOC'24.

**Comment by happyrao78** [comment]
@akshitagupta15june Kindly review my issue and assign it to me.

**Comment by akshitagupta15june** [comment]
not required
