### ISSUE TITLE
🪲[Bug]: Non-Uniform Image Holders

### ISSUE THREAD

**Issue by captainsahil001** [akshitagupta15june/PetMe#1705]
**Describe the bug**
The bug is that images in the blog section are not coming uniform and and resized on certain items.

**To Reproduce**
1. Go to 'Blogs'
2. Click on 'Any image'
3. Check they are not uniform

**Expected behavior**
All images should be linear and uniform and multi responsive

Screenshot:-
![Screenshot 2024-06-02 130659](https://github.com/akshitagupta15june/PetMe/assets/116186123/eb03e58a-9b63-48f6-b964-5f788e421e3f)

**Comment by captainsahil001** [comment]
Pls Assign me this issue

**Comment by captainsahil001** [comment]
Am ssoc ,3 contributor

**Comment by akshitagupta15june** [comment]
Go for it!
