### ISSUE TITLE
Implementation Multilingual support

### ISSUE THREAD

**Issue by Anjankumarkamalapur** [akshitagupta15june/PetMe#1711]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Anjankumarkamalapur** [comment]
@akshitagupta15june my plan is to provide various languages like user can access our website in their preferred language.
Example,
![Uploading Screenshot (991).png…]()

**Comment by Anjankumarkamalapur** [comment]
![Screenshot (992)](https://github.com/akshitagupta15june/PetMe/assets/139578011/d8b563be-fa19-4c74-a9ec-8726ee72fb23)

**Comment by akshitagupta15june** [comment]
its already present
