### ISSUE TITLE
💡[FEATURE]: Meet previous volunteers

### ISSUE THREAD

**Issue by Chelseasingla1** [akshitagupta15june/PetMe#1712]
**Is your feature request related to a problem? Please describe.**
I would like to add a feature so it shows the previous volunteers.

**Describe the solution you'd like**
It would show their experience and thoughts on it.

**Describe alternatives you've considered**

**Additional context**
Please assign me this issue under SSOC'24.

**Comment by riyasaxena32** [comment]
I am interested in resolving issue for GSSoC '24 and believe my skills in make me a good fit. Please assign it to me.

**Comment by akshitagupta15june** [comment]
not required
