### ISSUE TITLE
🪲[Bug]: Content is not good , language is not attractable.

### ISSUE THREAD

**Issue by piyushsahujtp** [akshitagupta15june/PetMe#1716]
**Describe the bug**
description about the dog is not looks caring behaviour , texts have no emotions.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kushagra-singhh** [comment]
I would like to work on this issue under ssoc'24. Please assign it to me!
