### ISSUE TITLE
💡[FEATURE]: Improving the Navigation bar Usability 

### ISSUE THREAD

**Issue by NaveenKS1824** [akshitagupta15june/PetMe#1719]
Description:
I would like to propose an improvement to the navigation bar to enhance user experience. Currently, when navigating through the website, it can be unclear which section the user is currently viewing. This can lead to confusion and a less intuitive browsing experience.

Proposed Enhancement:
To address this, I suggest implementing a feature that changes the color of the selected navigation bar tag. When a user selects a tag in the navigation bar, the color should change to indicate that it is active. This visual cue will help users easily identify their current position within the website.

Benefits:
Improved Usability: Users can quickly and easily see which section they are currently viewing.
Enhanced User Experience: A more intuitive and user-friendly navigation experience.
Visual Feedback: Provides clear visual feedback to the user, making the navigation process smoother.
Example:
When the "Home" tag is selected, it changes from its default color to a highlighted color (e.g., from grey to blue).

I am willing to contribute to this enhancement and look forward to your feedback.

**Comment by NaveenKS1824** [comment]
Hii! @akshitagupta15june ,I am an SSOC contributor ,Can you please assign this for me

**Comment by akshitagupta15june** [comment]
someone is working on it
