### ISSUE TITLE
🪲[Bug]: 2 forms in the same page in adopt.html

### ISSUE THREAD

**Issue by bitan2504** [akshitagupta15june/PetMe#1720]
There are 2 submission forms on the same page for adopt.html

We can not submit one form without completing the other, even though both have the same content. Also due to this, the pet's picture container is stretched making it look awful.

![1](https://github.com/akshitagupta15june/PetMe/assets/144161003/c99018a3-8dbe-4784-9341-2b17dbbf749b)
![2](https://github.com/akshitagupta15june/PetMe/assets/144161003/6679b86e-3a1d-4012-868e-b45ba569e8da)
![3](https://github.com/akshitagupta15june/PetMe/assets/144161003/9080bc1c-7483-4269-a19a-4365010aa5aa)

Please assign this issue to me, so that I can do the needful.

**Comment by akshitagupta15june** [comment]
someone is working on it
