### ISSUE TITLE
🪲[Bug]: [SSOC'24] Enhance Readability: Improve Font Color Contrast on "Contact Us" Page in Light Mode

### ISSUE THREAD

**Issue by sahithi-kanjarla** [akshitagupta15june/PetMe#1723]
Description:
In light mode, the "Contact Us" page has white font color on a light grey background. This makes the text difficult to read and not visually appealing. The font color needs to be changed to ensure better visibility and improve user experience.

Steps to Reproduce:

Switch the site to light mode.
Navigate to the "Contact Us" page.
Observe the font color and background color contrast.
Expected Behavior:
The text should be clearly visible and easy to read against the background.

Proposed Solution:
Change the font color to a darker shade.

![Screenshot 2024-06-03 200553](https://github.com/akshitagupta15june/PetMe/assets/139060052/ab62d700-f249-4b6f-92fd-bef94b8802b3)

I would like to contribute to fixing this issue as part of SSOC'24.

**Comment by akshitagupta15june** [comment]
Go for it!
