### ISSUE TITLE
💡[FEATURE]: Enhancing Cards and background of "PET Adoption Cards section"

### ISSUE THREAD

**Issue by jeevan10017** [akshitagupta15june/PetMe#1724]
As an **SSOC contributor** 
![Screenshot 2024-06-04 005133](https://github.com/akshitagupta15june/PetMe/assets/132948936/0e409ea1-8b49-409c-b6f6-eb6b936f00c0)
, I’m excited to contribute to our project by enhancing the pet adoption cards. After reviewing the current design, I’ve prepared a detailed plan for improvements:

**Pet Adoption Cards:**

1. Clearly display pet names, ages, breeds, and locations.
2. Improve the visibility of the “Adopt Me” button.
3. Apply consistent typography.

**Background Design:**

- Update the body background with a visually appealing image or color gradient.
- Add a subtle overlay to the card background for better readability.
- Consider color fades between different sections.

**Expected Outcome:** A visually appealing and cohesive design that encourages pet adoption and provides essential information to potential adopters.

I kindly request your approval to work on this task. If assigned, I’ll diligently implement the proposed changes and ensure thorough testing across different devices and screen sizes.

**Comment by akshitagupta15june** [comment]
Go for it!
