### ISSUE TITLE
Resize the heading images of the site

### ISSUE THREAD

**Issue by uepzues** [akshitagupta15june/PetMe#1725]
**Is your feature request related to a problem? Please describe.**
The heading images are very slow to load, specially on slower networks
![](https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExZW42NHZoazlvbXFsZDF4d3QyamplMGVibms3ZmVnZXFuNmJqcGVucyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/zpJyqoJ7u0jOHLWwam/giphy.gif)

The gif is just a short clip, the images load for more than 10 seconds.

**Describe the solution you'd like**
i suggest resizing the heading images to make it load faster and update the related code

**Additional context**
If possible I'd like to be assigned to this

**Comment by puneet426** [comment]
hey @akshitagupta15june please assign this project to me under GSSoC'24

**Comment by akshitagupta15june** [comment]
Go for it!
