### ISSUE TITLE
💡[FEATURE]: improving email section

### ISSUE THREAD

**Issue by Rishikesh63** [akshitagupta15june/PetMe#1726]
![Screenshot 2024-06-04 103433](https://github.com/akshitagupta15june/PetMe/assets/130288820/3a03cc48-8823-4322-88fe-82c0203872be)

border of email section not visible , it shows after hovering.

by changing  css i can improve this

**Comment by puneet426** [comment]
hello @akshitagupta15june please assign this project to me under GSSoC'24

**Comment by akshitagupta15june** [comment]
Go for it!
