### ISSUE TITLE
🪲[Bug]: Adopt me form rendered twice

### ISSUE THREAD

**Issue by rashmi3149** [akshitagupta15june/PetMe#1727]
**Describe the bug**
Adopt your favourite pet form is rendered twice.

**To Reproduce**
1. Go to 'Home'
2. Click on 'Adopt me' for any pet

**Expected behavior**
The form should ask for details only once.

**Screenshots**

![Screenshot 2024-06-04 111556](https://github.com/akshitagupta15june/PetMe/assets/113359160/0e97b361-ec33-4e5f-844b-669376708233)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [chrome]

**Comment by rashmi3149** [comment]
please assign this issue to me under SSOC'24

**Comment by akshitagupta15june** [comment]
Go for it!
