### ISSUE TITLE
📝[Docs]:new nav bar 

### ISSUE THREAD

**Issue by puneet426** [akshitagupta15june/PetMe#1732]
Issue
The navbar style is looking old i made a new design of it
OLD ONE:
![Screenshot 2024-06-04 141022](https://github.com/akshitagupta15june/PetMe/assets/168094736/db126761-44fb-46c4-9a45-63441a1f8b5e)
NEW ONE:

https://github.com/akshitagupta15june/PetMe/assets/168094736/de5798b1-6d35-401f-a1fc-97739b788754

hey @akshitagupta15june please assign this issue to me under GSSoC'2024

**Comment by akshitagupta15june** [comment]
Go for it!

**Comment by puneet426** [comment]
@akshitagupta15june please check it and merge
