### ISSUE TITLE
🪲[Blog Content]: Content not assigned properly inside Blog read 

### ISSUE THREAD

**Issue by mohitmuktikant** [akshitagupta15june/PetMe#1733]
![image](https://github.com/akshitagupta15june/PetMe/assets/101824646/70c100b8-e0ed-4835-b929-eb17eb4c37c3)

**Steps to check the behavior:**
https://akshitagupta15june.github.io/PetMe/blogs/dan.html

**Here's How it can be solved:**
![image](https://github.com/akshitagupta15june/PetMe/assets/101824646/fe4695cb-5ee3-46b4-b5c0-23a27904d343)

**Comment by mohitmuktikant** [comment]
Hey @akshitagupta15june please assign me to solve this

**Comment by akshitagupta15june** [comment]
Go for it!

**Comment by mohitmuktikant** [comment]
Please add level GSSoC
