### ISSUE TITLE
There is color of ( optional ) text isn't visible report page

### ISSUE THREAD

**Issue by MohitNamdev22** [akshitagupta15june/PetMe#177]
**Describe the bug**
On the report stray animal page, on the address option the "( optional )" is not visible, the color of the text can be changed for visibility. So can I work on this issue under Hacktoberfest 2022?

**Screenshots**
![image](https://user-images.githubusercontent.com/89779447/194042537-50ed8cf5-7ddb-4cab-ab6c-b42fa42103bf.png)

**Comment by akshitagupta15june** [comment]
@Susmita-Dey is it required?

**Comment by Susmita-Dey** [comment]
@akshitagupta15june What can be done here is either remove the `optional` word or highlight it using some colors.

**Comment by Priyadarshani7** [comment]
Hey! Can I work on this issue?

**Comment by MohitNamdev22** [comment]
> Hey! Can I work on this issue?

It's been already done and changes are made on website

**Comment by Susmita-Dey** [comment]
@Priyadarshani7 Check other issues as this has already been assigned

**Comment by MohitNamdev22** [comment]
> @Priyadarshani7 Check other issues as this has already been assigned

You can closed this as completed
