### ISSUE TITLE
Add cursor-pointer in "Support-Us" bottom

### ISSUE THREAD

**Issue by HimangshuRanjan** [akshitagupta15june/PetMe#1798]
**Is your feature request related to a problem? Please describe.**
![WhatsApp Image 2024-06-07 at 23 42 21_d4b54614](https://github.com/akshitagupta15june/PetMe/assets/146883557/6858e823-3908-435f-85bf-bd46a943cb07)

**Describe the solution you'd like**
![WhatsApp Image 2024-06-07 at 23 41 25_3d29ca75](https://github.com/akshitagupta15june/PetMe/assets/146883557/fe7ec572-fd38-43c7-9b1e-849136d456d8)

**Describe alternatives you've considered**

**Additional context**

**Comment by AnClicks** [comment]
@HimangshuRanjan Kindly assign me this issue.

**Comment by Gagan2601** [comment]
I can fix this issue. Please assign this to me and I can improve the navbar if you want.

**Comment by akshitagupta15june** [comment]
Go for it

**Comment by HimangshuRanjan** [comment]
I created the pull request and pushed it. Please check and merge it.

Thank you

**Comment by HimangshuRanjan** [comment]
And please add the GSSOC'24 label.

**Comment by HimangshuRanjan** [comment]
please add GSSoC label
