### ISSUE TITLE
Improve the header navbar

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#18]
Add a better design to header navbar

![image](https://user-images.githubusercontent.com/57909583/191895404-9e84254b-b1bd-4613-9355-3134e3380831.png)

**Comment by Jokerko93** [comment]
Hello. I would like to help you with this. :) May I?

**Comment by NisooJadhav** [comment]
Hi Akshita!, I think I can do this.
Can I work on this?
you can check my projects on [projects](https://nisootech.vercel.app/#projects)

**Comment by akshitagupta15june** [comment]
assigning you @Jokerko93
