### ISSUE TITLE
Improvement in ISSUE TEMPLATES

### ISSUE THREAD

**Issue by warmachine028** [akshitagupta15june/PetMe#180]
## Description
- Currently the issue templates in PetMe are very basic
- Every thing is pre filled making it confusing to identify the labels
- Users can't distinguish where to write their feature requests or bug description clearly.
- There is no place dedicated for adding screenshots.
- I want to improve the issue templates of BUG and FEATURE_REQUEST by adding proper descriptions, textAreas, description and tags, placeholders

## Screenshots 
- Feature Request Template 
![IMG_20221005_180920](https://user-images.githubusercontent.com/75939390/194062359-da22b523-10dc-4987-8a20-d13a4d279570.jpg)

- Bug Bounty Template
![IMG_20221005_182047](https://user-images.githubusercontent.com/75939390/194064630-ff30e8da-c27f-406e-98c5-c4418df1b03c.jpg)

**Comment by akshitagupta15june** [comment]
It's not needed
Thanks for your issue
