### ISSUE TITLE
🪲[Bug]:  The navbar keeps moving when we hover over the navbar elements.

### ISSUE THREAD

**Issue by amaira-aggarwal** [akshitagupta15june/PetMe#1819]
**Describe the bug**
The navbar keeps moving when we hover over the navbar elements.

**To Reproduce**
1. Go to 'https://akshitagupta15june.github.io/PetMe/blog.html'
2. Hover over home/contact us etc in the Navbar.
3. See error

**Expected behavior**
The navbar elements should not change in size and disturb the whole navbar. It should change colour and animate when hovering. This will help us to make the navbar look stable.

**Screenshots**
![image](https://github.com/akshitagupta15june/PetMe/assets/145780031/4d75e6e0-79ea-46f5-a37e-cefdb192a88f)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser -chrome
 
_**I am working under GSSoC'24 . Please assign me this issue .**_

**Comment by like-rounak** [comment]
Hmm it seems to be glitching
