### ISSUE TITLE
Day mode texts colors are different and some text partially visible

### ISSUE THREAD

**Issue by AkashSharma001** [akshitagupta15june/PetMe#184]
**Describe the bug**
In Day mode, many texts have different colors and some of the text is partially visible.

**To Reproduce**
Click on the 'toggle button(Day Mode)'
![image](https://user-images.githubusercontent.com/97700368/194100925-be7b5b93-cf16-4e28-9081-f54657e977c7.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/97700368/194101572-84cd818a-686c-4576-a545-8f22c61a90ce.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/97700368/194101846-eaea80c7-c746-4356-98c2-fed0d1827d4e.png)

**Comment by AkashSharma001** [comment]
Please Assign me @akshitagupta15june

**Comment by marsian83** [comment]
Please assign this task to me under hactoberfest, it'd be my first proper contribution

**Comment by akshitagupta15june** [comment]
This is not needed
