### ISSUE TITLE
🪲[Bug]: Re-designing "Adopt Your Favourite Pet" form

### ISSUE THREAD

**Issue by Ridhima10** [akshitagupta15june/PetMe#1840]
**Describe the bug**
i would like to re-design "Adopt Your Favorite Pet"  form

![Screenshot 2024-06-13 175421](https://github.com/akshitagupta15june/PetMe/assets/85826117/2b170c7e-3a38-43ac-ac2f-fe1746bbc888)
-The image is stretched out
-The label in form are not in an organized manner
-Heading color does not fir with the UI of website

**Comment by guneetdewangan9** [comment]
I would like to work on this issue. Please assign me this issue under GSSoC'24 to contribute to this project and to re-design form
