### ISSUE TITLE
🪲[Bug]: Contact Section color is too dark due to that contact us is not visible

### ISSUE THREAD

**Issue by sakeel-103** [akshitagupta15june/PetMe#1846]
**Describe the bug**
🪲[Bug]: Contact Section color is too dark due to that contact us is not visible.
I'll fix all these issues and also add some new features in contact section if you assign me this 

SS-
![p2](https://github.com/akshitagupta15june/PetMe/assets/136844498/3fbbe8ed-59dc-46e3-a1a3-0fe25d457e80)

@akshitagupta15june 
can you please assign me this under gssoc'24.

**Comment by mehrun171** [comment]
i want to work on this issue...please assign me @akshitagupta15june  @sakeel-103

**Comment by akshitagupta15june** [comment]
Go for it!

**Comment by RishiSharmapro** [comment]
Hello @akshitagupta15june 
I would like to work on this issue, please assign it to me :)

**Comment by sakeel-103** [comment]
@akshitagupta15june 
ma'am you didn't give a level.
