### ISSUE TITLE
Navbar Items hover color is not contrasting and theme changing button does not feel interactive

### ISSUE THREAD

**Issue by marsian83** [akshitagupta15june/PetMe#185]
**Describe the bug**
Hovering on the navbar items assigns them a color which makes them not clearly visible.
Also the icon for switching themes does not react to mouse hover by changing color like other navbar items.
The theme switching button must also change to a pointer cursor when hovered.
same goes for the text besides the logo, that text doesn't react to hovers either.

**To Reproduce**
1. Go to the website
2. Hover on navbar items
3. Hover on theme changing button
4. Hover on the text besides the logo 

**Expected behavior**
The navbar items must have a contrasting color and the text besides the logo must react to hovers also the theme changing button should react to hovers by changing colors like other navbar items. The theme changing color also keeps the cursor static instead of making it a pointer.

**Desktop :**
 - OS: Windows 11
 - Browser Brave
 - Version 1.14.105

I believe I could fix this, please assign this task to me under hacktoberfest 2022

**Comment by marsian83** [comment]
Can I be assigned this issue under hacktoberfest 2022 @akshitagupta15june

**Comment by akshitagupta15june** [comment]
ok go for it

**Comment by marsian83** [comment]
#188 this fixes it? if I reckon correctly

**Comment by hamzailyas237** [comment]
Please assigned it to me.
