### ISSUE TITLE
Add a footer to the website

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#19]
design a cool footer for this website
add the logo of website in the footer 
as well as add 
icons of the fb, insta
as pages are not created yet but the icons will be accepted an later on the links can be added

**Comment by abitsalihu** [comment]
Hey @akshitagupta15june, I would like to help with this issue. :)

**Comment by akshitagupta15june** [comment]
ok assigning u @abitsalihu
