### ISSUE TITLE
💡[FEATURE]: Making a Login and sign up page

### ISSUE THREAD

**Issue by AkshatPandey-2004** [akshitagupta15june/PetMe#1915]

**Comment by Khushi-83** [comment]
**Hey Sir!**
I am highly interested to contribute to this project. I have already came through all the abouts and guidelines of contribution in this project. I would be really thankful if you assign me this task. I would follow the  below steps to overcome with solution:
1) Set Up the HTML Structure
2) Style the Page with CSS
3) Add Functionality with JavaScript

Waiting for your response.

**Comment by Khushi-83** [comment]
And Sir please add labels of gssoc. 
Thankyou!
