### ISSUE TITLE
Visiblity of Contact Us Form's labels and button

### ISSUE THREAD

**Issue by kartikmandhan** [akshitagupta15june/PetMe#192]
**Is your feature request related to a problem? Please describe.**
The labels of contact us form are barely visible and makes it difficult for the user to read them

**Describe the solution you'd like**
Changing the shades of existing color to make it clearly visible and compatible with the existing UI.

**Describe alternatives you've considered**
Before: 
![Screenshot 2022-10-06 at 3 52 35 PM](https://user-images.githubusercontent.com/56060122/194289501-55f52289-aabe-41b1-a8bc-a65f3918f2c2.png)
After: 
![Screenshot 2022-10-06 at 3 52 58 PM](https://user-images.githubusercontent.com/56060122/194289567-ea35a1af-8e52-4c8b-a9ca-0daae706730e.png)

**Comment by kartikmandhan** [comment]
I have the changes ready, if it is approved I can create the pull request immediately. Thanks

**Comment by akshitagupta15june** [comment]
go for it!

**Comment by kartikmandhan** [comment]
Created a PR for it @akshitagupta15june
