### ISSUE TITLE
🪲[Bug]:  Footer section text is not visible

### ISSUE THREAD

**Issue by TBorundia** [akshitagupta15june/PetMe#1935]
**Describe the bug**
Footer section text is not visible properly due its font color and size

**Expected behavior**
Text must in visible in footer section of every page.

**Screenshots**

![image](https://github.com/user-attachments/assets/390983ac-fa9c-4c91-bc20-a358a00894a9)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by saurabhbakolia** [comment]
Hey @akshitagupta15june
Please assign this issue to me.
