### ISSUE TITLE
💡[FEATURE]: Add a scroll down progress bar 

### ISSUE THREAD

**Issue by chaanakyaaM** [akshitagupta15june/PetMe#1936]
**Description**: I would like to add a website progress indicator bar
**Uses**: it helps users to show how far the website has been scrolled.
**Benefits**: improves the overall website's UI and make it look professional.

**Looks like this**:
![Screenshot (345)](https://github.com/user-attachments/assets/05e6c532-3db3-40cc-8748-5f2717aaf094)

**Comment by anshulagr5** [comment]
@akshitagupta15june I would like to work on this issue. Kindly assign it to me.
