### ISSUE TITLE
Card does not looks good on medium screen 

### ISSUE THREAD

**Issue by mohdhaider07** [akshitagupta15june/PetMe#196]
**Card issue**
Card is not responsive on medium screen
 

**Expected behavior**
I want to make it responsive on medium screen

**Screenshots**
![image](https://user-images.githubusercontent.com/86488954/194381200-f654baca-8afc-46bf-846c-b49e126ede6a.png)

** I want to work on this  **
can you please assign this to me

**Comment by akshitagupta15june** [comment]
Go for it

**Comment by mohdhaider07** [comment]
@akshitagupta15june I am added PR can you please take a Look
