### ISSUE TITLE
🪲[Bug]:  Appearance issue with text 'Subscribe to our newsletter' in small screen devices

### ISSUE THREAD

**Issue by rajmanna-dev** [akshitagupta15june/PetMe#1964]
**Describe the bug**
Text appearence issue on footer subscribe newslatter text but only for small screen devices.

**To Reproduce**
1. Go to 'https://akshitagupta15june.github.io/PetMe/index.html'
2. Scroll down to 'Footer'

**Expected behavior**
Appearance of footer text should be same for all screen size devices.

**Screenshots**
Large screen
![Screenshot 2024-10-03 223613](https://github.com/user-attachments/assets/b142b6c2-c957-4717-a482-1ff6eba206b5)

Small screen (having issue)
![Screenshot 2024-10-03 223421](https://github.com/user-attachments/assets/05d197a6-65d6-4cbb-84c8-8c94b11d074f)

**Desktop:**
 - OS: Win11
 - Browser: Chrome

**Smartphone:**
 - Device: Samsung S21
 - OS: Android
 - Browser: Chrome

**Additional context**
I want to work on this issue please asign me on it.

**Comment by Pro-Developer01** [comment]
hi @akshitagupta15june I would like to pick this up, If you approve this bug
