### ISSUE TITLE
Better readability for text used over image 

### ISSUE THREAD

**Issue by gopukr** [akshitagupta15june/PetMe#200]
**Describe the bug**
Having difficulty reading white text used over the background image on mobile screens and medium screens.  

**Expected behavior**
Bring more readability to the text used over background image on smaller screens

**Screenshots**

![white-text-issue](https://user-images.githubusercontent.com/89155028/194402317-f28772ae-d6f6-4169-97fb-86953d9a9c3e.jpg)

**Additional context**
I'd could make the background image a bit darker using linear gradient for only mobile and medium screens as the readability is fine for larger screens. Doing so will imporve the readbility drasticaly.

**I would like to work on this**

**Comment by 19sriram** [comment]
@akshitagupta15june hey new contributor here. Can I make it responsive enough for all screens with screen contrast ?

**Comment by akshitagupta15june** [comment]
thanks for this issue i am planning to change background image
