### ISSUE TITLE
Contact Us Button UI 

### ISSUE THREAD

**Issue by mohdhaider07** [akshitagupta15june/PetMe#201]
**Describe the bug**
Contact us Button UI does Not working well on Small Screen

**Screenshots**
**Before**
![image](https://user-images.githubusercontent.com/86488954/194422045-af0d35a0-eb41-422a-86a0-2ed7117c5c69.png)
**After**
![image](https://user-images.githubusercontent.com/86488954/194422262-9d5bda3a-84c6-4b0a-a189-bf54580fdcfd.png)

I am ready to make a PR, assign this to me ASAP

**Comment by akshitagupta15june** [comment]
not needed currently
thaks
