### ISSUE TITLE
header is not uniform in all pages

### ISSUE THREAD

**Issue by 19sriram** [akshitagupta15june/PetMe#202]
**Describe the bug**
The header elements such as logo and theme icon is not uniform across all pages

**To Reproduce**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5829079/194431287-3f3e8840-74c6-47a1-b86e-173ac478b51b.png">
 In about page
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/5829079/194431340-ec6b580a-ef83-42d8-9bd2-c98febbf5877.png">
 In homepage

**Expected behavior**
Header has to be unique across all pages

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
 I really liked this idea and would like to start contributing. Really appreciate if you assign it to me

**Comment by akshitagupta15june** [comment]
go for it @19sriram
