### ISSUE TITLE
Change the background image to a brighter one for better text readability

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#203]
keep the theme in mind

Add your background images suggestions in the comment

**Comment by ShreyasSahoo** [comment]
Hi Akshita, I would like to contribute to this issue.

**Comment by TilteD24** [comment]
Please assign me this task

**Comment by akshitagupta15june** [comment]
ad image in comment which u are going to add

**Comment by TilteD24** [comment]
I would like to add this 
[image](https://images.unsplash.com/photo-1444212477490-ca407925329e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1228&q=80)

**Comment by akshitagupta15june** [comment]
@Susmita-Dey check images from contributors whichever suits the website because currently texts are not visible due to initial image

**Comment by Susmita-Dey** [comment]
@akshitagupta15june @TilteD24 `image1` looks good than `image2`

**Comment by akshitagupta15june** [comment]
ok @TilteD24 add the image 1
