### ISSUE TITLE
Footer is half-visible for tablet screensize

### ISSUE THREAD

**Issue by kartikmandhan** [akshitagupta15june/PetMe#205]
**Describe the bug**
Footer of the webpage gets cut out due to smaller screensizes, ("Adopt A pet"section is not visible on smaller screensize)
Before: 

![Screenshot 2022-10-07 at 8 47 41 AM](https://user-images.githubusercontent.com/56060122/194460713-1d6f572c-fee4-49cc-a5a3-2fab5baeb49a.png)

After: 
![Screenshot 2022-10-07 at 8 48 05 AM](https://user-images.githubusercontent.com/56060122/194460736-1a20ca1c-3621-49c8-96b0-fbd417f32996.png)

**Comment by kartikmandhan** [comment]
Also for tablet screensize, this issue exists.

**Comment by akshitagupta15june** [comment]
it looks ok!
if any changes required will create an issue
Thanks
