### ISSUE TITLE
Navigation to mentioned pages from About Us section

### ISSUE THREAD

**Issue by gopukr** [akshitagupta15june/PetMe#207]
**Is your feature request related to a problem? Please describe.**
In the About Us section, there are highlighted words that mention the features of the PetMe platform. If these texts could navigate the user to their respective page or section it would ensure better and faster navigation.

**Describe the solution you'd like**
When the mouse hovers over the highlighted words in the About Us section it should provide a hover action and clicking on it the user should be redirected to desired feature pages or section.

**Additional context**

Screenshot of the above mention section:
![about section](https://user-images.githubusercontent.com/89155028/194462983-db7e9be7-b1cf-4ec9-b43b-f0287cd484b0.png)

If this feels like a good feature, I would like to contriubte to the project by implementing it.

**Comment by akshitagupta15june** [comment]
go for it @gopukr
