### ISSUE TITLE
footer is not responsive

### ISSUE THREAD

**Issue by mohdhaider07** [akshitagupta15june/PetMe#208]
**Describe the bug**
when you Move from larger screen to smaller footer remains the same. it is not responsive

**Expected behavior**
I want to make it responsive 

**Screenshots**
On large screen

![image](https://user-images.githubusercontent.com/86488954/194468931-d820a1e6-12ba-401c-a9e6-408d977b9bbb.png)

**when you move from larger to smaller **
**Medium screen**

![image](https://user-images.githubusercontent.com/86488954/194469067-435d9f06-44fe-45ad-b7e4-9ad9130ce9d0.png)
**And ON  small screen**
![image](https://user-images.githubusercontent.com/86488954/194469195-47e66ab7-8a91-4653-8f0e-e0e81ab7927b.png)

**Can you please assign this to me**

**Comment by 19sriram** [comment]
i am planning to fix with the header :)
