### ISSUE TITLE
Contact Us button is misaligned on smaller screensize

### ISSUE THREAD

**Issue by kartikmandhan** [akshitagupta15june/PetMe#209]
**Describe the bug**
Contact Us button is misaligned on smaller screensize, and even goes out of viewport due to class "mx-72" to the parent div
Before: 
![Screenshot 2022-10-07 at 11 32 46 AM](https://user-images.githubusercontent.com/56060122/194478655-8e425d8f-a87b-4264-8c28-e2e821357c2e.png)
After: 
![Screenshot 2022-10-07 at 11 35 00 AM](https://user-images.githubusercontent.com/56060122/194478863-0455f03c-c93b-4587-a678-d8fdb9023e0f.png)

**Comment by akshitagupta15june** [comment]
This issue is not needed currently

**Comment by kartikmandhan** [comment]
@akshitagupta15june won't this affect the user experience of users using the website on mobile?
