### ISSUE TITLE
Add a cool navbar to SOS reports section

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#21]
![image](https://user-images.githubusercontent.com/57909583/191896334-4ecd6698-f3ae-487f-92f6-5d307fb4e8a3.png)

**Comment by sambhavgupta0705** [comment]
Hi,can you elaborate what things you want in the navbar

**Comment by akshitagupta15june** [comment]
@sambhavgupta0705 as u can see initially it doesn't have any navbar so it will be better if you add a navbar containing "home","contact us", "donate" you can take the links from home page index.html

**Comment by akshitagupta15june** [comment]
would you like to work on this?

**Comment by sambhavgupta0705** [comment]
Yes I would like to work on it
Please assign it to me

**Comment by akshitagupta15june** [comment]
ok

**Comment by akshitagupta15june** [comment]
As you are already assigned one issue so i am removing you from this one to give other contributors this issue

**Comment by akshitagupta15june** [comment]
ok fine @sambhavgupta0705 i am assigning you this @Satyakoidala would u like to work on issue https://github.com/akshitagupta15june/PetMe/issues/22

**Comment by sambhavgupta0705** [comment]
Thanks!!

**Comment by sambhavgupta0705** [comment]
Hi Akshita I have made the changes in navbar ,please let me know if you want any other change
