### ISSUE TITLE
Donate Animals form Contact Number field

### ISSUE THREAD

**Issue by kartikmandhan** [akshitagupta15june/PetMe#212]
**Describe the bug**
Currently, user can type alphanumeric characters in Contact Number field and still the form is submitted

![Screenshot 2022-10-07 at 11 59 33 AM](https://user-images.githubusercontent.com/56060122/194482251-393acedc-aeb3-428a-b9a3-877246d2ef95.png)

changing the input type to "Number" will make user only type '+' and Numeric characters only:
![Screenshot 2022-10-07 at 12 00 31 PM](https://user-images.githubusercontent.com/56060122/194482391-f8c7772e-6829-4625-99ac-13133d461be7.png)

**Comment by kartikmandhan** [comment]
@akshitagupta15june is this needed?

**Comment by akshitagupta15june** [comment]
go for it

**Comment by kartikmandhan** [comment]
@akshitagupta15june are you sure that "contact us" form's button alignment is not needed? (talking about the previous issue I created, #209 )

**Comment by 19sriram** [comment]
@kartikmandhan But, changing type to "number" is not the solution. if you change it, it can go to negative too ! This is not the solution

![image](https://user-images.githubusercontent.com/5829079/194487451-ac0fabb0-5a4a-4240-b7ec-7e4efb753725.png)

**Comment by kartikmandhan** [comment]
@19sriram yes, but atleast now it doesn't accept alphabets, let me see if we get a better solution using regex
