### ISSUE TITLE
Buttons can be darker for more visibility - Cosmetic change

### ISSUE THREAD

**Issue by 19sriram** [akshitagupta15june/PetMe#213]
**Describe the bug**
Selecting lighter theme, "Adopt me" buttons were still white and not visible

**Expected behavior**
Buttons & icons has to change with the theme or darker for more visibility

**Screenshots**
![image](https://user-images.githubusercontent.com/5829079/194482704-d9a3601b-7565-41ee-b1c3-1540847d9853.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser : Chrome

**Additional context**
I would like to fix up similar issues within theme switch for the application. Appreciate if I can pick it up

**Comment by akshitagupta15june** [comment]
go for it

**Comment by Priyadarshani7** [comment]
Is anyone working on this issue..if not please assign it to me

**Comment by 19sriram** [comment]
PR raised already.
