### ISSUE TITLE
"Adopt Me" not visible clearly on Mobile Screens

### ISSUE THREAD

**Issue by ayushanand16** [akshitagupta15june/PetMe#216]
**Describe the bug**
The "Adopt Me" banner in the home page is not visible clearly on mobile screens

**To Reproduce**
1. Go to https://akshitagupta15june.github.io/PetMe/ on Mobile
2. See error

**Expected behavior**
The "About Me" font should be clearly visible as it emphasizes the mission of the site. 

**Screenshots**
Following screenshot is attached:
![WhatsApp Image 2022-10-07 at 12 21 09](https://user-images.githubusercontent.com/96689639/194486101-58237ae7-4940-4653-b331-c5e9cdc7a2dc.jpeg)

**Smartphone (please complete the following information):**
 - Device: [Samsung A50s]
 - OS: [Android 11]
 - Browser [Chrome]

**Comment by ayushanand16** [comment]
@akshitagupta15june 
Please let me work on this issue.
Thanks.

**Comment by akshitagupta15june** [comment]
we are working on changing background so it will be visible afterwards

**Comment by ayushanand16** [comment]
Alright. Thanks
