### ISSUE TITLE
SOS report Heading

### ISSUE THREAD

**Issue by kartikmandhan** [akshitagupta15june/PetMe#217]
The heading of SOS report page has many capitalized letters in between the sentence which doesn't seems professional, I understand that those words are capital in order to highlight user's attention on them.
For ex: "Critical", "Animal Care"
![Screenshot 2022-10-07 at 12 30 01 PM](https://user-images.githubusercontent.com/56060122/194487177-7ab9668e-52f0-4124-9da7-297f85b4cb13.png)
Suggestion: Either Bold/italicize or change their color in order to emphasize on those words instead of capitalizing them.
Ex: 
![Screenshot 2022-10-07 at 12 31 15 PM](https://user-images.githubusercontent.com/56060122/194487384-dfa15834-22db-48db-8cdc-5e1000fb2b4d.png)

**Comment by akshitagupta15june** [comment]
this is not needed
