### ISSUE TITLE
Adding Contents to the Volunteer Page

### ISSUE THREAD

**Issue by ayushanand16** [akshitagupta15june/PetMe#218]
**Is your feature request related to a problem? Please describe.**
The current volunteer page has no content

**Describe the solution you'd like**
Instead of a blank page, we ask the user to submit their details which will go in the backend

**Describe alternatives you've considered**
We can also alternatively use google forms or redirect the user to mail us instead

**Comment by akshitagupta15june** [comment]
Currently we are working on it
No form needed
