### ISSUE TITLE
Navbar improvement in donate animals section

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#22]
add a better UI

**Comment by sambhavgupta0705** [comment]
Hey I would like to work on this issue during hacktoberfest.
Please assign this issue to me

**Comment by Satyakoidala** [comment]
@akshitagupta15june ,

What kind of UI improvements are expected? Also, can I add my own custom CSS file(s) if necessary? 

I could observe so much empty space beside the logo-and-adopt-today context in the header. Can the navbar section be moved there?

**Comment by sambhavgupta0705** [comment]
Hey ,can I work on this issue please

**Comment by Satyakoidala** [comment]
@akshitagupta15june , is this issue still open to working? I see the UI for Navbar component has already been updated.
