### ISSUE TITLE
Input Box Outline is not Uniform

### ISSUE THREAD

**Issue by mohdhaider07** [akshitagupta15june/PetMe#220]
**Describe the bug**
Input Box outline are different on different pages

**Screenshots**
**Donate Animal Form**
![image](https://user-images.githubusercontent.com/86488954/194521643-9f6d2173-537f-46fa-941b-1d0c7b3ca694.png)

**Contact us Form**
![image](https://user-images.githubusercontent.com/86488954/194521972-983255d7-1704-4312-b376-d6afbf6a318f.png)

**SOS Report Form**
![image](https://user-images.githubusercontent.com/86488954/194522134-1390b9ef-d447-42d5-b0d7-865f7b803fad.png)

**SOS report from Button text should be white**
![image](https://user-images.githubusercontent.com/86488954/194522890-a9067401-3b91-4a22-b915-7610ead16b51.png)

**Additional context**
I think Black outline would be nice, I want to make it uniform
can you assign this to me

**Comment by akshitagupta15june** [comment]
this issue is not needed
