### ISSUE TITLE
Navbar does not link to home page

### ISSUE THREAD

**Issue by annabaginski** [akshitagupta15june/PetMe#223]
**Describe the bug**
The navbar does not link back to the home page when on other pages. 

**To Reproduce**
1. Navigate to different page such as Donate Animals or SOS Report
2. Click Home on navigation bar 

**Expected behavior**
Link needs to be changed to link back to homepage

**Additional context**
I would be happy to add this quick fix!

**Comment by akshitagupta15june** [comment]
go for it

**Comment by Priyadarshani7** [comment]
Hey ! Can I work on this issue?

**Comment by kasib12** [comment]
**BUG**
The navbar is not linked back to the "Home" page when on other pages.

**Resolving The Bug**
This unexpected behavior is arising may be due to the href attribute.

**I would be happy to help fix this bug. Please assign it to me**

**Comment by annabaginski** [comment]
This bug has been resolved
