### ISSUE TITLE
SOS report button UI 

### ISSUE THREAD

**Issue by mohdhaider07** [akshitagupta15june/PetMe#226]
**Describe the bug**
UI of SOS button is not looking good

**Screenshots**
![image](https://user-images.githubusercontent.com/86488954/194590177-86cbb7e0-c0d0-4a42-8c8d-a3b89f9f2061.png)

**Additional context**
I want to add  hover and shadow effect

**Comment by akshitagupta15june** [comment]
firstly work on previous assigned issue
