### ISSUE TITLE
Adopt me page phone number is allowing other characters

### ISSUE THREAD

**Issue by 19sriram** [akshitagupta15june/PetMe#227]
**Describe the bug**
Phone number in "Adopt me" page is allowing other characters which are non-numeric

**Expected behavior**
Telephone number should allow only numeric

**Screenshots**
![image](https://user-images.githubusercontent.com/5829079/194595686-cec420b7-276b-4192-bd32-3ec63946c381.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Additional context**
Happy to fix it as always

**Comment by Potato-29** [comment]
can you assign this to me?
