### ISSUE TITLE
Adding favicon and animation

### ISSUE THREAD

**Issue by sumitkr2000** [akshitagupta15june/PetMe#229]
Hey @akshitagupta15june I want to add favicon and animation to your website. Can you please assign me this issue so that I can work on it ?

**Comment by akshitagupta15june** [comment]
where are u planning to add?

**Comment by sumitkr2000** [comment]
Favicon will be simply added on the top as you know and animations on dog cards and contact us.

**Comment by sumitkr2000** [comment]
@akshitagupta15june  Hoping to get a response!
