### ISSUE TITLE
Disregard*** Issues with directing to proper pages from Index.html 

### ISSUE THREAD

**Issue by vita-tran** [akshitagupta15june/PetMe#230]
**Describe the bug**
The page for "Become A Volunteer" and "Blogs" can't be accessed on the Home Page

**Expected behavior**
Page should load to those particular html files (and should be able to return to index.html) 

**Additional context**
I'd love to work on this and ensure that the linking between pages is fully functional 

UPDATE: I didn't realize there was no content inside those two pages yet, my apologies!

**Comment by akshitagupta15june** [comment]
thanks we are working on those pages
