### ISSUE TITLE
Want to add volunteer form in volunteer.html

### ISSUE THREAD

**Issue by KAMYAVERMA** [akshitagupta15june/PetMe#247]
**Is your feature request related to a problem? Please describe.**
Yes, there is nothing when we click on "become a volunteer".

**Describe the solution you'd like**
I want when we click on "become a volunteer" button, a form will display which will take the info of volunteer

**Describe alternatives you've considered**
Nothing is there in volunteer page. Want to add a form for the same.

**Additional context**
![volunteer ](https://user-images.githubusercontent.com/85511676/194720457-bc1fa90e-363d-47e0-adbb-6fec4d24af82.jpg)

**Comment by TheNobody-12** [comment]
please add hactoberfest to it @akshitagupta15june

**Comment by TheNobody-12** [comment]
I want to contribute towards this issue

**Comment by KAMYAVERMA** [comment]
Kindly, assign it to me.
HAPPY HACKING

**Comment by akshitagupta15june** [comment]
It is not required
Thanks
