### ISSUE TITLE
Improve the card design UI bug

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#25]
The problem in initial cards
whenever we put a big location name like "Jammu Kashmir" then the Kashmir word goes below so its not allign

also if we write full "Golden Retriever" then it also misaligns

![image](https://user-images.githubusercontent.com/57909583/192081537-f4395822-0601-4a06-b335-4586c85be511.png)

**Comment by Pratham-19** [comment]
Hi can I work on this

**Comment by akshitagupta15june** [comment]
ok assigning you @Pratham-19

**Comment by Pratham-19** [comment]
> ok assigning you @Pratham-19

thnx

**Comment by Pratham-19** [comment]
Can you assign me to logo  and navbar too

**Comment by Pratham-19** [comment]
also where can I dm you ?

**Comment by akshitagupta15june** [comment]
Join the discord link present in readme

**Comment by akshitagupta15june** [comment]
Better is work on this issue so as to give chance to other contributors
