### ISSUE TITLE
Coming Soon Page for blog.html

### ISSUE THREAD

**Issue by gopukr** [akshitagupta15june/PetMe#258]
**Is your feature request related to a problem? Please describe.**
Clicking on Blogs from the navbar leads to a blank page which feels like the site is broken.

**Describe the solution you'd like**
Temporarily using a 'Coming Soon' page will give positive feedback to the users navigating to blogs.html

**Additional context**
Additionally, we could place 'subscribe to our newsletter' content on the page or we could give a message which prompts the user to contribute to blogs and also provide information to do the same.

**Comment by Anuran12** [comment]
@gopukr  I am currently working on this  #156
