### ISSUE TITLE
About us button not working on blog page

### ISSUE THREAD

**Issue by nalowageena** [akshitagupta15june/PetMe#266]
**Describe the bug**
On the [blog page](https://akshitagupta15june.github.io/PetMe/blog.html), the **About us** link does not redirect to the about us section of the homepage

**To Reproduce**
1. Go to '[blog page](https://akshitagupta15june.github.io/PetMe/blog.html)'
2. Click on **About us** on nav bar.
4. Behaviour: No effect

**Expected behavior**
A redirect to the about us section of the homepage

**Desktop:**
 - OS: Windows
 - Browser Chrome

**Comment by akshitagupta15june** [comment]
Go for it

**Comment by nalowageena** [comment]
Thanks for merging. I was really nervous when I opened this issue.
I will close it now.
