### ISSUE TITLE
Text of the contact us form cannot be seen in light mode

### ISSUE THREAD

**Issue by nalowageena** [akshitagupta15june/PetMe#278]
**Describe the bug**
If you change to light mode on the pet me website, the text and labels of the contact us form cannot be seen as they have the same color as the background.

**To Reproduce**
1. Go to the pet me website
2. Click on the 'Contact us' button
3. Toggle light mode
4. Observe that no text or label can be seen on the form

**Screenshot**
![image](https://user-images.githubusercontent.com/77391048/196619456-74cf2c0d-a377-4fd5-90f2-5a13b0793d2f.png)

**Comment by elijahlc** [comment]
Hi there! I believe I have addressed this issue with my recent pull request ( #280 ).

**Comment by elijahlc** [comment]
I think this can be closed?

**Comment by nalowageena** [comment]
Yeah I'll close it now
