### ISSUE TITLE
Changing the background

### ISSUE THREAD

**Issue by irmeenhusain** [akshitagupta15june/PetMe#286]
**Is your feature request related to a problem? Please describe.**
The background doesn't go with the theme.

**Describe the solution you'd like**
Changing the background.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/84924821/198817048-7e7e03fd-5ca4-4b9d-81cb-0c72e28109c8.png)

**Comment by dankokonate** [comment]
assign me please

**Comment by omk-coder** [comment]
what kind of background do we needed did some work on this issue.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/93393539/202733675-5a6b11f5-b3e8-44b5-ba4e-e0983d1f7b7a.png">
using this image as a background
<img width="500" alt="image" src="https://user-images.githubusercontent.com/93393539/202733821-d19bf244-45ab-438e-9ddb-0b1dd448bf4c.png">

**Comment by omk-coder** [comment]
@irmeenhusain

**Comment by omk-coder** [comment]
can anyone pls look into this..

**Comment by akshitagupta15june** [comment]
Hi the previous background look background!
