### ISSUE TITLE
Improves the visibility of pet images

### ISSUE THREAD

**Issue by jcbotero** [akshitagupta15june/PetMe#302]
Hi,

Although the images have a good resolution, perhaps when someone is interested in a specific one, we can improve their experience on the web, by increasing its size when clicking on it.

I could add some interactivity to the images, with an eventlistener and a close icon.

I could try something like this if you're interested in seeing the results.

Greetings

**Comment by akshitagupta15june** [comment]
Go for it

**Comment by mud1tx** [comment]
@akshitagupta15june I can work on this feature today only, please assign it to me.
