### ISSUE TITLE
Removing Whitespace bug under the Hero image and aligning the Text properly. 


### ISSUE THREAD

**Issue by Othniel01** [akshitagupta15june/PetMe#304]
I noticed at the very first time of entering the site. 

• The hero image was quite different from what appeared in the readme. 

• Not to talk about the huge white space underneath it. 

Screenshot:

![198420811-655925db-e26d-4ccb-a3b5-f02a3c94a616.png](https://user-images.githubusercontent.com/121637925/221414637-1977778a-389f-4045-a854-53c3af08d0e2.png)

Fix; 

• I can remove the Whitespace and align the text in its proper position.

**Comment by Othniel01** [comment]
It's my first time here and I already fixed this bug and created a pull request before reading about having to report the bug and having it assigned first. I sincerely apologise for that.

**Comment by AdityaGoel0320** [comment]
is there space to do this task .

**Comment by Othniel01** [comment]
I think it has been done already but there are other task still available.
Check out #472
