### ISSUE TITLE
Dark and Light Mode switch not fully functional

### ISSUE THREAD

**Issue by raslene5** [akshitagupta15june/PetMe#315]
**Describe the bug**
A clear and concise description of what the bug is: 
Currently, when attempting to switch between Dark and Light Mode on the PetMe website, only the navigation bar changes and not the rest of the screen. This can lead to a jarring user experience and make it difficult for users to read the content on the website.
Expected Behavior: When the Dark or Light Mode switch is toggled, the entire website should change to the appropriate mode, not just the navigation bar.

**To Reproduce**
1. Go to 'https://akshitagupta15june.github.io/PetMe/reportstary.html?'
2. Click on 'the sun or the moon on the  top right corner in the nav bar '

Expected Behavior: When the Dark or Light Mode switch is toggled, the entire website should change to the appropriate mode, not just the navigation bar.
**Screenshots**
![i1](https://user-images.githubusercontent.com/122980534/226133676-a82cab2a-109c-4a55-bceb-e4aba27308ba.GIF)
![i2](https://user-images.githubusercontent.com/122980534/226133687-717a864c-3810-468a-a06f-463607306c21.GIF)
i can fix it once i get assigned to it

**Comment by SandeepKumar2024** [comment]
I want to work upon it . 
Can you assign me  ?

**Comment by karthiknadar1204** [comment]
If this issue is still open,please assign it to me

**Comment by mud1tx** [comment]
@raslene5 I can easily resolve this issue please assign it to me.

**Comment by suzy-g38** [comment]
Can I work on it for gssoc23?
