### ISSUE TITLE
Update README.md with more detailed information

### ISSUE THREAD

**Issue by raslene5** [akshitagupta15june/PetMe#317]
**Description:**
The current README.md file provides a brief overview of the PetMe project, but it could benefit from more detailed information about how to use the application, how to set it up, and how to contribute to it. I suggest updating the README.md file to include more information about the project's features, installation instructions, and contribution guidelines. This would make it easier for new users to get started with the project and for contributors to understand how they can help improve it.

i can do it once i get assigned to it

**Comment by akshitagupta15june** [comment]
go for it @raslene5

**Comment by karthiknadar1204** [comment]
@raslene5 ,are you still working on this issue?
