### ISSUE TITLE
Bug alert: contact us form UI is no more

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#32]
Please add a cool UI for contact us form and replace the action part with the previous form

**Comment by Susmita-Dey** [comment]
@akshitagupta15june Image is broken and not visible

**Comment by akshitagupta15june** [comment]
yes

**Comment by stephane-r** [comment]
Hey @akshitagupta15june 

What is the role of the checkbox ? 😄

**Comment by akshitagupta15june** [comment]
@stephane-r it was a kind of toggle button in which if we clicked the contact form opened

**Comment by stephane-r** [comment]
Okay, it's clearer 😸 don't want show always the form ?

**Comment by akshitagupta15june** [comment]
didn't understand what you are saying?

**Comment by akshitagupta15june** [comment]
@stephane-r would you like to work on this issue?

**Comment by stephane-r** [comment]
Yep

**Comment by akshitagupta15june** [comment]
Fine go for it @stephane-r
