### ISSUE TITLE
Title: Broken button to subscribe to the newsletter

### ISSUE THREAD

**Issue by raslene5** [akshitagupta15june/PetMe#321]
**Description:**
The "Subscribe" button in the bottom of the PetMe website is not working. When clicked, after filling the form, it does not trigger any action as expected. Instead, nothing happens and users are unable to subscribe to the newsletter.

**To Reproduce**
1)Go to the PetMe website: 'https://akshitagupta15june.github.io/PetMe/#'
Click on the "Subscribe" button in the bottom of the website.
Observe that the button does not trigger any action, and users are unable to subscribe to the newsletter.

**Expected behavior**
Clicking on the "Subscribe" button in the bottom of the website should trigger an action that leads users to sign up to receive the PetMe newsletter.

**Impact:**
This issue prevents users from subscribing to the PetMe newsletter, which can impact the website's ability to communicate with its audience and keep them informed about updates and news related to the website.

**Comment by okaydivyansh** [comment]
kindly assign this issue to me.

**Comment by okaydivyansh** [comment]
There is no js for the subscribe button. there is no link attached to it

**Comment by karthiknadar1204** [comment]
If this issue is still open,please assign it to me,i can fix it

**Comment by mud1tx** [comment]
@akshitagupta15june I can work on this issue by using EMAIL.JS. With the help of which a user can subscribe and he/she will get the newsletter using Email.

**Comment by sandeep0009** [comment]
hey if this issue is still open can you assign it to  me
