### ISSUE TITLE
Misaligned header on Opera browser

### ISSUE THREAD

**Issue by gabrysia694** [akshitagupta15june/PetMe#325]
**Describe the bug**
The menu on the header is not properly aligned on Opera browser.

**Screenshots**
<img width="916" alt="Bez tytułu" src="https://user-images.githubusercontent.com/97764356/230923368-2bcfb36e-4ee8-43aa-8ec5-77f706043de3.png">

**Comment by schan610** [comment]
I believe that's a responsive issue which I'd love to contribute to fix if someone wants to assign it to me!
