### ISSUE TITLE
Addition of BLOG and EVENT in the menu bar

### ISSUE THREAD

**Issue by tangorishi** [akshitagupta15june/PetMe#326]
/I suggest an addition of a Blog button in the menu section where different people can share their experience of adopting or donating a pet, or can share their personal experience of growing up a pet. 
In addition to this there also can be a Event button in the menu bar which will be having latest and complete information of any sort, regarding pets.

![Screenshot (270)](https://user-images.githubusercontent.com/110519406/230998576-e3f63d38-8c60-4f3f-9003-e40ca9291f2c.png)

edit- I can work on this, if assigned and also if the owner feels the need for addition of this one.

**Comment by BHANUJATIN** [comment]
pleas assign it under GSSOC'23 to me
