### ISSUE TITLE
Remove "our contributors" section from home page of the website

### ISSUE THREAD

**Issue by rohansx** [akshitagupta15june/PetMe#328]
![Screenshot from 2023-04-15 00-24-38](https://user-images.githubusercontent.com/33249782/232132452-dbd47cfc-59a3-4bdc-8069-9b2d744cf545.png)
"Our contributors" section on the main page does not look good. It should be either removed or we can add all the contributors to the about us page after creating the "about us" page and can also move the content of the about us section to that page so that the web page will look more in a systematic manner

**Comment by Yashdon999** [comment]
I Would like to work on this issue

**Comment by Hayat4144** [comment]
you can assign me this task . i will try my best to improve the web page by create separate about page and adding contributor section in about page and i also remove above section from the home page and put it in about page.

**Comment by MOHDNEHALKHAN** [comment]
@akshitagupta15june If you agree with this issue can i work on it

**Comment by Rihem-taboubi** [comment]
Hello, I would like to work on this issue by creating a new AboutUs page and adding sections as @Hayat4144 mentioned.
@akshitagupta15june
