### ISSUE TITLE
Adding Favicon to the website

### ISSUE THREAD

**Issue by mnik7044** [akshitagupta15june/PetMe#331]
Hey @akshitagupta15june I want to add favicon to this website as well as it looks a bit odd without the favicon.

**Comment by mnik7044** [comment]
Please assign this issue to me @akshitagupta15june

**Comment by abhinav2712** [comment]
@akshitagupta15june I can work on this, issue this to me

**Comment by mnik7044** [comment]
Hey @akshitagupta15june I think I can contribute to the project by adding it. Please assign it to me.

**Comment by mnik7044** [comment]
Hey @akshitagupta15june I think I can contribute to the project by adding it. Please assign it to me.

**Comment by abhinav2712** [comment]
@akshitagupta15june This issue is solved in #332 , Do review it thank you
