### ISSUE TITLE
Poorly Organized Home Page

### ISSUE THREAD

**Issue by raslene5** [akshitagupta15june/PetMe#336]
**Describe the bug**
The current home page of the PetMe website is cluttered and poorly organized, which can make it difficult for users to find the information they need. The various sections are not clearly differentiated, and the overall layout is not intuitive. This can lead to a frustrating user experience and discourage users from exploring the website further.

**To Reproduce**
1. Go to 'https://akshitagupta15june.github.io/PetMe/'

**Additional context**
Proposed solution: To address this issue, we should consider redesigning the home page to make it more user-friendly and easy to navigate. This could involve reorganizing the sections to clearly differentiate between them, improving the layout and visual design, and adding clear and concise headings and descriptions for each section. By improving the home page, we can create a more positive user experience and encourage users to explore the rest of the website.

**Comment by nikim178** [comment]
hey, I'm interested in working on it. May I have permission to tackle this issue?

**Comment by nikim178** [comment]
I'm interested in working on it. May I have permission to tackle this issue?
for gssoc'23

**Comment by saiful64** [comment]
I'm interested in working on this issue under GSSoC'23
