### ISSUE TITLE
Missing Content on the Adopt Page

### ISSUE THREAD

**Issue by raslene5** [akshitagupta15june/PetMe#337]
**Describe the bug**
The Adopt page on the PetMe website is missing important information about the adoption process, such as the requirements for adopting a pet, the adoption fees, and the adoption application process. This makes it difficult for potential adopters to understand how to adopt a pet from PetMe. 

**To Reproduce**
1. Go to 'https://akshitagupta15june.github.io/PetMe/index.html#About'
2. Click on 'Adopt me'

**Additional context**
Adding this information to the Adopt page would improve the user experience and make it easier for people to adopt pets from PetMe.

**Comment by abhinav2712** [comment]
@raslene5 I dont think I can see the error, the adopt page has enough information

**Comment by AishwaryVishwa** [comment]
I would like to work on this issue. I think we can use a image slider for showing all this information which will also be eye catching.
And please provide full process description and what other information is to be added.

**Comment by saiful64** [comment]
I would like to work in this issue. We can include necessary information regarding the adoption process in adoption page. Also I think the fees should be included in the home page itself as price tag/adoption fees
