### ISSUE TITLE
Lack of Visual Appeal on News Page

### ISSUE THREAD

**Issue by raslene5** [akshitagupta15june/PetMe#339]
**Describe the bug**
The News page of the PetMe website lacks visual appeal and appears plain and uninviting to users. Currently, the page only consists of plain text with no engaging visuals or graphics to make the page more visually appealing. This can make the page unattractive and uninteresting to users, which could discourage them from engaging with the content.

**To Reproduce**
1. Go to 'https://akshitagupta15june.github.io/PetMe/index.html'
2. Click on 'Pet news' in the navbar

**Additional context**
adding more engaging visuals and graphics to make the page more visually appealing. This could include adding images related to the news articles, using an attractive layout, and incorporating other visual elements such as icons or infographics. By enhancing the visual appeal of the News page, we can increase user engagement and make the page more inviting for visitors. i can do it once i get assigned to it

**Comment by anuza08** [comment]
hey, can you assign me this issue?

**Comment by sandeep0009** [comment]
hey can you assign me this issue

**Comment by mahekkg** [comment]
Hi there! I would like to contribute to improving the News page of the PetMe website. I have reviewed the bug report and I agree that adding engaging visuals and graphics would greatly enhance the page's visual appeal. Once assigned, I'll work on incorporating relevant images, an attractive layout, and other visual elements to make the page more inviting for users. Looking forward to contributing to this project! 
Please assign this task to me. Thank you!

**Comment by saiful64** [comment]
I'm interested in working on this issue under GSSoC'23
