### ISSUE TITLE
Missing Search Bar on Blog Page

### ISSUE THREAD

**Issue by raslene5** [akshitagupta15june/PetMe#340]
**Describe the bug**
The Blog page of the PetMe website does not have a search bar, making it difficult for users to find specific blog posts. This can lead to frustration and make it harder for users to navigate the website and find the content they are looking for.
**To Reproduce**
1. Go to 'https://akshitagupta15june.github.io/PetMe/'
2. Click on 'Blogs' in the navbar

**Expected behavior**
We should consider adding a search bar to the Blog page to make it easier for users to search for specific blog posts by keywords or topics.

**Additional context**
Proposed Solution: Add a search bar to the Blog page to allow users to search for specific blog posts based on keywords or topics. This will improve the user experience and make it easier for users to navigate the website and find the content they are looking for.

**Comment by sandeep0009** [comment]
hello sir can you assign me this issue i will make sure this task to be done very fast

**Comment by yamadivya** [comment]
Hello @raslene5 I am interested to contribute

**Comment by Cipher-08** [comment]
![image](https://github.com/akshitagupta15june/PetMe/assets/74664860/8dde8599-37cb-47f7-9291-2e7e5604c5d2)

Added the search button with 

![image](https://github.com/akshitagupta15june/PetMe/assets/74664860/727762e6-e72d-4917-b320-6ee546a84fbc)
for not present and if the text is present in it then 

![image](https://github.com/akshitagupta15june/PetMe/assets/74664860/1b8f85e2-0e9d-4634-adbb-96f55a5957a6)
