### ISSUE TITLE
Hidden text in the email box of the subscribe button .

### ISSUE THREAD

**Issue by Rihem-taboubi** [akshitagupta15june/PetMe#349]
When you click to enter your email in the box before the subscribe button. The text is hidden and the characters are not shown.

**Comment by Akshaykumar4524** [comment]
Hi @Rihem-taboubi I tried to resolve the issue can you pls assign it to me and check the PR

https://github.com/akshitagupta15june/PetMe/pull/350

**Comment by Rihem-taboubi** [comment]
Hello, @Akshaykumar4524 I couldn't assign you.I am not the owner of this repository.

**Comment by Akshaykumar4524** [comment]
@akshitagupta15june can you please have look into the PR
