### ISSUE TITLE
The "Become a volunteer" option under support us link is not styled

### ISSUE THREAD

**Issue by piyushkhurana2019** [akshitagupta15june/PetMe#358]
**Describe the bug**
The "Become a volunteer"  option is not styled

**To Reproduce**
1. hover on sponsor option present in the navigation bar
2. See error

**Expected behavior**
It should be Eye catching so that the user can think twice to join the community 

**Screenshots**
<img width="1440" alt="Screenshot 2023-05-20 at 1 38 56 AM" src="https://github.com/akshitagupta15june/PetMe/assets/96003210/7300b0b3-4dd8-446a-82ad-e94cbe560562">

**Desktop (please complete the following information):**
 - OS: mac os
 - Browser: chrome

**Comment by Vishal-Parasram** [comment]
@akshaaatt can I work on this issue under GSSoC

**Comment by ani0722** [comment]
@piyushkhurana2019 
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on a solution. Please assign this issue to me, and I will start working on it.

**Comment by Cipher-08** [comment]
I am on the code and working with this issue.. Hope you will like the changes !!

**Comment by akshitagupta15june** [comment]
It is currently not needed in website
