### ISSUE TITLE
Add github repo stats in the main readme

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#36]
for example
![image](https://user-images.githubusercontent.com/57909583/192417213-d554e0f4-faa5-4841-88ec-9f8e31d26bac.png)

**Comment by Harsh97x** [comment]
I'd like to work on it, please assign me.

**Comment by akshitagupta15june** [comment]
as u are working on the logo issue so we are letting other contributors to work on it, to give chance to everyone

**Comment by Harsh97x** [comment]
That's fine with me. It's my first time participating. So I got a little too eager :)

**Comment by Pranjalmishra30** [comment]
Hi I would like to work on this issue, if its not assigned

**Comment by akshitagupta15june** [comment]
Ok @Pranjalmishra30 assigning u
