### ISSUE TITLE
Link pet names to customized profiles

### ISSUE THREAD

**Issue by ERHolguin** [akshitagupta15june/PetMe#361]
Having a short blurb about each pet on the website would be nice. As someone who has adopted pets, I've found this information very helpful. This determines whether the animal will be a good fit for my household and if it will get along with my existing pets. 

If you like this idea, please assign this issue to me. I'm with the GSSoC'23 program.

**Comment by arjun26122002** [comment]
can you assign me for this work ?

**Comment by akshitagupta15june** [comment]
It is currently not needed in website
