### ISSUE TITLE
Enhancement: Enhance Contributors Section UX - Enable GitHub Icon Redirect

### ISSUE THREAD

**Issue by Saurav-Pant** [akshitagupta15june/PetMe#364]
Requesting an improvement in the Contributors section UX. 
Option 1: Enable the GitHub icon to redirect users to the GitHub contributors page for seamless navigation and better engagement. Option 2: Alternatively, consider removing the icon for a cleaner design. Your decision on either approach would greatly enhance the user experience. Thank you for considering this suggestion.

if yes assign it to me.

https://github.com/akshitagupta15june/PetMe/assets/103263909/8e487d70-9c05-4048-b665-acf1e6bd7a45

**Comment by Nayanika-12** [comment]
@akshitagupta15june please assign me this issue. I can work on this.

**Comment by Saurav-Pant** [comment]
Yes, I made a PR for this, waiting for merging.
