### ISSUE TITLE
IMPROVE THE UI FOR THE CONTACT US FORM ON THE PAGE

### ISSUE THREAD

**Issue by karthiknadar1204** [akshitagupta15june/PetMe#365]
**Is your feature request related to a problem? Please describe.**
THE ui of the contact page doesnt align with the rest of the project

**Describe the solution you'd like**
We can make the contact form aligned to the center but contained in a container with backgeound color while coming out from the right.

**Describe alternatives you've considered**

**Additional context**

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by pjyoti121** [comment]
please assign me this issue

**Comment by karthiknadar1204** [comment]
Yes, will be submitting today

**Comment by AnjaniChilumula123** [comment]
Is this issue still active?
If so.. will you assign this to me??
