### ISSUE TITLE
Improve the pet news page making it more engaging 

### ISSUE THREAD

**Issue by karthiknadar1204** [akshitagupta15june/PetMe#367]

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by ParamveerSingh-7** [comment]
I would like to work on this project under gssoc'23. 
I can make this page even more attractive and appealing to match its layout with the other pages.
Can also provide the Figma design .

**Comment by akshitagupta15june** [comment]
some contributor is working on this
