### ISSUE TITLE
Create a new logo for the website

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#37]
initial logo 
![image](https://user-images.githubusercontent.com/57909583/192417398-91fefa71-070c-4389-988b-66c64eb2f625.png)

**Comment by Harsh97x** [comment]
I would like to work on it, please assign me.

**Comment by akshitagupta15june** [comment]
fine go for it @Harsh97x 
assigning u

**Comment by akshitagupta15june** [comment]
Please keep the theme in mind while making a logo

**Comment by Harsh97x** [comment]
ok 👍🏻

**Comment by kanishk6103** [comment]
> Please keep the theme in mind while making a logo

Hey I tried making something after i saw this issue, I'll attach a screeenshot of a quick ideation of the logo I did

![ideation](https://user-images.githubusercontent.com/72643990/192806991-f7e1eb3e-2c9c-449f-b93a-9889fec3f5ef.png)

**Comment by akshitagupta15june** [comment]
@Susmita-Dey and @muditchoudhary can you review the above logo created by @kanishk6103 for our website please request changes if you want to.

**Comment by kanishk6103** [comment]
> @Susmita-Dey and @muditchoudhary can you review the above logo created by @kanishk6103 for our website please request changes if you want to.

This is just an ideation, if you like the ideation i will go ahead with it, Thanks :)

**Comment by Susmita-Dey** [comment]
@akshitagupta15june @kanishk6103 Looks good. But the current logo is also good

**Comment by akshitagupta15june** [comment]
@Susmita-Dey yes it is but actually for the website its looks kind of distorted so thought of creating a new

**Comment by akshitagupta15june** [comment]
@kanishk6103 then you can go for it and try to add a colourful logo that fits website

**Comment by Harsh97x** [comment]
Hey, @akshitagupta15june want some feedback on the logo, How is it?


![logo](https://user-images.githubusercontent.com/71343199/192825983-100f7319-7916-44fe-a0d1-271ddf29dfed.jpg)

**Comment by akshitagupta15june** [comment]
umm @Harsh97x it doesn't define the theme your previous one was good but try to do one thing in that instead of writing petme below write in between of picture and remove the logo part from where it is writting
i hope you can understand what i am saying

**Comment by akshitagupta15june** [comment]
better is to add a cat dog rabbit and write petme and then beautify accordingly
one example i am adding
![image](https://user-images.githubusercontent.com/57909583/192831579-15bb3e40-17f1-4429-9782-3264135be062.png)

**Comment by Harsh97x** [comment]
![Petmelogo2](https://user-images.githubusercontent.com/71343199/192839735-00133fad-593d-4348-b2d7-dd53a3fb0dd8.png)

I think this image conveys the theme better. What are your thoughts on it?
> and remove the logo part from where it is written
>
I don't get this part could you please elaborate further?

**Comment by akshitagupta15june** [comment]
Oh this picture looks very cool can u add rabbit also in it and write petme in box 

Pet me should be visible clearly in front of box

**Comment by Susmita-Dey** [comment]
@Harsh97x The last one is cute.

**Comment by Harsh97x** [comment]
Ok so how about this, it has all three of them and there is ample space to put the text in between the image.

![dogcatrabbit-withaheart-logo](https://user-images.githubusercontent.com/71343199/192844929-2c2b3c1b-fe61-49bb-a22a-d2f0aa35ed6e.png)

**Comment by akshitagupta15june** [comment]
That's so cute
Just increase font size a little and u are good to go
Try to give a pr after 1st October so it will be counted in hacktoberfest

**Comment by Susmita-Dey** [comment]
> That's so cute Just increase font size a little and u are good to go Try to give a pr after 1st October so it will be counted in hacktoberfest

I agree with you.

**Comment by muditchoudhary** [comment]
> > Please keep the theme in mind while making a logo
> 
> Hey I tried making something after i saw this issue, I'll attach a screeenshot of a quick ideation of the logo I did
> 
> ![ideation](https://user-images.githubusercontent.com/72643990/192806991-f7e1eb3e-2c9c-449f-b93a-9889fec3f5ef.png)

Wow it's good. I prefer this. Just add some colors to it.

Btw did you draw it by yourself?

**Comment by kanishk6103** [comment]
> > > Please keep the theme in mind while making a logo
> > 
> > Hey I tried making something after i saw this issue, I'll attach a screeenshot of a quick ideation of the logo I did
> > 
> > ![ideation](https://user-images.githubusercontent.com/72643990/192806991-f7e1eb3e-2c9c-449f-b93a-9889fec3f5ef.png)
> 
> Wow it's good. I prefer this. Just add some colors to it.
> 
> Btw did you draw it by yourself?

I didn't draw it all by myself, i did trace it and drew some of the face expressions and details on the dog by myself

**Comment by akshitagupta15june** [comment]
i prefer this one 
![image](https://user-images.githubusercontent.com/57909583/192962018-222a57c1-b07b-41b7-97a9-fda214acc767.png)

**Comment by akshitagupta15june** [comment]
just increase the font size a little

**Comment by Susmita-Dey** [comment]
> i prefer this one ![image](https://user-images.githubusercontent.com/57909583/192962018-222a57c1-b07b-41b7-97a9-fda214acc767.png)

Me too

**Comment by muditchoudhary** [comment]
Okay that's good too. We will add that then

**Comment by Harsh97x** [comment]
>just increase the font size a little
>

I increased the font.

![logo](https://user-images.githubusercontent.com/71343199/192994259-8d8e3d6d-88a5-4ce3-8802-4d39ad95cee0.jpg)
