### ISSUE TITLE
Adding adopt me button and improve cards

### ISSUE THREAD

**Issue by DurgaSanthosh** [akshitagupta15june/PetMe#377]
**Is your feature request related to a problem? Please describe.**
A button would give user attention to adopt me.  Ex. Now it's not capturing the attention of users.(I'm in GSSOC'23" as a contributor.)

**Describe alternatives you've considered**
A proper button is highlighted on the page and improved styling of cards.
**Additional context**
![Screenshot 2023-05-20 122818](https://github.com/akshitagupta15june/PetMe/assets/75644571/2cef8c27-3ae6-476c-9f71-a9545d138af1)

(can I take this up as a part of gssoc 23')

**Comment by akshitagupta15june** [comment]
currently its not needed for the website
