### ISSUE TITLE
Add a section "How to get started with open source?" in the readme

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#38]
take help from face-x readme https://github.com/akshitagupta15june/Face-X#readme
![image](https://user-images.githubusercontent.com/57909583/192442620-cbae0822-03e0-4351-8854-f9373997fb90.png)

**Comment by ABHIGYAN-MOHANTA** [comment]
Hey! Can I work on this? Since I myself am a beginner, I think I would be great for this. I just finished up my high school. I would be very grateful if you can assign it to me, I will make the pr on october 1st. Thanks! Also congratulations on mlh fellowship.

**Comment by akshitagupta15june** [comment]
cool @ABHIGYAN-MOHANTA go for it!

**Comment by ABHIGYAN-MOHANTA** [comment]
Thank you
