### ISSUE TITLE
Make the drop and drag feature functionable in donate animal form

### ISSUE THREAD

**Issue by ANKITy102** [akshitagupta15june/PetMe#382]
**Describe the bug**
A form opens Donate Animals link in navbar and in that there is feature to upload animal's image 
which does not work.

**To Reproduce**
1. Go to 'donate.html'
2. Scroll down to 'Your Pet's Image'
3. Click on 'Drop files to Attach, or Browse box'

**Expected behavior**
On uploading image, the uploaded image should show on top-left-corner

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Browser  chrome
 - Version 113.0.5672.127

I would like to fix the upload image box
Could you Assign it to me

**Comment by akshitagupta15june** [comment]
ok assigning you

**Comment by Nayanika-12** [comment]
Are  you still working on it @ANKITy102 ?
