### ISSUE TITLE
Multiple Bugs in this website

### ISSUE THREAD

**Issue by kriti-002** [akshitagupta15june/PetMe#383]
**Describe the bug**

1. Contact Us button is not working.
2. Hero Image text can be put it in center.
3. Adopt me button in the card can be styled.
4. News Section UI needs improvement.
5. Padding and the height of the About Us section can be increased (preferably to 100vh).
6. The card can be made to change on hover not only the image in the Meet Our Friends Section.
7. Follow Us On text on the Footer section should be increased as it doesn't seem aligned to the icons just below it.
8. Padding on the Report SOS form can be increased as it seems to touch the navbar.

@akshitagupta15june please give me this opportunity to tackle the issues listed by assigning this to me.

**Comment by akshitagupta15june** [comment]
Some contributors are already working on this
