### ISSUE TITLE
Add Button Back to Top

### ISSUE THREAD

**Issue by Ahtaxam** [akshitagupta15june/PetMe#385]
We should add a button at bottom right side of  Home page. when user click on button, it reach top of page.

**Note**: I would like to work on this issue under GSSOC'23.

**Comment by Aditi323** [comment]
I would like to work on this issue as a GSSOC contributor.

**Comment by SamridhiNancy** [comment]
"Hi there! I'm excited to contribute to this project'GSSOC;'23 I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward to collaborating with you all on this!

**Comment by MohdSaquib114** [comment]
Hey i want to work on this issue as a GSSOC contributor. Its going to be my first contribution to the opensource community.
Let me know if you want

**Comment by op-amateur** [comment]
Please assign me this issue, thank you.

**Comment by akshitagupta15june** [comment]
Some contributors are already working on this
