### ISSUE TITLE
The SOS button can be optimized 

### ISSUE THREAD

**Issue by theDRB123** [akshitagupta15june/PetMe#386]
hello , 
After observing and interacting with the site i have found that  normally a user might not be able to get the context of the SOS button provided at the bottom right corner,
The user might not be able to see that button or might not get the context of that .

**Solution** :- adding a hover animation  which makes the SOS box bigger and better visible when the user hovers over it , and also change the SOS to "Report Animal Abuse"  ,  doing so might increase user attention to the button 

If possible assign this issue to me as a GSSoC 2023 Contributor .
_Thank you ._

**Comment by Aditi323** [comment]
I would like to work on this issue as a GSSOC contributor.

**Comment by akshitagupta15june** [comment]
It is currently not needed in website
