### ISSUE TITLE
Homepage Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [akshitagupta15june/PetMe#387]
The homepage interface is nice but it can be improved by making some design adjustments. Working on the CSS of the homepage, I would like to make this homepage even more good.

**Comment by iamRabia-N** [comment]
I would like to work on this issue as part of GSSOC-23

**Comment by SamridhiNancy** [comment]
"Hi there! I'm excited to contribute to this project'GSSOC;'23 I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward to collaborating with you all on this!

**Comment by akshitagupta15june** [comment]
Some contributors are already working on this
