### ISSUE TITLE
Add a gallery section to the home page

### ISSUE THREAD

**Issue by Srija-Burugula** [akshitagupta15june/PetMe#388]
Adding a gallery section to the home page makes it even more attractive. We can also add a review section which will attract more users and will improve UI.
Please assign me this issue.

**Comment by Aditi323** [comment]
I would like to work on this issue as a GSSOC contributor.

**Comment by arjun26122002** [comment]
Hey, I want to work on issue. Can you please assign it to me under GSSOC23

**Comment by Srija-Burugula** [comment]
@arjun26122002 was this issue assigned to you?

**Comment by arjun26122002** [comment]
@Srija-Burugula nope

**Comment by Srija-Burugula** [comment]
@arjun26122002 Did you work on this issue?

**Comment by shubhangi-hash** [comment]
Kindly assign me this issue

**Comment by akshitagupta15june** [comment]
Some contributors are already working on this
