### ISSUE TITLE
Pictures of the pets in some of our friends section

### ISSUE THREAD

**Issue by Shaurya10101** [akshitagupta15june/PetMe#395]
**Is your feature request related to a problem? Please describe.**
It is really frustating to see only one picture that gets big on hovering , it is not very appealing to the eye and it doesn't reveal a lot about the pet

**Describe the solution you'd like**
There should be atleast 2-3 pictures that self change and not enlarge 

**Describe alternatives you've considered**
there are 4 pictures together displayed as a collage and one of them gets enlarged if hovered over the specific picture

**Additional context**

**Comment by AishwaryVishwa** [comment]
I would like to work on this issue please assign it to me @Shaurya10101

**Comment by akshitagupta15june** [comment]
Some contributors are already working on this
