### ISSUE TITLE
Adding Back-to-top button to the site

### ISSUE THREAD

**Issue by Sathvik902** [akshitagupta15june/PetMe#401]
**Is your feature request related to a problem? Please describe.**
In every page, whenever the user wants to get to the top, he must scroll by himself. This is tedious if the number of blogs are more.

**Describe the solution you'd like**
Adding a Back-to-top button on the right most bottom corner of the website would solve this.

I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by akshitagupta15june** [comment]
already present
