### ISSUE TITLE
Fav icon

### ISSUE THREAD

**Issue by SumitKanth** [akshitagupta15june/PetMe#406]
We can add a attracting fav icon to the website which gives good user experience. 

Plz assign me for this issue.

**Comment by codewithnadeem14502** [comment]
i have alread add fav icon in jy many porject, so I request you to assign me this issue

**Comment by DhairyaMajmudar** [comment]
Hey 👋 I'm Dhairya. I would be happy if you could this issue to me. I'll contribute to this issue under GSSoc'23. I can add the favicon as mentioned

**Comment by Silentshooter** [comment]
I want to work on this issue under GSSOC '23 . I also have the relevant skills for this issue to get fixed. So please approve my request.

**Comment by akshitagupta15june** [comment]
it is not currently needed for website
