### ISSUE TITLE
Improvement in home and blogs section

### ISSUE THREAD

**Issue by Anikinee** [akshitagupta15june/PetMe#407]
**Is your feature request related to a problem? Please describe.**
The CSS of the blogs section and the home page to be improved.

**Describe the solution you'd like**
The CSS of the blogs section must be improved. 

**Describe alternatives you've considered**
In the home page instead of a single picture, multiple pictures in transition will make it more attractive.

I can solve this issue. Please assign it to me under GSSOC'23.

**Comment by akshitagupta15june** [comment]
some contributor is working on this
