### ISSUE TITLE
Add a backend to donate animal section 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#41]
![image](https://user-images.githubusercontent.com/57909583/192443584-ecc3879d-309d-4fb7-9f50-542735bf2cf9.png)

**Comment by akshitagupta15june** [comment]
Creating this issue as a discussion

**Comment by tanisha-tech360** [comment]
Can you please elaborate what do you want  us to do in this section?

**Comment by adityabisht02** [comment]
Are you looking for a SQL database or a no SQL one? I can work on this but ill need the deployed database creds.

**Comment by adityabisht02** [comment]
Or I can simply implement this for a local DB and you can add the creds later.

**Comment by Sukriti-m** [comment]
Hi @akshitagupta15june 
I'd like to work on this issue. I have made many projects of backend using NodeJS. I will connect this to a MongoDB database. Please assign it to me.

**Comment by akshitagupta15june** [comment]
@muditchoudhary can you please help her

**Comment by muditchoudhary** [comment]
> Is it possible to connect it to Mongo db, if yes, I would like to start with this! @akshitagupta15june

Yes it's possible we are using a mongo db in this

**Comment by DugarRishab** [comment]
hey, can I do this too?

**Comment by akshitagupta15june** [comment]
Ok @DugarRishab

**Comment by DugarRishab** [comment]
Hii @muditchoudhary, i have a question. 

Every time someone donates a animal, will it be considered a pet? I mean will it be considered in a similar way to the other pets?

**Comment by DugarRishab** [comment]
> > Hii @muditchoudhary, i have a question.
> > Every time someone donates a animal, will it be considered a pet? I mean will it be considered in a similar way to the other pets?
> 
> I actually don't understand what you mean.

okay, leave it. I understand wat I need to do.
