### ISSUE TITLE
Navbar CSS  in donate page breaks. 

### ISSUE THREAD

**Issue by Noothan-am** [akshitagupta15june/PetMe#410]
**Describe the bug**
css of navbar breaks in donate page 

**To Reproduce**
1. Go to website url
2. Click on 'donate tab.'

**Expected behavior**

**Screenshots**
![image](https://github.com/akshitagupta15june/PetMe/assets/100135382/2e645fad-ad47-459b-a32d-4dd9f2fd60b8)

**Desktop (please complete the following information):**
 - OS:  Windows
 - Browser chrome

i want to work on this issue

**Comment by RahulRana701** [comment]
hi @akshitagupta15june I would like to work on this issue.........

**Comment by Noothan-am** [comment]
@RahulRana701 i am already working on this issue

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by VC6378** [comment]
Hello @akshitagupta15june, I want to work on this issue, please assign me
