### ISSUE TITLE
Set Contact Number Limit

### ISSUE THREAD

**Issue by SoundaryaKoutharapu** [akshitagupta15june/PetMe#411]
While filling the form "Donate for Animals".
contact number is taking numbers without limit.
It should be better if we add some limit to contact number.
![2023-05-20](https://github.com/akshitagupta15june/PetMe/assets/71914071/e18cc6f5-cc1e-4d4c-bf45-cb0060e3f373)

**Comment by SoundaryaKoutharapu** [comment]
Hello @akshitagupta15june 
Could you please assign this issue to me, I'd like to work on it under GSSOC'23.

**Comment by Anjali2312-Thombare** [comment]
Hello @SoundaryaKoutharapu ,
I would like to solve this issue . Can you  please assign me this issue ?

**Comment by akshitagupta15june** [comment]
some contributor is working on this
