### ISSUE TITLE
Enhancing Readability and Aesthetics: Elevating the H1 and Paragraph Elements in the Hero Section

### ISSUE THREAD

**Issue by jfmartinz** [akshitagupta15june/PetMe#415]
**Describe the bug**
I want to add a little bit styling to the h1 and paragraph on hero section to make it more aesthethic and readable for better user experience.

**To Reproduce**
1. Navigate to 'https://akshitagupta15june.github.io/PetMe/index.html'.
2. Locate the hero section.
3. Observe the paragraph and h1 within the hero section.

**Expected behavior**
We can make it more aesthethic and more readable for better user experience and aesthethic of the page

**Screenshots**
![image](https://github.com/akshitagupta15june/PetMe/assets/129386460/2b5b8815-7e4b-4d8d-8f10-da56d34ceef5)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [113.0.5672.127]

**Smartphone (please complete the following information):**
 - Device: [Realme c27]
 - OS: [Android]
 - Browser [chrome]
 - Version []

**Additional context**
I want to work in this under GSSoc contributor. Please assign this to me :)

**Comment by akshitagupta15june** [comment]
ok assigning you
