### ISSUE TITLE
 Improve Styling and Display of Scrolling Navigation/Scroll-To Feature on the Page

### ISSUE THREAD

**Issue by jfmartinz** [akshitagupta15june/PetMe#416]
**Describe the bug**
Currently, there is a bug with the scroll-to feature on the website. It does not display correctly on the page and lacks aesthetic appeal. I would like to improve its appearance and ensure that it functions properly. Additionally, I plan to implement a sticky functionality that will allow the scroll-to feature to remain fixed while scrolling.

**To Reproduce**
- Visit the webpage where the scroll-to feature is located.
- Scroll through the page to trigger the scroll-to feature.
- Observe the incorrect display and lack of aesthetic appeal.

**Expected behavior**
The scroll-to feature should display correctly on the page, with improved aesthetics. Additionally, it should remain sticky and fixed in position while scrolling.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I would love to work on this issue under GSSoc23 contributor. please assign this to me :)

**Comment by akshitagupta15june** [comment]
ok assigning you

**Comment by Nayanika-12** [comment]
As this issue is closed I would like to re-open it and work on it.
Can you please assign this to me @akshitagupta15june?

**Comment by jfmartinz** [comment]
> As this issue is closed I would like to re-open it and work on it. Can you please assign this to me @akshitagupta15june?

Im currently working on it. the issue was duplicate so the person open the issue close it
