### ISSUE TITLE
Landing page of "Adopt Me" button.

### ISSUE THREAD

**Issue by susanyeldo** [akshitagupta15june/PetMe#418]
**Description:** 

The landing page once you click the "Adopt Me" button under any particular animal is not properly styled.

**Screenshot:**

![Adopt Me - Google Chrome 5_20_2023 9_08_41 PM (2)](https://github.com/akshitagupta15june/PetMe/assets/92731934/adb38194-8032-4068-b404-282df1283a1c)

Please assign this issue to me as part of **GSSoC '23**.

**Comment by Mridulbirla13** [comment]
Hey! I think I can design the landing page of the Adopt Me button. I would like if this issue is assigned to me. 
Please assign this issue under GSSoC,23

**Comment by akshitagupta15june** [comment]
some contributor is working on this
