### ISSUE TITLE
Add Hover effect to social media section 

### ISSUE THREAD

**Issue by Prajwal0225** [akshitagupta15june/PetMe#421]
**Currently, when hovering over the social media logos on the PetMe website, no visual feedback or effect is displayed to indicate that they are interactive elements. This lack of feedback can lead to confusion for users who may expect some form of response when interacting with these logos.**

![social media petMe](https://github.com/akshitagupta15june/PetMe/assets/103810119/0b7c3758-fce6-4c80-be89-7306c9a5c49d)

### Expected Behavior:
When hovering over the social media logos, a visually distinct effect should be displayed to indicate that they are interactive elements. This effect could include changes in color, opacity, size, or any other visually appealing animation that clearly communicates their interactivity.

### Proposed Solution:
To resolve this issue and enhance user experience, the hover effect should be added to the social media logos. This can be achieved by implementing the following steps:

### Benefits:

-  **Improved User Experience**: The hover effect will provide immediate visual feedback to users, indicating that the social media logos are interactive elements.

- **Clearer Interaction Cues**: Users will be able to easily identify and engage with the social media links, enhancing navigation and encouraging social media engagement.
- **Aesthetically Pleasing**: The addition of hover effects can make the website feel more interactive and visually appealing, creating a positive impression for visitors.

**Comment by Vanshika-73** [comment]
Will be able to do this task effectively. Please assign me this issue under Gssoc23

**Comment by green-veggies** [comment]
I am interested in contributing in this project. Please assign this to me
