### ISSUE TITLE
Update of Contact Us section

### ISSUE THREAD

**Issue by Rupantar-Borphukan** [akshitagupta15june/PetMe#422]
UI/UX of Contact Us section is not matching with home page. It can be much improve.  Now, it has only basic input form i.e, name, email, message and button. Nothing else is there except this thing. We can build much better UI and we can add some more content to that.

![PetMe Web contactus](https://github.com/akshitagupta15june/PetMe/assets/94108574/afc0e253-5b6d-46ec-90b5-ebe892484b20)

Please allow me to improve that section under GSSoC '23 as a contributor. I will definitely improve much if allow me to the issue to solve.

**Comment by Anjali07Patel** [comment]
I feel happy to solve this issue. Please assign me this issue

**Comment by Naincy04** [comment]
Hello, I want to work on this issue under GSSoc'23 as a contributor. Please assign this issue to me.

**Comment by akshitagupta15june** [comment]
some contributor is working on this
