### ISSUE TITLE
Contact Us Page

### ISSUE THREAD

**Issue by Vanshika-73** [akshitagupta15june/PetMe#423]
There is requirement to add validation on fields of the contact us form in order to ensure the submission of correct details.
Please assign me this task under Gssoc23.

**Comment by samarthhapse** [comment]
Yes it is not really good and I would like to add some features and make it more attractive and engaging. I'm excited to contribute to this project 'GSSOC'23 . I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know..

thanks !

**Comment by akshitagupta15june** [comment]
some contributor is working on this
