### ISSUE TITLE
Improve: Pet news page 

### ISSUE THREAD

**Issue by Pragati-3003** [akshitagupta15june/PetMe#428]
I would like to improve pet news page as it is not eye pleasing.
I would like to change its ui/ux to make it more attractive.
So, please assign this issue to me under GSSOC'23.

**Comment by Anjali2312-Thombare** [comment]
Hi @Pragati-3003 
I would like to solve this issue .Can You please assign me this issue ?

**Comment by akshitagupta15june** [comment]
its currently not needed for website
