### ISSUE TITLE
Issue : Adopt me Button

### ISSUE THREAD

**Issue by Pragati-3003** [akshitagupta15june/PetMe#429]
I would like to improve Adopt me  button. 
After clicking adopt me button a page appears which is not good. 
I would like to change its ui/ux to make it more attractive.
So, please assign this issue to me under GSSOC'23.

**Comment by Anjali2312-Thombare** [comment]
hey @Pragati-3003  
I will improve Adopt button. please assign me this issue

**Comment by wisdom-egba** [comment]
Hello, please I would like to modify the 'adopt me' button, giving it a proper styling and hover effect  to have a great user experience
From GSSOC'23.
![Screenshot 2023-05-22 043624](https://github.com/akshitagupta15june/PetMe/assets/99222194/59a54f9e-8fb5-47cc-9672-99eafb2c4285)

**Comment by akshitagupta15june** [comment]
some contributor is working on this
