### ISSUE TITLE
Enhance : Contact Us form

### ISSUE THREAD

**Issue by Pragati-3003** [akshitagupta15june/PetMe#430]
I would like to improve contact us form as it is not good. 
I would like to change it or add some margin,padding and all to make it more attractive.
So, please assign this issue to me under GSSOC'23.

**Comment by kasturimandlik** [comment]
I would like to work on this issue under GSSOC'23. please assign me this issue

**Comment by samarthhapse** [comment]
Yes it is not really good and I would like to add some features and make it more attractive and engaging. I'm excited to contribute to this project 'GSSOC'23  . I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know..

thanks !

**Comment by op-amateur** [comment]
Please assign me this issue, thank you.

**Comment by akshitagupta15june** [comment]
some contributor is working on this
