### ISSUE TITLE
SOS Button is overlapping newsletter button in mobile view 

### ISSUE THREAD

**Issue by parthksingh1** [akshitagupta15june/PetMe#433]
**Describe the bug**
SOS Button is overlapping newsletter button in mobile

**Expected behavior**
SOS Button Above newsletter button

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 -Phone: Samsung Galaxy A33
 - Browser: Chrome

**Additional context**

**Comment by parthksingh1** [comment]
Please Assign me this under @GSSOC'23 to make it better

**Comment by Sathvik902** [comment]
Please assign it to me under @GSSOC'23 , I would love to contribute.
Thank you!
