### ISSUE TITLE
SEO of the Complete Website

### ISSUE THREAD

**Issue by Girishnikam** [akshitagupta15june/PetMe#434]
[GSSoC 2023] 

**Is your feature request related to a problem? Please describe.**

Having an SEO-friendly website can increase credibility, improve user experience, and gain more visitors to the website

**Describe the solution you'd like**

For making the website SEO friendly I'll like to implement following things

- Optimize the title tags and meta descriptions
- Using keywords in the website content (will perform proper research for keywords across all the search engines)
- Include keyword-rich anchor text in links
- Compressing the media (images, illustrations) to make sure website loads faster
- Clean up and organize the complete code
- (Optional) Implement various Google tools like Google Analytics, Google Search Console to see how site is performing in Google search results

**Additional context**
Find the attachment of example, how optimization will help to boost performance of the website

![use of title and meta description optimisation](https://github.com/akshitagupta15june/PetMe/assets/84145346/9129f038-f674-45a4-a248-9a1be0113134)

**Comment by akshitagupta15june** [comment]
its currently not needed for website

**Comment by Girishnikam** [comment]
Okay, thank you!
