### ISSUE TITLE
Changing the styling of Become a volunteer form and making it look good.

### ISSUE THREAD

**Issue by Vyom-26** [akshitagupta15june/PetMe#437]
Currently Become a Volunteer page has a form with very bad css. Also it strains the eye as the color selection isn't good.

I would like to totally transform this form and make it look appealing.

Please assign this issue to me under GSSOC 2023

**Comment by Naincy04** [comment]
Hello, I want to work on this issue under GSSoc'23 as a contributor. Please assign this issue to me.

**Comment by akshitagupta15june** [comment]
its currently not needed for website
