### ISSUE TITLE
Changing the styling of Contact Us form

### ISSUE THREAD

**Issue by Vyom-26** [akshitagupta15june/PetMe#438]
Currently the Contact Us form looks boring with zero styling and doesn't appeal to the user.
I would like to change the styling and css and make it look impressive.

Please assign this issue to me under GSSOC 2023.

**Comment by Vanshitgupta9717** [comment]
i can do it . please assign me this issue under GSSOC 2023

**Comment by Naincy04** [comment]
Hello, I want to work on this issue under GSSoc'23 as a contributor. Please assign this issue to me.

**Comment by green-veggies** [comment]
I can improve it under GSSoC please assign this to me

**Comment by akshitagupta15june** [comment]
its currently not needed for website
