### ISSUE TITLE
Add a tab containing some adoption success stories

### ISSUE THREAD

**Issue by rayarka26** [akshitagupta15june/PetMe#439]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rayarka26** [comment]
I would love to do this if you feel you can assign it. I will make a tab in navbar having "Our Success" and populating it with some content

**Comment by Naincy04** [comment]
Hello, I want to work on this issue under GSSoc'23 as a contributor. Please assign this issue to me.

**Comment by akshitagupta15june** [comment]
its currently not needed for website
