### ISSUE TITLE
Add the rescuing pets page for the street and disabilities pets 

### ISSUE THREAD

**Issue by NishanthIlango** [akshitagupta15june/PetMe#442]
Add the page for rescuing the pets from the streets and disabilities pets and taking care by Animal Welfare NGO(add a contact).

**Comment by green-veggies** [comment]
I would like to contribute in this project under GSSoC'23 Please assign this to me

**Comment by kharshita590** [comment]
I would like to contribute in this project under GSSoC'23
Please assign me

**Comment by NishanthIlango** [comment]
I would like to contribute in it under GSSoC 2023,
Please assign me

**Comment by akshitagupta15june** [comment]
its currently not needed for website
