### ISSUE TITLE
Adding a "Scroll to top" button

### ISSUE THREAD

**Issue by Sakar95** [akshitagupta15june/PetMe#446]
Missing scroll-to-top button.

Addition of the "scroll to top" button that would float in bottom-right corner would enhance the user experience of the website.

I would love to work on this and request you to assign this issue to me as GSSoC 2023 Contributor

**Comment by Palakkgoyal** [comment]
Can you assign this issue to me? I can add this functionality

**Comment by Palakkgoyal** [comment]
I am under GSSOC'23

**Comment by op-amateur** [comment]
Please assign me this issue, thank you.

**Comment by khubaibkm** [comment]
Hello, I am a GSSOC'23 Contributor and want to work on this issue.
Thankyou!

**Comment by SHAIK-MUNEERUDDIN** [comment]
Hii, I can work on this issue please assign this to me as GSSoC 2023 contributor.Thank u

**Comment by akshitagupta15june** [comment]
its completed
