### ISSUE TITLE
adopt me button hover effect

### ISSUE THREAD

**Issue by avnigoyal25** [akshitagupta15june/PetMe#451]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by op-amateur** [comment]
Please assign me this issue, thank you.

**Comment by gitanushka** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by yashicagarg50** [comment]
Please assign me this issue under GSSoC'23

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by 000626574705** [comment]
I want to work on this issue as a contributor.
Pleasure Assign me.

**Comment by akshitagupta15june** [comment]
its completed
