### ISSUE TITLE
Readme updation

### ISSUE THREAD

**Issue by shraddha761** [akshitagupta15june/PetMe#455]
**
![image](https://github.com/akshitagupta15june/PetMe/assets/106100728/103b7a19-e54b-440b-a5d9-48decfc1b8f5)

adding this image in readme make it more attractive please assign me this issue under GSSOC'23

**Comment by Anjali2312-Thombare** [comment]
Hello @shraddha761 ,
I would like to solve this issue. Can you please assign me this issue ?

**Comment by shraddha761** [comment]
@Anjali2312-Thombare I am not owner of this repo

**Comment by akshitagupta15june** [comment]
its currently not needed for website
