### ISSUE TITLE
[FEAT]Adding a new page "Guide for Pet Parents" 

### ISSUE THREAD

**Issue by NehaKariya0309** [akshitagupta15june/PetMe#456]
Feature Request:
There can be many doubts in a person's mind before adopting a pet. A well structured guide page would help them in this regard.

Suggestion:
A page "Guide for Pet Parents" can be included. This page would contain guidelines for taking care of pets. While this may differ for pet to pet, a general guideline can be provided for dogs,cats,parrots and rabbits (most common pets) .

I am interested to work for this issue. I am a GSSoC'23 contributor. 

Thanks and regards,
Neha Kariya

**Comment by rafiya2003** [comment]
can you please assign me this issue under GSsoc'23

**Comment by VC6378** [comment]
Hey,
I am interested to be part of this idea, please assign me this issue.
Thanks and Regards,
Vibhuti Chandrakar.

**Comment by Naincy04** [comment]
Hello, I'm a contributor to GSSoc'23 and I want to work on this issue. Can u please assign this issue to me?

**Comment by akshitagupta15june** [comment]
its currently not needed for website
