### ISSUE TITLE
Enable lazy loading to improve website performance

### ISSUE THREAD

**Issue by M-A-N-I-K** [akshitagupta15june/PetMe#457]
Lazy loading is a technique that can be used to improve the performance of a website by delaying the loading of images and other resources until they are needed. This can help to reduce the initial load time of a page, which can improve the user experience and make the website more responsive.

The benefits of lazy loading include:

-     Reduced initial load time
-     Improved user experience
-     More responsive website
-     Increased SEO ranking

**Comment by akshitagupta15june** [comment]
its currently not needed for website
