### ISSUE TITLE
New feature which helps in fining the people willing to donate in the nearest distance of the adopter[GSSOC'23]

### ISSUE THREAD

**Issue by Nagapadmini7** [akshitagupta15june/PetMe#458]
As a pet lover, I've always wanted to adopt a pet, but one of the major challenges I had was learning the precise location of the adoption or finding the person who is willing to adopt in my closest locality.

**Problem with the present project**: The current project has a problem in that it only displays the state or city where the pet is currently up for adoption. 

**Solution**: We can provide a new feature that allows potential adopters to view the available pets in their immediate area as well as their options.

**Advantage:**The advantage of this function is that it takes rid of the adopter's laziness and the thought, "Will I Have to Go This Far to Adopt?" It also makes it possible for the donor to view the pet after adoption if it is taken in within walking distance.
 I am interested to work for this issue. I am a GSSOC'23 Contributor.

**Comment by akshitagupta15june** [comment]
its currently not needed for website
