### ISSUE TITLE
Improve Icon of theme in navbar change by giving it some shadowing effect on hovering as on other as other navbar texts are

### ISSUE THREAD

**Issue by shuklabhisekh** [akshitagupta15june/PetMe#459]
**Is your feature request related to a problem? Please describe.**
I think giving a shadow effect or highlighting the theme Icon in Navbar on hover will be improving the user interface as all other things emphasize the navbar on hovering.

**Describe the solution you'd like**
I would either give a box shadowing or will the icon with some color match with the navbar on hovering as other items are.

**Describe alternatives you've considered**
 I would give a shadowing effect by hovering on the theme Icon which will let the user know that it's working as other navbar links and will look pleasing from the user's perspective.

**Additional context**
Please Assign me this Issue so that I can work on this and make the UI look more pleasing as per User's perspective and contribute in @GSSOC'23.  
Currently, theme Icon looks like this on hovering - 
![Screenshot (209)](https://github.com/akshitagupta15june/PetMe/assets/95949460/bda3a4b4-f5eb-4296-9c08-2c7848486cc9)
After adding the shadowing effect the theme Icon will look something like this on hovering-
![image](https://github.com/akshitagupta15june/PetMe/assets/95949460/12ff9539-dea0-4e82-a4ea-ec5ebb24724d)

**Comment by akshitagupta15june** [comment]
its currently not needed for website
