### ISSUE TITLE
improve the spacing between the cards in home page

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#46]
![image](https://user-images.githubusercontent.com/57909583/192445883-9611a5d5-c848-44bb-8282-127371d5f2ba.png)

**Comment by Mustafa-Azad025** [comment]
hey , Please Assign This Task to me.

**Comment by DugarRishab** [comment]
hey, can I take this up?

**Comment by akshitagupta15june** [comment]
according to fcfs assigning this issue to @Mustafa-Azad025 

@DugarRishab you can look at other issues

**Comment by Mustafa-Azad025** [comment]
Will This Contribution Adds In Hacktoberfest 2022

**Comment by akshitagupta15june** [comment]
If you give the pr after 1st oct then it will count

**Comment by Mustafa-Azad025** [comment]
Ok So I Will Raise PR Again By Adding Screenshot Of The Changes .

**Comment by Mustafa-Azad025** [comment]
Hey @akshitagupta15june ,
I have raised PR please merge it.

**Comment by Mustafa-Azad025** [comment]
hey @akshitagupta15june ,
please approved this as a quality contribution for hacktober fest.

**Comment by akshitagupta15june** [comment]
I already did merge it

**Comment by Mustafa-Azad025** [comment]
Ok but i haven't receive any message from hacktoberfest as approved.
For earlier contribution I received message that why i am asking

**Comment by akshitagupta15june** [comment]
You will not receive notifications on Every contribution
Only in first and fourth pr

**Comment by Mustafa-Azad025** [comment]
Oh ok 😊
