### ISSUE TITLE
Contact us page 'name' field improved

### ISSUE THREAD

**Issue by kasturimandlik** [akshitagupta15june/PetMe#460]
In the contact us form present in the website the name field is not compulsory. 
The name field should be made compulsory. I would like to work on thus issue. 
Please assign me this issue under GSSOC'23.
@akshitagupta15june

**Comment by rafiya2003** [comment]
can you please assign me this issue under GSsoc'23

**Comment by 000626574705** [comment]
i want to work on this issue plz assign me that

**Comment by akshitagupta15june** [comment]
contributor are working on it
