### ISSUE TITLE
Image Upload Bug in  server/controllers/petController.js

### ISSUE THREAD

**Issue by M0hitSingh** [akshitagupta15june/PetMe#465]
**Describe the bug**
There is no Proper uploading of image in AddPet API
**To Reproduce**
1. Go to 'server/controllers/petController.js'
2. On Line No 8
3 See error

**Expected behavior**
We have to use Multer or any other file/image upload service, we cant retrieve image from image.body

**Comment by M0hitSingh** [comment]
Hey @akshitagupta15june if you think it is bug to solve 
then I can solve this issue for my GSSOC'23 contribution

**Comment by akshitagupta15june** [comment]
contributor are working on it
