### ISSUE TITLE
Adding a newsletter featuring all the available pets to all the users who subscribe!

### ISSUE THREAD

**Issue by anan262** [akshitagupta15june/PetMe#475]
Yeahh,some pets might be available and not adopted for a long time and some specific people might be searching for the same and I would like to mitigate this problem by cvreating newletters every month which would also increase the popularity of the website!

A newsletter goes to the emails of all those people that subscribed and this way we can also promote the company and also showcase the available pets to all the people around!

Interesting alternative would be to send mails periodically to the customers and the subscribers to visit the website!

I'm Ananya, a GSSOC contributor and would like to work on the same!

**Comment by Peacesandy** [comment]
Please assign me this issue as GSSOC 23
