### ISSUE TITLE
Make the adopt me button more attractive with effects.

### ISSUE THREAD

**Issue by Divyanshu24** [akshitagupta15june/PetMe#478]
**Is your feature request related to a problem? Please describe.**
When I visited the website i have seen that the adopt me button is less attractive and i think it cannot catch the attention of visitor.

**Describe the solution you'd like**
I can change the button and add effects that it can attract user's attention

**Comment by Anjali2312-Thombare** [comment]
Hey @Divyanshu24  I would like to solve this issue Please assign me this issue

**Comment by 000626574705** [comment]
i want to work on adopt button so please assign me that

**Comment by 766athul** [comment]
Hey Athul here . I would like to fix this issue under GSSoC'23  . I have the required knowledge and experience to solve this issue efficiently . I will not disapoint you  .

**Comment by yaminimasand** [comment]
I can work on this issue and make the adopt me button more catchy and attractive. Kindly assign it to me.
Regards

**Comment by Adityakumarsinghstm** [comment]
I can make the adopt me button more attractive.
please assign this issue to me so that i can show my skills. I am a contributor under GSSoC'23.

**Comment by laibaahsan27** [comment]
![image](https://github.com/akshitagupta15june/PetMe/assets/123810454/1eae8871-7e10-438d-a7f6-3721c2b41cb6)
![image](https://github.com/akshitagupta15june/PetMe/assets/123810454/a1644ca4-d113-4d01-be16-9c1b0338452f)
![image](https://github.com/akshitagupta15june/PetMe/assets/123810454/97a4df4c-d5a9-49e0-9a3d-a21a2a67f0ee)
![image](https://github.com/akshitagupta15june/PetMe/assets/123810454/91edaa62-13f7-497d-b460-2a2aea9ed218)



I can change the css of "adopt me" button by making it look like the above button on the snapshots of your choosing. I will add hover to the button which will fill up with colour when you scroll on it. I will customize the colour of the button according to the colour scheme of your website. 
This will make the "adopt me" button look more appealing and aesthetically pleasing.

Allow me make these changes by assigning this issue to me under the label of GSSOC 2023

**Comment by akshitagupta15june** [comment]
its completed
