### ISSUE TITLE
 Want  to add carousel  into a front page

### ISSUE THREAD

**Issue by HimanshuNarware** [akshitagupta15june/PetMe#480]
I want to add a carousel on the front page to  improve the user experience

**Describe the solution you'd like**
On the front page their only one image of dogs  we can use a carousel  to show different pets on the front page

**Additional context**

![slideshow](https://github.com/akshitagupta15june/PetMe/assets/83147410/77315083-86f4-4f11-ad2b-8996282962f8)

**Comment by ePSA-eJya** [comment]
i would also want to contribure here

**Comment by akshitagupta15june** [comment]
contributor are working on it
