### ISSUE TITLE
Adjusting the bg image with 3 dogs

### ISSUE THREAD

**Issue by laibaahsan27** [akshitagupta15june/PetMe#481]
**Describe the bug**
The background image of the landing page with contains 3 dogs is not fitting the spcae meant for it and there is a blank space left out at the bottom of the image.

**To Reproduce**
1. Go to 'your website'
2. Scroll down to 'just above "about"'
3. See error

**Expected behavior**
The white space should not be showing.

**Screenshots**
![image](https://github.com/akshitagupta15june/PetMe/assets/123810454/d7825d53-564f-4a76-a15c-b5bd0da9862d)

**Additional context**
@akshitagupta15june  Allow me to fix this issue by assigning this task to me under the label of GSSOC 2023

**Comment by Anjali2312-Thombare** [comment]
Hi @laibaahsan27  
I will adjust the background with 3 dogs . Please assign me this issue;
