### ISSUE TITLE
Back to top button

### ISSUE THREAD

**Issue by Soumyajit2825** [akshitagupta15june/PetMe#482]
**Describing the feature**
There is no button in the website by which we can come back to top of the website.

**Solution**
I want to add a button which will work in the website and which will help all the users to quickly go back to the top of the website

**Benefits**

- It will help users to back to the top of the website quickly
- Website will be more user-friendly

**ScreenShot**
![Screenshot 2023-05-22 004933](https://github.com/akshitagupta15june/PetMe/assets/100519291/3cef84e3-1e5f-458a-8800-a0d9f812207e)

**Additionally**
I would like to change the position of the SOS button from whole website to stick on the navbar and I want to add the back to top button in the position of the SOS button

Please let me know if any chnages are needed in my planning
Thank you

**Comment by Priyanshsri** [comment]
Hey can I also contribute to this issue ?

**Comment by ePSA-eJya** [comment]
i would also want to contribute here. please assign this issue to me.

**Comment by akshitagupta15june** [comment]
already present
