### ISSUE TITLE
People experiences after adoption in the form of corousel

### ISSUE THREAD

**Issue by An525ish** [akshitagupta15june/PetMe#483]
**Is your feature request related to a problem? Please describe.**
I would like to introduce a people experience section above contact us section in the form of a carousel

**Describe the solution you'd like**
A well-designed carousel to show the genuinity of the service which will lead to more traffic 

**Describe alternatives you've considered**

**Additional context**

**Comment by akshitagupta15june** [comment]
its not currently needed for website
