### ISSUE TITLE
Add FAQs section above Contact Us section

### ISSUE THREAD

**Issue by itsaakashpatel** [akshitagupta15june/PetMe#484]
**Is your feature request related to a problem? Please describe.**
I believe we should add a FAQ section just above the contact us section. As a first-time user, I don't have much idea about the initiative and project. Adding some frequently asked questions and answers would help the visitors.

Something like this:
<img width="948" alt="image" src="https://github.com/akshitagupta15june/PetMe/assets/20282826/cbed9196-185f-452f-a598-8de3f735fbe2">

**Describe the solution you'd like**
I would like to add a FAQ section after deciding on frequently asked questions and their answers. I can build APIs in Node Js and FAQ section on the site.

**Describe alternatives you've considered**
- Maybe a dedicated FAQs Page.

**Additional context**

I would love to contribute as part of GSSOC'23.

Thank you!

**Comment by Apreksha** [comment]
Hey, I'm a GSSoCC'23 contributor. I would like to add FAQs section above Contact us section. Could you please assign this task to me.
