### ISSUE TITLE
No Proper visibility of Scroll to Top icon in Blog page

### ISSUE THREAD

**Issue by krushn-a** [akshitagupta15june/PetMe#488]
**Describe the bug**
When you navigate to the blog page. At the Bottom left corner, there is Scroll to the top icon which is not visible due to the image used here.
It is visible only when the browser is in dark mode making it difficult to be seen in light mode.
Another Problem is, it is shown as list due to which a black disk appears beside the icon.

**To Reproduce**
1. Go to 'Blogs'
2. Navigate to the bottom of the page.
3. beside the black dot Scroll to the top icon is present

**Expected behavior**
   The icon should be visible in both light and dark mode.

**Screenshots**
   
![2023-05-22 (1)](https://github.com/akshitagupta15june/PetMe/assets/111559776/653c2a6b-f447-4d46-9f5b-68acd74e2641)
In dark mode

![2023-05-22](https://github.com/akshitagupta15june/PetMe/assets/111559776/2fbf666c-a3f6-4505-9e46-9f4c9f837f07)
In light mode

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Comment by Apreksha** [comment]
Hey, I'm a GSSoCC'23 contributor. I would like to add proper visibility of scroll to top button in blog page. Could you please assign this task to me.

**Comment by akshitagupta15june** [comment]
already present in website
