### ISSUE TITLE
styling to 'Adopt me' button and page button visible on a particular page

### ISSUE THREAD

**Issue by Sanju-Gautam0855** [akshitagupta15june/PetMe#492]
**Is your feature request related to a problem? Please describe.**
The Adopt Me button is not clear as the colour contrast is not matching with the UI of the website. And when we go to a particular page like Pet News, Blogs, or Donate Animals .... the page heading doesn't get highlighted and we didn't know which we are on which page. 

**Describe the solution you'd like**
I want to add some styling to the Adopt Me button and the page heading should remain highlighted as long as we are on that particular page so that we know we are on which page.

**Describe alternatives you've considered**
Adopt Me button should be visible clearly and the page heading should be highlighted.

**Comment by akshitagupta15june** [comment]
already present
