### ISSUE TITLE
Slideshow of rescued/adopted animals on the main page

### ISSUE THREAD

**Issue by shubhangi-hash** [akshitagupta15june/PetMe#495]
A slideshow of pictures of the adopted/rescued animals on the main page will increase the engagement of the users. Makes the website look more authentic

**Comment by Apreksha** [comment]
Hey, I'm a GSSoCC'23 contributor. I would like to add slideshow of rescued/adopted animals on the main page. Could you please assign this task to me.

**Comment by Adityaprakash754** [comment]
Hello, I'm a contributor to GSSoc'23 and I want to work on this issue. Can u please assign this issue to me?

**Comment by P00NAM** [comment]
I want to contribute in this issue, please assign me.

**Comment by akshitagupta15june** [comment]
its not currently needed for website
