### ISSUE TITLE
Adding hover effect to social media links.

### ISSUE THREAD

**Issue by titaskundu** [akshitagupta15june/PetMe#497]
After reviewing the website, I think it will be better to add a small hover effect like turning the icon in blue to help users understand which social media icon to click. Please assign me to this issue I am a Gssoc contributor.
![Screenshot (570)](https://github.com/akshitagupta15june/PetMe/assets/123840507/c1ffa1f5-ffec-426a-a6bc-f907c3aadf24)

**Comment by Peacesandy** [comment]
Please assign me this issue as GSSOC 23
