### ISSUE TITLE
scrolling effect when we click on Home, Pet News etc.

### ISSUE THREAD

**Issue by Sanju-Gautam0855** [akshitagupta15june/PetMe#498]
**Is your feature request related to a problem? Please describe.**
When we scroll down the website and want to go to the beginning of the page, we click on the home page and the website gets refreshed. 

**Describe the solution you'd like**
When I am on the bottom of the page and want to go up by clicking the Home button, I go fast and smoothly, scrolling over the content I have read.

**Describe alternatives you've considered**
When we click on home page, the website gets refreshed and takes some time which can have a negative impact on the user if we add the scrolling effect the time it takes in getting refreshed will be covered by the time it takes to get to the top of it.

**Additional context**
If I assign this I can show the changes I want.

**Comment by akshitagupta15june** [comment]
its completed
