### ISSUE TITLE
[GSSOC'23] Restricting Contact Us Form to Accept Only String Values for Name Field

### ISSUE THREAD

**Issue by purviporwal0** [akshitagupta15june/PetMe#501]
the contact us form should only accept name if it is a string 
![Screenshot (9)](https://github.com/akshitagupta15june/PetMe/assets/116807722/e99be92d-a05a-46a7-a305-8869459d08f2)

**Comment by ks20soni** [comment]
This form can also be made to route to another page instead of being part of the home page, as it makes the home page look messed up. I wish to work on this part. Can you please assign this issue to me?

**Comment by kushagra-goyal-14** [comment]
please assign me this issue

**Comment by akshitagupta15june** [comment]
contributor are working on it
