### ISSUE TITLE
Want to style the "adopt me" button

### ISSUE THREAD

**Issue by shineishukla** [akshitagupta15june/PetMe#502]
**Is your feature request related to a problem? Please describe.**
Yes, the "adopt me" button is not looking good and has no style.

**Describe the solution you'd like**
Styling the button to suit your website.

**Describe alternatives you've considered**
Custom background and border styles, Toggle buttons, Icon buttons

**Additional context**

**Comment by sukanyachopra** [comment]
Please allow me to contribute to this issue as GSSOC Contributor.
