### ISSUE TITLE
[GSSOC'23]Add hover to social media links in footer

### ISSUE THREAD

**Issue by purviporwal0** [akshitagupta15june/PetMe#503]
I want to add hover to social media links in the footer 
![Screenshot (10)](https://github.com/akshitagupta15june/PetMe/assets/116807722/f2d7c30e-716e-472f-8b4a-603d8dadc8a4)

**Comment by tyagipriyanshi79** [comment]
Can you please assign this issue to me. I was able to do it

**Comment by ks20soni** [comment]
I wish to work on this issue to make the social media links more lively; I also plan to add some transition property to make the website footer look more attractive. Can you please assign this issue to me?

**Comment by P00NAM** [comment]
please assign me this issue

**Comment by Peacesandy** [comment]
Please assign me this issue as GSSOC 23

**Comment by akshitagupta15june** [comment]
currently no social media page of petme
