### ISSUE TITLE
[GSSOC'23] Make the about us section more attractive 

### ISSUE THREAD

**Issue by purviporwal0** [akshitagupta15june/PetMe#504]
The about us section could be made more attractive by using CSS .
![Uploading Screenshot (11).png…]()

**Comment by Priyanshsri** [comment]
i also want to contribute

**Comment by ks20soni** [comment]
The about us section seems dull and merges with the next section in a very non-appealing way. I plan to make it attractive and merge it cleanly with the next section. Can you please assign this issue to me?

**Comment by akshitagupta15june** [comment]
contributor are working on it
