### ISSUE TITLE
improve tha UI of blog section 

### ISSUE THREAD

**Issue by anjaliSilawat** [akshitagupta15june/PetMe#505]
I want to improve the UI of blog section @akshitagupta15june please assign it to me 
![image](https://github.com/akshitagupta15june/PetMe/assets/108583230/9c18bc7e-f091-4b2f-9d5d-cdd3bfd941f2)

**Comment by Priyanshsri** [comment]
i would like to contribute pls add me

**Comment by akshitagupta15june** [comment]
contributor are working on it
