### ISSUE TITLE
Improve "Adopt Your Favourite Pet" page

### ISSUE THREAD

**Issue by rishuraj1** [akshitagupta15june/PetMe#508]
I strongly believe that the "Adopt Your Favourite Pet" page needs a revamp, the bg image is good but the form does not look appealing and it needs additional designs.

Current:
![Screenshot (103)](https://github.com/akshitagupta15june/PetMe/assets/47839626/d07b4bb9-7cad-4a6d-b61b-5cbe111240f2)

We can make it more attractive by incorporating simpler and modern form as shown in the image below, It follows overall theme and coloring of the website as well as looks appealing too. 
We can also modify the contents of the form by adding some cool svgs instead of classic text.

proposed idea: 
![Screenshot (104)](https://github.com/akshitagupta15june/PetMe/assets/47839626/c686d195-a858-404e-92d9-84f1b16a49b3)

As I would really love to contribute to this wonderful project, can you please assign me this task under GSSoC '23. Thank You!

**Comment by akshitagupta15june** [comment]
go for it
