### ISSUE TITLE
Footer section should be interactive

### ISSUE THREAD

**Issue by PritamSarbajna** [akshitagupta15june/PetMe#51]
## Footer should be interactive when hovering

![Screenshot (219)](https://user-images.githubusercontent.com/90236635/192700235-eefe8ea9-abdd-4b75-a23b-ff072f23cfd1.png)

**I can fix this issue if assigned [For [HACKTOBERFEST '22]**

**Comment by akshitagupta15june** [comment]
Cool you can work on it

**Comment by PritamSarbajna** [comment]
Hey @akshitagupta15june is this fine if I make a PR after hacktoberfest starts ?

**Comment by akshitagupta15june** [comment]
Yes fine
