### ISSUE TITLE
Add a about us section in website 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#52]

**Comment by sambhavgupta0705** [comment]
Hey ,I can work on this issue,please assign it to me

**Comment by akshitagupta15june** [comment]
As you are already working on an issue so let's other work on it

**Comment by yadavsairaj** [comment]
Hey can i work on this issue?

**Comment by omk-coder** [comment]
Hey can I work on this issue.??

**Comment by avezqureshi14** [comment]
hey please @akshitagupta15june mam can you assign me this issue

**Comment by akshitagupta15june** [comment]
Assigning to @omk-coder

**Comment by omk-coder** [comment]
thanks.

**Comment by sambhavgupta0705** [comment]
> As you are already working on an issue so let's other work on it

ok no issues
