### ISSUE TITLE
Add hover effect on social media icons. 

### ISSUE THREAD

**Issue by ePSA-eJya** [akshitagupta15june/PetMe#522]
**Is your feature request related to a problem? Please describe.**
Social media icons remain still.

**Describe the solution you'd like**
Adding hover effects would enlarge the icons and change color.

I'm a GSSoCC'23 contributor. please assign this issue to me @akshitagupta15june

**Comment by ePSA-eJya** [comment]
I'm a GSSoCC'23 contributor.  please assign this issue to me @akshitagupta15june

**Comment by Aditi323** [comment]
Could you please assign me this as a GSSOC Contributor.

**Comment by Mittalkashish** [comment]
i want to work on this issues  as GSSOC Contributor , i had already work on this type of  issue on my own project

**Comment by sukanyachopra** [comment]
I can contribute towards this issue as GSSOC Contributor.

**Comment by P00NAM** [comment]
please assign me this issue as GSSOC'23

**Comment by Peacesandy** [comment]
Please assign me this issue as GSSOC 23

**Comment by SakshiRawat13** [comment]
Is your feature request related to a problem? Please describe.
Social media icons remain still. This is how it looks right now
![image](https://github.com/akshitagupta15june/PetMe/assets/97942987/d920b718-ee47-43a8-8f10-ac066417cbe5)


Describe the solution you'd like
Adding hover effects would make the section more attractive.

Screenshot:
![image](https://github.com/akshitagupta15june/PetMe/assets/97942987/1cbe2f06-a003-4ed3-bea6-aa737f451ea6)

On hovering the bg color changes and the icons turn white :
![image](https://github.com/akshitagupta15june/PetMe/assets/97942987/0b990442-f213-496e-aa66-c58ef38f4e91)


I'm a GSSoCC'23 contributor. Please assign this issue to me @akshitagupta15june

**Comment by P00NAM** [comment]
okay
