### ISSUE TITLE
map link for the location icon, 

### ISSUE THREAD

**Issue by ePSA-eJya** [akshitagupta15june/PetMe#523]
**Is your feature request related to a problem? Please describe.**
the location icon on the home page.

**Describe the solution you'd like**
Clicking the location icon could open the map estimation the nearest adoption centre.

**Additional context**
![image](https://github.com/akshitagupta15june/PetMe/assets/120899038/e2a5c4ef-ef62-4d99-9d3b-0aec391f5f68)

I'm a GSSoCC'23 contributor.  please assign  this task to me @akshitagupta15june

**Comment by ePSA-eJya** [comment]
I'm a GSSoCC'23 contributor.  Clicking the location icon could open the map estimation the nearest adoption centre. please assign  this task to me @akshitagupta15june

**Comment by Gauravmauryaios** [comment]
I am a GSSoC'23 contributor. I have all the skills required. Please assign me this issue, I want to work on this issue under the GSSoC'23

**Comment by akshitagupta15june** [comment]
its not currently needed for website
