### ISSUE TITLE
After submitting the form, the form content does not get cleared. 

### ISSUE THREAD

**Issue by ePSA-eJya** [akshitagupta15june/PetMe#525]
**Describe the bug**
After submitting the form, the form content does not get cleared. it will be very tedious for the user if he want to fill another form. he will have to clean the entire form before submitting a new response.

**To Reproduce**
1. Go to 'donate animas'
2. fill form
3. Submit and return

**Expected behavior**
A new form available.

I am a GSSOC'23 contributor. let me fix this issue. @akshitagupta15june

**Comment by ePSA-eJya** [comment]
it will be very tedious for the user if he want to fill another form. he will have to clean the entire form before submitting a new response. I am a GSSOC'23 contributor. let me fix this issue. @akshitagupta15june

**Comment by sukanyachopra** [comment]
I want to work on this issue. Can you please assign me this issue?

**Comment by akshitagupta15june** [comment]
its not currently needed for website
