### ISSUE TITLE
3-4 separate button for different types of animals in meet my friends section of Home page

### ISSUE THREAD

**Issue by DeepikaChauhan09** [akshitagupta15june/PetMe#526]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

In Meet our friend section of the Home Page, all types of animals are given at the same place. we can make buttons and add data of different types of animals over there. Like in the Dog button, all available dogs will come, similarly in the Cat button all cats, in the Birds button all birds, and in the Cow button all cows. and we make 1 button -others. In this, all other animals which are less likely to adopt as pets like rabbits, tortoises, etc will come. 

This will make page more user friendly

**Comment by Aditi323** [comment]
Could you please assign me this as a GSSOC Contributor.
