### ISSUE TITLE
Name input field allow only characters not numbers. So that won't create any problem in database

### ISSUE THREAD

**Issue by DeepikaChauhan09** [akshitagupta15june/PetMe#527]
**Describe the solution you'd like**
Name input in all forms must be restricted to characters only. so that it will not create problem on backend side in database while storing it. so that database won't be corrupt. Right now name field is accepting both characters and digits.

Please assign this issue to me @akshitagupta15june

**Comment by akshitagupta15june** [comment]
its not currently needed for website
