### ISSUE TITLE
Blog and Pet news Page need  to be more user friendly

### ISSUE THREAD

**Issue by DeepikaChauhan09** [akshitagupta15june/PetMe#529]
Blog and Pet news Page need to be more user-friendly. For this, we can make changes in the background and more content can be added

Please assign me this issue @akshitagupta15june

**Comment by Aditi323** [comment]
Could you please assign me this as a GSSOC Contributor.

**Comment by Peacesandy** [comment]
I'm interested in improving the page and adding more features
