### ISSUE TITLE
Add hover effect on Adopt me Button in home page

### ISSUE THREAD

**Issue by dc9deepika** [akshitagupta15june/PetMe#531]
Please assign this to me @akshitagupta15june

**Comment by SakshiRawat13** [comment]
Please assign this issue to me @akshitagupta15june

**Comment by Himanshi1207** [comment]
I can work on the issue could you please assign it to me under GSSoC'23.

**Comment by Peacesandy** [comment]
I can work on this please assign this issue to me GSSOC 23
