### ISSUE TITLE
navbar of the page that opened on clicking adopt me button is not displaying properly.

### ISSUE THREAD

**Issue by Chhavi-Adlakkha** [akshitagupta15june/PetMe#534]
page that opened on clicking adopt me button is not displaying perfectly.
the navbar is just displaying vertically and the icons are getting larger.

1. Go to meet your friend section
2. Click on Adopt Me button
3. See error

![petme error](https://github.com/akshitagupta15june/PetMe/assets/125033137/543f1156-4655-4a1c-a37c-1bc5dff5597d)

hey !
As a freind of animals and also being a  pet guardian🐶 I would really like to contribute in this project.
contributor gssoc2023
kindly  please assign this issue to me  @akshitagupta15june .

**Comment by Aditi323** [comment]
Could you please assign me this as a GSSOC Contributor.
