### ISSUE TITLE
[GSSoC'23] Improving the UI of Pet News

### ISSUE THREAD

**Issue by nishita2104** [akshitagupta15june/PetMe#535]
The pet news page can be made to look more organised and attractive by adding in a card style UI. This way the title, photo and body of the article would be easily readable. 
Please assign me this issue under GSSoC'23.

**Comment by Aditi323** [comment]
Could you please assign me this as a GSSOC Contributor.

**Comment by Peacesandy** [comment]
Please can you assign me this issue as a GSSOC contributor

**Comment by Pv200** [comment]
plz assign it to me, i have commited some changes in news page, it looking like this

https://github.com/akshitagupta15june/PetMe/assets/117562053/6e3654fc-491f-452d-a580-018ba5687047

![Screenshot 2023-05-23 121622](https://github.com/akshitagupta15june/PetMe/assets/117562053/c94cb197-b704-45b0-9528-5721d20092bb)
