### ISSUE TITLE
[GSSoC'23] Improving UI of Adopt me button

### ISSUE THREAD

**Issue by nishita2104** [akshitagupta15june/PetMe#536]
Right now the adopt me button is very basic. It could be improved so as to match to the site's UI.
Please assign this to me under GSSoC'23.
![image](https://github.com/akshitagupta15june/PetMe/assets/98174888/3b52604d-7e4a-4bb6-aa9d-ef95f9b2244c)

**Comment by Aditi323** [comment]
Could you please assign me this as a GSSOC Contributor.

**Comment by Peacesandy** [comment]
I'll like to be assigned this task as a Girl script summer of code contributor
