### ISSUE TITLE
Improved Pet Cards

### ISSUE THREAD

**Issue by Arka90** [akshitagupta15june/PetMe#537]
Design can be Improved also the Button for "Adopt me" is not visible

**Expected behavior**
The cards can be Improved

**Screenshots**
![Capture](https://github.com/akshitagupta15june/PetMe/assets/64225385/1a1e4cbc-3af6-4421-a63b-4bbf42abd5d4)

**Desktop :**
 - OS: Windows
 - Browser [Chrome , Firefox]

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 7 Pro]
 - OS: [Android]
 - Browser [Chrome]

**Comment by dhruv18ranjan** [comment]
hey @Arka90  i would like to work on this issue can you assign me

**Comment by Mittalkashish** [comment]
i want to work on this issue , i can make card attractive looking

**Comment by ptharshit** [comment]
I want to work on this issue under GSSoC'23. Please assign me this.

**Comment by JasnoorMaan** [comment]
The content alignment in the cards can be improved. I can help with this issue under gssoc23

**Comment by akshitagupta15june** [comment]
its not currently needed for website
