### ISSUE TITLE
Making the contributors list attractive.

### ISSUE THREAD

**Issue by saiwali** [akshitagupta15june/PetMe#538]
**Is your feature request related to a problem? Please describe.**
The list of contributors can be presented in an attractive manner. The present UI does not fit with the other parts of the website.

**Describe the solution you'd like**
Circular images for contributors images can be applied with beautiful designs.

**Describe alternatives you've considered**
Even a carousel can be used to demonstrate contributors' images.

**Additional context**

**Comment by saiwali** [comment]
Hello @akshitagupta15june, I think the above changes can make the website look more attractive.  Could you please assign this issue to me under GSSOC'23?

**Comment by akshitagupta15june** [comment]
its not currently needed for website
