### ISSUE TITLE
Add a contributors section in the bottom of website 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#54]

**Comment by laxmanbalaraman** [comment]
Hey @akshitagupta15june ! I would like to work on this issue. Can you assign this to me?

**Comment by laxmanbalaraman** [comment]
@akshitagupta15june, I did some research and this could be easily be implemented using github's [API](https://docs.github.com/en/rest/repos/repos#list-repository-contributors). Would love to work on this one as a part of my hacktoberfest 😄 !

**Comment by akshitagupta15june** [comment]
@laxmanbalaraman awesome go for it 👍

**Comment by Anuran12** [comment]
hey @akshitagupta15june can you please assign it to me. I already did this type of contribution so it's easy for me

Thanks : )

**Comment by laxmanbalaraman** [comment]
Hey @Anuran12, I am assigned and already working on it for my hacktoberfest. Request you to kindly find some other issue. Thanks.

**Comment by Anuran12** [comment]
Okay : )
I am also participating hacktoberfest...
Okay if you need any help in this you can ask me

**Comment by laxmanbalaraman** [comment]
@akshitagupta15june, I have done the contributors section. Contributors get dynamically added as they contribute to the repo. Also, it would look responsive in the mobile version as well. Clicking on any of the contributor's DP will take them to their profile. Hovering over DP will show them their name.

Tell me if everything looks fine.

![contributors-desktop](https://user-images.githubusercontent.com/67074796/193215954-2abc0475-fc9a-4521-8da4-c7ca766f47cb.jpg)

**Comment by akshitagupta15june** [comment]
That is so great👍👍
Well done
Try to give pr tomorrow

**Comment by laxmanbalaraman** [comment]
Thanks! 😄 
Sure, I will!
