### ISSUE TITLE
[GSSoC'23] Fix: Adding Footer  in Pet News page

### ISSUE THREAD

**Issue by davidkilamlya** [akshitagupta15june/PetMe#546]
Hi @akshitagupta15june,  am david from GSSoS'23 our Pet News have no footer I hope we should add it for better user experience

**Comment by sukanyachopra** [comment]
I can work on this. I have really awesome idea for the footer. Please assign me this as GSSOC Contributor

**Comment by P00NAM** [comment]
please assign me this issue, I really want to contribute in this beautiful project because with this project we can provide  better life for pets. I can make easy for users to contact with the help of footer .

**Comment by P00NAM** [comment]
please assign me this issue, I really want to contribute in this beautiful project because with this project we can provide  better life for pets.

**Comment by akshitagupta15june** [comment]
its not currently needed for website
