### ISSUE TITLE
[GSSOC'23] Needs to improve nav bar of this site

### ISSUE THREAD

**Issue by iam-ravi-12** [akshitagupta15june/PetMe#547]
**Is your feature request related to a problem? Please describe.**
This website's simple navigation bar is incredibly boring to look at.

**Describe the solution you'd like**
Add some css and come color gradient to look an attractive nav bar

**Additional context**

![Screenshot 2023-05-23 000135](https://github.com/akshitagupta15june/PetMe/assets/79560130/ca27055b-262e-4cd0-a864-61a337e931d0)

**Comment by iam-ravi-12** [comment]
I want to work on this issue to resolve it and make this site navbar attractive.

**Comment by Himanshi1207** [comment]
I can make this navbar look more attractive could you please assign it to me it will be my first contribution under GSSOC'23

**Comment by ptharshit** [comment]
I want to work on this issue under GSSoC. Please assign me this.

**Comment by VishalJx** [comment]
Greeting,
I would like to help adding and improving overall UI of navbar of this project. Kindly assign me this task under GSSOC'23.
Thank You.

**Comment by akshitagupta15june** [comment]
contributors are working on it
