### ISSUE TITLE
[GSSoC'23] Fix: Blogs descriptions and images are not visible well (blurred) in mobile phones screens 

### ISSUE THREAD

**Issue by davidkilamlya** [akshitagupta15june/PetMe#548]
The issue can be due to excessive shadow and text color choosen

**Comment by rishabhchaudhary0210** [comment]
Hey @akshitagupta15june @davidkilamlya 
I'm a GSSOC'23 contributor and I would like to work on this issue.
I suppose this issue could be resolved by removing on hover css when in mobile view

**Comment by akshitagupta15june** [comment]
contributors are working on it
