### ISSUE TITLE
Add testimonial section

### ISSUE THREAD

**Issue by rishitachail** [akshitagupta15june/PetMe#552]
Is your feature request related to a problem? Please describe.
Yes, I would like to add a testimonial section to my website.

Describe the solution you'd like
I would like to have a testimonial section on my website where I can display testimonials from my customers. Each testimonial should include the customer's name, their testimonial message, and their profile picture.

Describe alternatives you've considered
I have considered manually creating a testimonial section by writing HTML and CSS code for each testimonial. However, this approach would be time-consuming and not scalable if I want to add or update testimonials in the future.

Additional context
I would like the testimonial section to have a clean and professional design that matches the overall style of my website. It would be great if the testimonial section is responsive and adjusts well on different devices.

**Comment by akshitagupta15june** [comment]
its not currently needed for website
