### ISSUE TITLE
UI enhancement of Cards of Blogs Page

### ISSUE THREAD

**Issue by MohitNamdev22** [akshitagupta15june/PetMe#559]
**Is your feature request related to a problem? Please describe.**
On the blogs page, cards can have better animation with the use of drop shadow, I can work on this under GSSOC '22.

**Screenshot**
![image](https://github.com/akshitagupta15june/PetMe/assets/89779447/61eb1e5a-cac5-4e75-b680-281b398831ea)

**Comment by khushi767** [comment]
hii...This blog page can be made more attractive ....please assign me this issue under gssoc'23

**Comment by MohitNamdev22** [comment]
@khushi767 Actually I'm already raised this particular issue and will work on it, it would be great if you raise something different issue.
