### ISSUE TITLE
Have a fixed navbar which makes it easy for the user to access the different tabs and doesn't need to scroll up

### ISSUE THREAD

**Issue by ani0722** [akshitagupta15june/PetMe#568]
<img width="1274" alt="Screenshot 2023-05-23 at 5 20 44 PM" src="https://github.com/akshitagupta15june/PetMe/assets/107585475/aab92770-e3d2-450c-b210-6d5a9d1f00c0">

THIS WEBPAGE  here can Have a fixed navbar which makes it easy for the user to access the different tabs and doesn't need to scroll up. 

The Adopt Me can also be hovered upon. so its more of a chance that the user might actually click on it. There is higher chances of the dog getting adopted then

**Comment by pjyoti121** [comment]
please assign me this issue

**Comment by PoulavBhowmick03** [comment]
it hasn't been done for 2 weeks. can it be assigned to me instead?

**Comment by ani0722** [comment]
https://github.com/akshitagupta15june/PetMe/pull/596#event-9329405491

PR accepted and closed
