### ISSUE TITLE
Add video of Petme website in the main readme

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#57]
here is the video link https://youtu.be/U1EQjtT-G8E

**Comment by Eyesnatcher-coder** [comment]
Hi👋 @akshitagupta15june , could you please elaborate me the issue....

**Comment by omthakare16** [comment]
Can I work on this issue, can you assign me ?

**Comment by akshitagupta15june** [comment]
Would you like to work on this?

**Comment by omthakare16** [comment]
Yes , I would like to work !

**Comment by akshitagupta15june** [comment]
ok @omthakare16

**Comment by omthakare16** [comment]
Can I embed the youtube video in readme or just provide the link ?

**Comment by akshitagupta15june** [comment]
you can embed it

**Comment by omthakare16** [comment]
Hey sorry for inconvenience ,  I have tried but it is not possible to embed the youtube video itself , So can I download and embed the video or should I provide youtube link ! ?
