### ISSUE TITLE
Improve in media queries in Pet News page

### ISSUE THREAD

**Issue by Pv200** [akshitagupta15june/PetMe#571]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Pv200** [comment]
News page is not that much responsive on mobile phone
i am attaching the image for your reference:
![WhatsApp Image 2023-05-23 at 19 14 57](https://github.com/akshitagupta15june/PetMe/assets/117562053/34777cd3-1ad9-4e7f-8e09-d72397b3a27b)

**Comment by akshitagupta15june** [comment]
contributors are working on it

**Comment by Pv200** [comment]
OK
