### ISSUE TITLE
Footer icon not redirecting to Home

### ISSUE THREAD

**Issue by SoundaryaKoutharapu** [akshitagupta15june/PetMe#572]
**Steps to reproduce the behavior:**
1. Go to 'blogs'
2. Scroll down to 'bottom'
3. Click on 'footer logo' 
4. It doesn't redirect to home page

I'd like to work on this issue, Could you please assign this issue to me under GSSOC'23.

https://github.com/akshitagupta15june/PetMe/assets/71914071/69dd172e-5842-4c47-98b5-08a7dbe04a06

**Comment by akshitagupta15june** [comment]
its not currently needed for website

**Comment by SoundaryaKoutharapu** [comment]
Okay fine!
