### ISSUE TITLE
Add a blog section in navbar-->blog.html

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#59]
on clicking blog it will take to a new blog.html

currently leave that page as blank

will decide further

**Comment by Arghya-Banerjee** [comment]
I can do this for you, please assign me this issue.

**Comment by shivamvishwakarm** [comment]
Hey akshitgupta i did it. I send you a PR

**Comment by akshitagupta15june** [comment]
@Arghya-Banerjee u are already working on an issue so lets give others a chance

**Comment by zugzwang03** [comment]
Can I work on this under Hacktoberfest'22?

**Comment by akshitagupta15june** [comment]
Yes @zugzwang03

**Comment by Yh010** [comment]
@akshitagupta15june I have sent a PR, pls review it

**Comment by akshitagupta15june** [comment]
This issue is assigned to @zugzwang03
