### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by narayan954** [akshitagupta15june/PetMe#6]
Website could use an awesome favicon , currently it doesn't have one.

**Comment by SushanthReddy-49** [comment]
I would like to work on this. Can you assign me?
@narayan954

**Comment by narayan954** [comment]
nope I can't @SushanthReddy-49

**Comment by SushanthReddy-49** [comment]
Ok @narayan954

**Comment by sambhavgupta0705** [comment]
hi, I want to work on this issue ,can you please assign it to me

**Comment by Pratham-19** [comment]
Hi can I work on it ?

**Comment by CodeWAdi** [comment]
I would like to work on this issue,can you please assign me

**Comment by akshitagupta15june** [comment]
This issue is completed
