### ISSUE TITLE
[BUG] FORM FIELDS ARE NOT CLEARED AFTER THE SUBMISSION FOR ALL THE FORMS

### ISSUE THREAD

**Issue by akhilender-bongirwar** [akshitagupta15june/PetMe#602]
**Describe the bug**
The contact us form in the main home page are having the previous entered data in the respective fields even after the submission of the form.

**To Reproduce**
1. Go to the Home page of the website
2. Scroll down to the contact us form
3.  Or else click on the contact us button present on the navabar
4. Now fill the required details in the form and submit the form. You will be navigated to thanks! form submitted successfully.
5. Then click on the Go back button.
6. You can see your filled details again present in the form. This is the error I want to fix.

**Expected behavior**
The expected behaviour is the form after submission should return an empty form again but not with the previous data present in it.

**Video of the error**
I would like to demonstrate the problem by attaching a small video of it.

https://github.com/akshitagupta15june/PetMe/assets/112749383/9e929922-570e-41b4-a4c8-45b9f3ff326d

**Approach to solve the issue**
I would like to change some javascript code for the proper functioning of the contact us form. Basically all the fields will get cleared and an empty form would be returned after the submission. Therefore increases the user experience.

**Update**
UPDATE: ALL THE FORMS HAVE THIS ISSUE AFTER SUBMISSION

1. Even the Donate Animals Form has the same above specified issue..
2. Become a Volunteer form has also the same above specified issue.
3. Even the SOS form.
I would like to work on all these issues. Please assign me.

**Comment by akhilender-bongirwar** [comment]
@akshitagupta15june, I would like to work on this issue if approved. Please assign me this issue.

**Comment by akhilender-bongirwar** [comment]
UPDATE: ALL THE FORMS HAVE THIS ISSUE AFTER SUBMISSION
1. Even the Donate Animals Form has the same above specified issue..
2. Become a Volunteer form has also the same above specified issue.
I would like to work on all these issues. Please assign me.

**Comment by Hritik1503** [comment]
I can solve this issue very easily and fast.Please assign this to me under GSSOC'23 so i can start working on this
