### ISSUE TITLE
Add a button in navbar 

### ISSUE THREAD

**Issue by Swapnil-2503** [akshitagupta15june/PetMe#617]
- Adding a button for meet our friends here for directly navigating in that place
- It will be easy for user to find pet that they wanted more easily

Assign this to me i am contributing under GSSOC'2023

**Comment by iamaashi23** [comment]
Till now there is no button that would navigate us to the place where we can actually adopt pets, i can add a button that can do so.Please assign me this issue.  Also till now there is no mechanism that tells us which page we are currently in, i can solve that too.

**Comment by AnuragK2** [comment]
I would too like to contribute to this issue. Can you please assign this to me.

**Comment by Swapnil-2503** [comment]
please guys i created this issue so that i can contribute in this project, if you have any other ideas you can create issue and say for assign me, this time it is for me.

**Comment by Mannu292001** [comment]
plz assign to me under gssoc'23

**Comment by khushiminda** [comment]
I AM A WEB DESIGNER I CAN ADD CALMING EFFECTS AND BUTTONS ON THIS
i can add a button that can do so.Please assign me this issue. 
Can you please assign this to me.
