### ISSUE TITLE
fixing the size moon image in night mode

### ISSUE THREAD

**Issue by vivekrawat21** [akshitagupta15june/PetMe#620]
**Describe the bug**

**To Reproduce**
1. Go to 'PetMe'
2. Click on 'sun image on nav bar'
3. See error

**Expected behavior**
On clicking the sun image the moon image should have to be of same size but it is not  of same size as sun image

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vivekrawat21** [comment]
Assign me this issue

**Comment by akanksha984** [comment]
I would like to work upon this issue. Please assign it to me Gssoc'23
