### ISSUE TITLE
To improve the colors of the home page of website

### ISSUE THREAD

**Issue by DhairyaMajmudar** [akshitagupta15june/PetMe#628]
**Describe the bug**
The colors used on home page are not visually effective and contrasting

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the website
2. And open the home page

**Expected behaviour**
There should be the use of cool/calming colors to make the website more visually effective
**Screenshots**
![image](https://github.com/akshitagupta15june/PetMe/assets/124715224/4e402bdf-53b9-4695-a073-b4236dbfef54)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Fire-Fox

**Expected Solution**
This issue can be solved by using somewhat light shades of the existing color,  also by using contrasting colors to differentiate between different sections and adding box-shadows

**Comment by DhairyaMajmudar** [comment]
I would love to solve this issue under GSSoC'23 by using HTML and CSS.

**Comment by Mannu292001** [comment]
plz assign to me under gssoc'23

**Comment by khushiminda** [comment]
As for my love towards animals ...i would love to improve the colours of your home page 
as i think that i have a very good taste in aesthetic!!!
I would love to solve this issue under GSSoC'23 by using HTML and CSS.
