### ISSUE TITLE
Add a "Subscribe to newsletter" option in the footer of website 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#63]
For example

![image](https://user-images.githubusercontent.com/57909583/193088839-0ec28b8c-1fc1-4aac-b20e-2b798622f778.png)

**Comment by Ahnaf-codes** [comment]
do you want it to be a pop up or just a normal card?

**Comment by akshitagupta15june** [comment]
in the bottom of site better is to keep in footer

**Comment by akshitagupta15june** [comment]
would u like to work in this?

**Comment by Ahnaf-codes** [comment]
> would u like to work in this?
yes! i can start tommorow

**Comment by omthakare16** [comment]
> would u like to work in this?
I would like to work on it

**Comment by Ahnaf-codes** [comment]
> would u like to work in this?

please assign me

**Comment by tanitoluwam** [comment]
> in the bottom of site better is to keep in footer

I would love to work on this....can i go ahead?

**Comment by Eyesnatcher-coder** [comment]
@akshitagupta15june can you please assign me the task?

**Comment by Ahnaf-codes** [comment]
@akshitagupta15june should it be in the footer or above it in place of contact us?

**Comment by akshitagupta15june** [comment]
It should be in footer left side besides the logo

**Comment by Ahnaf-codes** [comment]
Hey its done I've sent the pr please review it
