### ISSUE TITLE
Add a mission in the header

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#65]
"saving lives, saving animals"
This is the mission of this website so i want this mission to displayed in header but without disturbing the UI

**Comment by SammriddhGupta** [comment]
I would like to work on this issue!

**Comment by ujwxl23** [comment]
I would like to work on this issue!!

**Comment by akshitagupta15june** [comment]
assigning to @SammriddhGupta

**Comment by SammriddhGupta** [comment]
<img width="960" alt="PetMe_Mission_v1" src="https://user-images.githubusercontent.com/72302725/193454945-0b16e9ad-e348-46a1-aefc-880a9a9e73bd.PNG">
Does this look anything like what you had in mind for the mission?

**Comment by akshitagupta15june** [comment]
loooks good

**Comment by akshitagupta15june** [comment]
make a pr

**Comment by SammriddhGupta** [comment]
Alright!
