### ISSUE TITLE
Volunteer page hover bug

### ISSUE THREAD

**Issue by karthiknadar1204** [akshitagupta15june/PetMe#676]
**Describe the bug**
When we hover the submit button on the volunteer page, it expands beyond the required width making it look bad.

**To Reproduce**
Solution:
Here we will be fixing the width change that occurs on hovering the button by checking out the container it is contained in.

**Expected behavior**
The button is expected to have a bunch of hover effects and transitions and not increase in width by a few rems on hovering.

**Screenshots**
<img width="1371" alt="Screenshot 2023-05-27 at 7 50 40 AM" src="https://github.com/akshitagupta15june/PetMe/assets/95973644/84ae7476-504d-47c5-baff-f739d9317271">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS].  mac
 - Browser [e.g. chrome, safari]. chrome

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]  onePlus

**Additional context**

**Comment by karthiknadar1204** [comment]
I would like to work on this issue uunder gssoc'23

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor

**Comment by akshitagupta15june** [comment]
ok
