### ISSUE TITLE
Change Size of light & dark mode icon 

### ISSUE THREAD

**Issue by MOHDNEHALKHAN** [akshitagupta15june/PetMe#702]
@akshitagupta15june, as a gssoc'2023 contributor I want to work on this feature
Before Changes -

https://github.com/akshitagupta15june/PetMe/assets/125626654/341149dd-fd11-40c8-ac4b-2ba055356cc9

After Changes -

https://github.com/akshitagupta15june/PetMe/assets/125626654/ffeb256f-278f-4799-aa21-06a0e8c36649

**Comment by aniketnimkar** [comment]
hey i want work on this feature

**Comment by debdutta04** [comment]
Hi, @akshitagupta15june please assign me this

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor
