### ISSUE TITLE
Improving the button styles and adding a floating "back-to-top" button to enhance the website

### ISSUE THREAD

**Issue by yaten2302** [akshitagupta15june/PetMe#707]
**Is your feature request related to a problem? Please describe.**
I noticed that the "back to top" button is on the bottom of the page, which makes it difficult for the user to scroll to top quickly. Also I saw that the styling of the buttons can be improved so the user will be attracted by the new UI.

**Describe the solution you'd like**
I would like to add a floating "back to top" button and enhance the styling of buttons.

**Additional context**
![image](https://github.com/akshitagupta15june/PetMe/assets/129659514/19c69c33-e06a-4980-828f-67e4c270c07d)
Here is the screenshot of my changes.

Please assign this issue to me under gssos'23 so that I can contribute to this project.

**Comment by jfmartinz** [comment]
im working on it already. check the issue here #416
