### ISSUE TITLE
🚀 [IMPROVE] - PAGE PERFORMANCE BY OPTIMIZING IMAGE ASSETS

### ISSUE THREAD

**Issue by 0xabdulkhalid** [akshitagupta15june/PetMe#708]
| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    | The site uses `jpg`, `png` & `svg` types of images, but the `jpg` images are always tend to be more larger in size so that the page takes more bandwith to load it |
| **Solution Proposed**      | My plan is to convert all those `jpg` images to `webp` to minimize the page load time and bandwith|
| **Additional Context**     | Unoptimized images severly affects page load time, because it may uncomfortable for the people who having a moderate internet connection|

### Code of Conduct

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

Kindly assign me to this issue with `GSSoC'23` and `level 3` label for adding & improving new optimized images which improves the sites performance and SEO score!

**Comment by akshitagupta15june** [comment]
hey its not required currently
