### ISSUE TITLE
Bug Alert: Site isn't responsive in mobile phone 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#71]
![image](https://user-images.githubusercontent.com/57909583/193384008-0062170e-553b-4b88-adc3-485edc39cb61.png)
![image](https://user-images.githubusercontent.com/57909583/193384012-9368cc2f-fefe-4169-b79d-a8e1b2db8ea4.png)

**Comment by Ahnaf-codes** [comment]
hey can i work on this?

**Comment by akshitagupta15june** [comment]
Yes you can

**Comment by Ahnaf-codes** [comment]
What breakpoint should i use?

**Comment by Ahnaf-codes** [comment]
Hey it seems like i would need to rework Almost the whole desktop code since tailwind only supports min width media queries. Would that be a problem?

**Comment by akshitagupta15june** [comment]
Yes please work on it

**Comment by Ahnaf-codes** [comment]
so i will be using basic css if you dont mind

**Comment by Ahnaf-codes** [comment]
Is this good for the pet cards?
![Screenshot 2022-10-01 at 14-55-09 PetMe](https://user-images.githubusercontent.com/102795582/193401608-425dcf17-36be-4a48-9a28-3ed16e951a73.png)

**Comment by Ahnaf-codes** [comment]
Is this Good?
![Screenshot 2022-10-01 at 15-01-33 PetMe](https://user-images.githubusercontent.com/102795582/193401859-4136f7e7-b30d-401b-bbc4-1e467bce0fdd.png)

**Comment by akshitagupta15june** [comment]
Yes it is
