### ISSUE TITLE
Enhancing Page Appeal with Slideshow Background

### ISSUE THREAD

**Issue by manasi-jain** [akshitagupta15june/PetMe#716]
**Is your feature request related to a problem? Please describe.**

I wanted to bring your attention to an exciting enhancement idea for our project. I believe we can significantly improve the page appeal by implementing a slideshow background feature. This will create a visually captivating experience for the users and make the project more engaging.

**Describe the solution you'd like**
Implement the necessary changes to incorporate a slideshow background. The dynamic visuals will add a touch of elegance and interactivity to the page, enhancing the overall user experience.

If you find this enhancement request valid, I kindly request you to assign it to me under GSSoC '23
@akshitagupta15june  @Susmita-Dey  @muditchoudhary  @akshaaatt 

## **Demo**

https://github.com/akshitagupta15june/PetMe/assets/83013408/c224478d-ba21-4f92-9e15-71be9be44dec

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 as a contributor

**Comment by KavyaS5757** [comment]
I want to work on this issue. Please assign this to me.

**Comment by mehaksharma23** [comment]
I am interested on working this issue under GSSOC'23 as a contributor.
