### ISSUE TITLE
Request to make the "Pet News" section more creative

### ISSUE THREAD

**Issue by Nayanika-12** [akshitagupta15june/PetMe#728]
**Is your feature request related to a problem? Please describe.**
The "Pet News" section of the website has two pet trivia. The box expands containing the trivia expands horizontally and so does the text in it and it is very hard for a reader to read the text smoothly that way. Also, the background image makes the text in the last box ineligible to be read. There should be more interesting trivia on the "pet news" page. The content isn't enough to draw a lot of attention.

**Describe the solution you'd like**
I would like that the text box pops out a little when hovered over it and no box or text expanding takes place there. The trivia boxes should be arranged like a grid, with two boxes in each row. The background image should be something with lighter colors so that the text is properly visible as the text is very important here. I would also like to see more interesting trivia on that page and there should be up-to-date pet news information too. The entire page should look creative and different so that it can attract people.

**Comment by Titiksha2012** [comment]
Kindly assign this issue to me. I want to improve the frontend of the Pet News page. @akshitagupta15june @Nayanika-12

**Comment by akshitagupta15june** [comment]
how will u improve it @Nayanika-12 can u add some images
