### ISSUE TITLE
copy right reserved footer

### ISSUE THREAD

**Issue by Sushilverma002** [akshitagupta15june/PetMe#773]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/akshitagupta15june/PetMe/assets/114687502/802f3e3b-7e5e-4d01-8bb9-2bec0e67bc7d)

it seems no copy right footer
**Describe the solution you'd like**
![Untitled](https://github.com/akshitagupta15june/PetMe/assets/114687502/3e068d69-71d6-44d7-b6ca-65daa344d61d)
it look like this at the end of last section
**Describe alternatives you've considered**

**Additional context**

**Comment by akshitagupta15june** [comment]
go for it
