### ISSUE TITLE
Add footer to the Pet news section

### ISSUE THREAD

**Issue by PoulavBhowmick03** [akshitagupta15june/PetMe#780]
**Is your feature request related to a problem? Please describe.**

The pet news section ends without a footer, pushing the 2nd news to the bottom

**Describe the solution you'd like**

Add a footer similar to the home page

![image](https://github.com/akshitagupta15june/PetMe/assets/133862694/20645ba6-1b22-49bb-86f8-443b2ec01fe7)

**Comment by Dishant4277** [comment]
hello i would like to contribute in this issue for GSSOC'23, can you please assign this issue to me.

**Comment by itzanway** [comment]
please assign tis task to me
