### ISSUE TITLE
Scroll to top button

### ISSUE THREAD

**Issue by aakshitaa** [akshitagupta15june/PetMe#803]
It is difficult and inconvinient to scroll back to the top again and again instead just add a back to top button

**Comment by VanshilPatel** [comment]
Hey , this issue is already solved by someone else . Changes are made in the source code . Its just that they haven't made the PR . Shall I make the PR to this issue ?? or you can close the issue .

**Comment by aakshitaa** [comment]
yeah cool, I'll close the issue
