### ISSUE TITLE
[Feat] Add a translation section in README.md 

### ISSUE THREAD

**Issue by jfmartinz** [akshitagupta15june/PetMe#822]
**Is your feature request related to a problem? Please describe.**
Yes, the feature request is related to enhancing accessibility and reaching a wider audience for the project. (it is stated at "What's next for PetMe" section)

**Describe the solution you'd like**
I would like to add a translation section within the README file. This section will provide translated versions of the content in multiple languages, making it easier for users to understand the project's purpose, instructions, and documentation. I will add also a respective folder for the translation of the languages (to make it organize), and also instructions or rules on how they can add a translation.

**Describe alternatives you've considered**
Translation section within the README file would be a great idea for better accessibility and reach many people as possible

**Additional context**
Under gssoc assign this to me

**Comment by geoffreylgv** [comment]
Hey @jfmartinz, Very good idea. 

Hi @akshitagupta15june, I can work on French also Spanish version for that.
Kindly assign us under `GSSOC'23`.

Thanks.

**Comment by jfmartinz** [comment]
@akshitagupta15june what do you think?
