### ISSUE TITLE
[Bug]: Pet Logo Photo and Scroll Bar Icon Overlap Each Other in Footer Section

### ISSUE THREAD

**Issue by NarendraKoya999** [akshitagupta15june/PetMe#826]
### GSSOC'23
**Describe the bug**
- **Pet Logo Photo and Scroll Bar Icon Overlap Each Other. It's Bad Vision for Visitors.**

**To Reproduce**
1. Go to 'https://akshitagupta15june.github.io/PetMe/'
2.  Click on " '' 
3. Scroll down to **'Bottom of Footer Section'**
4. See error On **Footer Section like Logo Image and Scroll Bar Icon Overlap Each Other.**

**Expected behavior**
- **Separate Logo Image and Scroll Bar Icon and Solve in Two Cases**

> First Case
- **Logo Image Size is Slightly Decrease.**

> Second Case
- **Move Scroll Bar Icon to Slightly Left to Logo Image using Particular CSS Properties and Values.**

**Screenshots**
<img width="959" alt="petme-1" src="https://github.com/akshitagupta15june/PetMe/assets/84512164/2dc94b6f-127e-49f0-bc93-fd398dfb3e74">

**Desktop (please complete the following information):**
 - OS: [Microsoft Windows]
 - Browser [Chrome]
 - Version [114.0.5735.110 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 5 Pro]
 - OS: [9.0]
 - Browser [Chrome]
 - Version [114.0.5735.110 (Official Build)]

**Additional context**

**Comment by akshitagupta15june** [comment]
Go for it
