### ISSUE TITLE
Small issue in responsive navbar

### ISSUE THREAD

**Issue by Sachin4219** [akshitagupta15june/PetMe#837]
**Describe the bug**
The navbar has an anchor element for meet pets which has styling inconsistent with links in the navbar because of p-3 tailwind class
**To Reproduce**
1. Go to https://akshitagupta15june.github.io/PetMe
2. Compress the screen horizontally using developer tools window
3. Click on navbar menu icon
4. See error at pet me link

**Expected behavior**
The anchor element should have same styling as other elements
**Screenshots**
![image](https://github.com/akshitagupta15june/PetMe/assets/91952010/63c22fe4-4b7f-4ffc-9f52-a099ed5be50f)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Additional context**
Just a minor issue

**Comment by yeolesanskruti** [comment]
Hey @Sachin4219 
I am a GSSOC'23 contributor and would like to work on this.
Please assign me.
Thank you :)

**Comment by Sachin4219** [comment]
@yeolesanskruti Sorry to say but I am just a contributor here so, I cannot assign anyone even I was not assigned this issue I created. PR for this issue has already been submitted

**Comment by yeolesanskruti** [comment]
Ok. Thank you :)
