### ISSUE TITLE
Moment date formatter is required in Pet news screen.

### ISSUE THREAD

**Issue by asfaqehussain** [akshitagupta15june/PetMe#843]
**Describe the bug**
The date is not in the format it is showing a nonreadable format now like this: 2021-10-01T00:00:00.000Z

**To Reproduce**
1. Go to PetNews screen
2. Check the date in the news.

**Expected behavior**
Expected should a valid format of date and time which ever is required.

**Screenshots**

![Screenshot (26)](https://github.com/akshitagupta15june/PetMe/assets/51645676/549f7885-748b-48eb-b53c-63ec41039b42)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**
Please assign this issue to me so I can fix this and also share the required date format to be added in the Pet news section.

**Comment by akshitagupta15june** [comment]
ok
