### ISSUE TITLE
Adding a sticky navbar

### ISSUE THREAD

**Issue by yadavsairaj** [akshitagupta15june/PetMe#85]
Adding a sticky navbar so that it would be easy to navigate.
![image](https://user-images.githubusercontent.com/67747523/193402953-6e168f1e-7088-4d98-870c-8c18816d6dc5.png)

**Comment by yadavsairaj** [comment]
Can you assign me with this issue?

**Comment by Ahnaf-codes** [comment]
@akshitagupta15june can i do this?

**Comment by akshitagupta15june** [comment]
Hi this is not needed for the website
