### ISSUE TITLE
Reduce the main page navbar height

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#870]
https://akshitagupta15june.github.io/PetMe/index.html

**Comment by dishamodi0910** [comment]
Please assign it to me.

**Comment by Vidip-Ghosh** [comment]
Please assign this issue to me under gssoc'23

**Comment by RudraPrasadMahapatra** [comment]
kindly assign this issue to me under gssoc'23 . It can be my 1st open-source contribution.

**Comment by akshitagupta15june** [comment]
assigning to @dishamodi0910
