### ISSUE TITLE
Add some more pet news

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#871]
https://akshitagupta15june.github.io/PetMe/news.html#
Add 2 more funny or exciting pet news

**Comment by PoulavBhowmick03** [comment]
Please assign it to me @akshitagupta15june

**Comment by rafiya2003** [comment]
can you plz assign me this

**Comment by akshitagupta15june** [comment]
assigning @rafiya2003

**Comment by Shanukumar2929** [comment]
Can you please assign me this issue under gssoc'23.

**Comment by PoulavBhowmick03** [comment]
Hey @akshitagupta15june its been 3 weeks since this was assigned, can I please work on this?

**Comment by akshitagupta15june** [comment]
@rafiya2003 As you didn't update the previous pr, and its been a long time so I am assigning this issue to @PoulavBhowmick03
