### ISSUE TITLE
remove duplicate kafka blog

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#872]
https://akshitagupta15june.github.io/PetMe/blog.html

**Comment by dishamodi0910** [comment]
Please assign it to me. @akshitagupta15june

**Comment by Vidip-Ghosh** [comment]
Please assign this issue to me under gssoc'23

**Comment by RudraPrasadMahapatra** [comment]
kindly assign this issue to me under gssoc'23

**Comment by akshitagupta15june** [comment]
assigning

**Comment by AmulGaurav** [comment]
@akshitagupta15june I think you should close this issue as it is already solved under this pr: https://github.com/akshitagupta15june/PetMe/pull/882
