### ISSUE TITLE
Remove the meet pets and about us from the pet news section

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#874]
https://akshitagupta15june.github.io/PetMe/news.html
Also remove the contact us from navbar

**Comment by PoulavBhowmick03** [comment]
Please assign it to me @akshitagupta15june

**Comment by Nayanika-12** [comment]
Mam, please assign this to me. @akshitagupta15june . This will be my first issue under gssoc.

**Comment by PoulavBhowmick03** [comment]
I have completed the last issue, please assign this @akshitagupta15june

**Comment by ojaswi18** [comment]
@akshitagupta15june kindly assign this issue to me this would be my first issue.

**Comment by RitiChandak** [comment]
Please assign this issue to me

**Comment by rafiya2003** [comment]
can you plz assign me this work

**Comment by Naina047** [comment]
I would like to contribute in this. Please assign it to me under GSSOC'23 @akshitagupta15june

**Comment by lalitkumawat1m** [comment]
Hi @akshitagupta15june 
I have created pr for this issue. Could you please review and give feedback to me?
