### ISSUE TITLE
Remove the meet pets and about us from the donate section

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#876]
https://akshitagupta15june.github.io/PetMe/donate.html
Also remove contact us from navbar

**Comment by PoulavBhowmick03** [comment]
Please assign it to me @akshitagupta15june

**Comment by Nayanika-12** [comment]
Mam, please assign this to me. @akshitagupta15june . This will be my first issue under gssoc.

**Comment by Sch476** [comment]
I can fix this issue. Please assign this issue to me.

**Comment by akshitagupta15june** [comment]
assigning @Sch476

**Comment by Sch476** [comment]
@akshitagupta15june Should I also re-align the navbar a bit doing the changes you stated??

**Comment by suman-somu** [comment]
Issue fixed
