### ISSUE TITLE
Remove the meet pets and about us from the volunteer section 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#877]
https://akshitagupta15june.github.io/PetMe/volunteer.html
Also remove contact us from navbar

**Comment by rafiya2003** [comment]
can you plz assign me

**Comment by Nayanika-12** [comment]
Mam please assign this to me.

**Comment by akshitagupta15june** [comment]
assigning @Nayanika-12

**Comment by Nayanika-12** [comment]
https://github.com/akshitagupta15june/PetMe/pull/884/ Mam please a look at this PR.

**Comment by suman-somu** [comment]
This issue is fixed
