### ISSUE TITLE
Remove the meet pets and about us from the sos report section

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#878]
https://akshitagupta15june.github.io/PetMe/reportstary.html
Also remove contact us from navbar

**Comment by Tarek-Kidwai** [comment]
Hi, Please kindly assign me to this. Thanks

**Comment by Nayanika-12** [comment]
Mam, please assign this to me. @akshitagupta15june . This will be my first issue under gssoc.

**Comment by akshitagupta15june** [comment]
assigning

**Comment by Naina047** [comment]
If it's still not done, I would like to contribute in this. Please assign it to me under GSSOC'23

**Comment by Tarek-Kidwai** [comment]
Hi ,

I am almost done with it. And finalizing it tonight.

Thanks,
Tarek

**Comment by suman-somu** [comment]
This issue has been partially solved by this pr - #900 . 
Left tasks are to remove contact us link.
