### ISSUE TITLE
Text not visible on support us page

### ISSUE THREAD

**Issue by sumitkr2000** [akshitagupta15june/PetMe#889]
**Describe the bug**

Hey @akshitagupta15june The heading is not visible on the support us page. Please assign me this issue. Thank you!

**To Reproduce**

**Expected behavior**

The heading should be visible on the support us page.

**Screenshots**

![image](https://github.com/akshitagupta15june/PetMe/assets/100675296/0b1cd9b0-4eae-440b-a04c-de56466ddf72)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lalitkumawat1m** [comment]
Hi @akshitagupta15june 
I have raised a pr on this issue. Could you please review it and give feedback?

**Comment by sumitkr2000** [comment]
> Hi @akshitagupta15june I have raised a pr on this issue. Could you please review it and give feedback?

Bhai issue maine create kiya aur tune pr kr diya 😂😂
