### ISSUE TITLE
Improve contact us form

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#9]

**Comment by aswin2108** [comment]
I am really interested in doing this. Could you please assign this to me? I would really love to do this as a part of hacktoberfest.

**Comment by akshitagupta15june** [comment]
ok but contributions will be counted after 1st oct

**Comment by Karmpatel960** [comment]
Can you please Assign me this . I want to do it.

**Comment by akshitagupta15june** [comment]
@Karmpatel960 you can work on diffrent issues as this issue is for @aswin2108

**Comment by aswin2108** [comment]
@akshitagupta15june is it necessary to redirect to formspree page after submission or will an alert saying "the form submitted" is fine?

**Comment by akshitagupta15june** [comment]
hey @aswin2108 actually here formspree which is used is a html form service, we don't have a backend so we used a api service so while submitting the form the service only takes to that page so regarding this issue you can work on styling of the form

**Comment by aswin2108** [comment]
@akshitagupta15june okay, I started looking at how submissions should be working and noticed that the form is not getting cleared after submitting that's why I asked. So I don't have to clear this issue and regarding submitting it and should focus only on the look and feel of the form right?

**Comment by akshitagupta15june** [comment]
yes
