### ISSUE TITLE
Design the scrollbar

### ISSUE THREAD

**Issue by zugzwang03** [akshitagupta15june/PetMe#92]
**Is your feature request related to a problem? Please describe.**
I want to customize the scrollbar of the website, to align it with the overall designing.
**Describe the solution you'd like**
I want to customize the scrollbar of the website, to align it with the overall designing.
**Describe alternatives you've considered**

**Additional context**
I want to make this contribution under hacktoberfest'22.

**Comment by akshitagupta15june** [comment]
what changes will this make?

**Comment by zugzwang03** [comment]
It will customize the scrollbar, or rather beautify it. Like now, the website has a scrollbar of white and grey combination, I can add a scrollbar of brownish colour to keep it in alignment with the whole layout of the website.

**Comment by akshitagupta15june** [comment]
Fine go for it

**Comment by minhaj-313** [comment]
i want to add Scroll bar could you please Assign to me
