### ISSUE TITLE
text is not visible 

### ISSUE THREAD

**Issue by RitiChandak** [akshitagupta15june/PetMe#923]
**Describe the bug**
The bug is that the "Adopt Me" text remains invisible regardless of whether the application is in light mode or dark mode.
**To Reproduce**
1. Go to 'Home'
3. Scroll down to 'Meet our Friends Here'

**Expected behavior**
adopt me text should be visible

**Screenshots**
![image](https://github.com/akshitagupta15june/PetMe/assets/96969496/1ac37658-203c-4c85-8712-819493e0f0c2)
in light mode

![image](https://github.com/akshitagupta15june/PetMe/assets/96969496/8dc207cb-61a0-40a5-b147-042c8c6de8cb)
in dark mode 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GriffinAnnshual** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by akshitagupta15june** [comment]
Go for it
