### ISSUE TITLE
Enhancing the UI and color combination of homepage

### ISSUE THREAD

**Issue by jaivsh** [akshitagupta15june/PetMe#930]
**Is your feature request related to a problem? Please describe.**
I'd improve the UI associated with the homepage, which includes the cards of individual animals, correcting the color schema of some elements, and so on. This would reduce the design complexity of the webpage and make it more smooth and easy for the audience.   

**Additional context**
<img width="1470" alt="Screenshot 2023-07-03 at 11 44 51 PM" src="https://github.com/akshitagupta15june/PetMe/assets/93859359/a9ec8b9c-6195-4599-93c7-6498c2f2b074">

**Comment by akshitagupta15june** [comment]
go for it
