### ISSUE TITLE
hover effect to buttons and inconsistent navbar

### ISSUE THREAD

**Issue by Komal73** [akshitagupta15june/PetMe#931]
- it did not encouraged me to click on the buttons as they were not interactive, no color change,  no animation.
I want to make all the buttons of page including social icons interactive by adding hover effect
- also the navbar is not the same on different pages as it has different font size some options not present, thus creating confusion

**Comment by Komal73** [comment]
kindly assign me this issue under GSSOC 23

**Comment by Komal73** [comment]
@akshitagupta15june

**Comment by akshitagupta15june** [comment]
its not required currently 
thankyou
