### ISSUE TITLE
"Become A Volunteer" page styling.

### ISSUE THREAD

**Issue by JoeNeedham** [akshitagupta15june/PetMe#933]
**Is your feature request related to a problem? Please describe.**

I want to improve the styling of the "Become A Volunteer" page. Right now it is not consistent with the rest of the site.

**Describe the solution you'd like**

The styling would mirror the "contact us" form on the home page.
I would also additionally add the footer to the page.

**Additional context**

<img width="1432" alt="Screen Shot 2023-07-04 at 1 59 05 PM" src="https://github.com/akshitagupta15june/PetMe/assets/83193580/d8132c2f-c68c-46e1-bbc2-a63de6152238">
<img width="1432" alt="Screen Shot 2023-07-04 at 1 59 34 PM" src="https://github.com/akshitagupta15june/PetMe/assets/83193580/57940b0d-7fde-4908-9e09-b9b974c14fcc">

**Comment by akshitagupta15june** [comment]
hey its not required currently 
Thanks
