### ISSUE TITLE
[Maintainance]: Project Restructuring

### ISSUE THREAD

**Issue by Viveksati5143** [akshitagupta15june/PetMe#942]
Issue:
Codebase is not organized making it difficult for new contributors like me to understand!!

Solution:
Separate folders for different pages along with their .html, .css, and .js files
Adding pictures in separate folders
Setting proper links accordingly for proper functioning of website 

Screenshot:
<img width="159" alt="image" src="https://github.com/akshitagupta15june/PetMe/assets/100852245/112b3682-0656-408a-9e53-f7f6833cbfd6">

**Comment by akshitagupta15june** [comment]
Hey this is new not required
Already we are migrating project to reactjs
