### ISSUE TITLE
Improve UI of navbar items

### ISSUE THREAD

**Issue by nashira26** [akshitagupta15june/PetMe#949]
With the google translate item visible, the navbar items seem bit crowded. This can be solved by font size reduction or updating navbar design.
Please assign this to me under GSSoC'23.

![Screenshot 2023-07-09 164037](https://github.com/akshitagupta15june/PetMe/assets/32673772/909b5322-b346-4a44-8886-7885302db1a2)

**Comment by akshitagupta15june** [comment]
hey its already good so no improvement required

**Comment by akshitagupta15june** [comment]
Actually i am planning to remove google translate so it will look more cleaner

**Comment by nashira26** [comment]
Yeah, that seems better.
