### ISSUE TITLE
The bottom to top buttons overlapping

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#960]
a single button should be there
https://akshitagupta15june.github.io/PetMe/#top

**Comment by Viveksati5143** [comment]
Sure happy to fix

**Comment by akshitagupta15june** [comment]
![image](https://github.com/akshitagupta15june/PetMe/assets/57909583/df5ae878-71f9-4605-b732-d8458462aa26)
@Viveksati5143

**Comment by MeenuyD** [comment]
I would like to work on this issue please assign it to me
