### ISSUE TITLE
Add LinkedIn and Twitter links in footer section

### ISSUE THREAD

**Issue by blindaks** [akshitagupta15june/PetMe#963]
**Is your feature request related to a problem? Please describe.**
I want to add LinkedIn and Twitter icons in the footer section.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sakshimaluskar2** [comment]
I want to add LinkedIn and Twitter icons in the footer section.        

Solution -
Outreach and Networking: LinkedIn and Twitter are platforms that can be used to reach a wider audience and connect with individuals and organizations interested in animal welfare, pet adoption, or related fields. By including these links, the website can expand its network and engage with professionals, volunteers, and potential adopters who are active on these platforms.

Community Engagement: LinkedIn and Twitter can be used to foster a sense of community and encourage engagement among individuals interested in pet adoption. By providing links to these platforms, the website can create a space for discussions, sharing success stories, promoting events, and raising awareness about animal adoption-related issues. It allows visitors to connect with like-minded individuals and participate in ongoing conversations.

I will add LinkedIn and Twitter icons int footer section by writting code int index.html for that specific icon in social icon section.

![pet](https://github.com/akshitagupta15june/PetMe/assets/128711718/28755904-e1da-41f6-a45d-6768f0b208e4)

**Comment by sakshimaluskar2** [comment]
hey @akshitagupta15june I will be able to do this, please assign this issue to me.

**Comment by lalitkumawat1m** [comment]
I want to work on this issue. Could you please assign to me?

**Comment by akshitagupta15june** [comment]
there are no handles currently, I will remove them from footer
