### ISSUE TITLE
Pet News Addition

### ISSUE THREAD

**Issue by Harshu467** [akshitagupta15june/PetMe#977]
**Is your feature request related to a problem? Please describe.**
Only two Pet News Available which is not looking good
**Describe the solution you'd like**
There are only two news of pets why wont we add more news and we can create api or free apis available and fetch them to show all news

**Comment by Harshu467** [comment]
@akshitagupta15june  Assign it to me

**Comment by akshitagupta15june** [comment]
go for it!

**Comment by Harshu467** [comment]
This issue has been resolved and merged successfully , Closing it
